// angular_ngzorro/src/app/reservation-record/reservation-record-list.component.ts
import {Component, OnInit, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {ReservationRecordService} from '../../service/reservation-record.service';
import {ReservationRecordQueryForm} from '../../types/req/ReservationRecordQueryForm';
import {SharedModule} from '../shared.module';
import {ReservationRecord} from '../../types/resp/ReservationRecord';
import {Page} from '../../types/page';
import {ReservationRecordAddComponent} from './reservation-record-add.component';
import {ReservationRecordViewComponent} from './reservation-record-view.component';
import {NzModalService} from 'ng-zorro-antd/modal';
import {RoomSelectorComponent} from '../room/room-selector.component';
import {exportToExcel} from '../../util/exportUtil';
import {getReservationRecordStatusText} from '../../util/dictTranslator';

@Component({
  selector: 'reservation-record-list',
  imports: [
    RoomSelectorComponent,
    ReservationRecordAddComponent,
    ReservationRecordViewComponent,
    SharedModule
  ],
  templateUrl: './reservation-record-list.component.html',
  standalone: true
})
export class ReservationRecordListComponent implements OnInit {
  searchForm!: FormGroup;
  searchLoading: boolean = false
  listOfData: ReservationRecord[] = [];
  total: number = 0

  @ViewChild(RoomSelectorComponent, { static: false }) roomSelectorComponent!: RoomSelectorComponent;
  @ViewChild(ReservationRecordAddComponent, { static: false }) reservationRecordAddComponent!: ReservationRecordAddComponent;
  @ViewChild(ReservationRecordViewComponent, { static: false }) reservationRecordViewComponent!: ReservationRecordViewComponent;

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private reservationRecordService: ReservationRecordService,
    private modal: NzModalService
  ) {}

  ngOnInit(): void {
    this.searchForm = this.fb.group({
      roomId: [0],
      roomNumber: [''],
      name: [''],
      phone: [''],
      status: [undefined],
    })
    this.onSearch()
  }

  onReset() {
    this.searchForm.reset()
  }

  onSearch() {
    try {
      this.searchLoading = true
      this.reservationRecordService.find(new ReservationRecordQueryForm(this.searchForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          const page: Page<ReservationRecord> | undefined = resp.data
          if (page && page.list.length > 0) {
            this.listOfData = page.list
            this.total = page.total
          }
        },
        complete: () => {
          this.searchLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onAdd() {
    this.reservationRecordAddComponent.display(0)
  }

  onExport() {
    try {
      const headers = ['房号','姓名','联系电话','预定入驻时间','备注','状态']
      this.searchLoading = true
      this.reservationRecordService.find(new ReservationRecordQueryForm(this.searchForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1 || !resp.data || resp.data.list.length < 1) {
            this.message.error('无数据导出')
            return
          }
          const exportData = []
          for (const d of resp.data.list) {
            exportData.push([d.roomNumber, d.name, d.phone, d.checkInTime, d.remark, getReservationRecordStatusText(d.status)])
          }
          exportToExcel(headers, exportData)
        },
        complete: () => {
          this.searchLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  editRow(id: number) {
    this.reservationRecordAddComponent.display(id)
  }

  delRow(id: number) {
    this.modal.confirm({
      nzTitle: '<i>删除提示</i>',
      nzContent: '<b>确定要删除吗?</b>',
      nzOnOk: () => {
        this.reservationRecordService.del(id).subscribe({
          next: (resp) => {
            if (resp && resp.code === 1) {
              this.message.success('删除成功!')
              this.onSearch()
            } else {
              this.message.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
            }
          },
          complete: () => {
            this.searchLoading = false
          }
        })
      }
    });
  }

  detailRow(record: ReservationRecord) {
    this.reservationRecordViewComponent.display(record)
  }

  findRoom() {
    this.roomSelectorComponent.display()
  }

  handleRoomSelectedEvent(selectedRoom: { roomId?: number; roomNumber?: string; }) {
    if (selectedRoom && 'roomId' in selectedRoom) {
      this.searchForm.patchValue(selectedRoom);
    }
  }

  onAdded(addedFlag: boolean) {
    if (addedFlag) {
      this.onSearch()
    }
  }
}

<nz-breadcrumb class="breadcrumb">
  <nz-breadcrumb-item>
    <a>首页</a>
  </nz-breadcrumb-item>
  <nz-breadcrumb-item>预定记录列表</nz-breadcrumb-item>
</nz-breadcrumb>
<form nz-form class="search-form" [formGroup]="searchForm" (keydown.enter)="$event.preventDefault();onSearch()" nzLayout="inline">
  <nz-form-item>
    <nz-form-label nzFor="roomNumber">房号</nz-form-label>
    <nz-form-control>
      <nz-input-group nzSearch [nzAddOnAfter]="roomNumberSuffixIconButton">
        <input nz-input formControlName="roomNumber" placeholder="请选择房号" readonly />
      </nz-input-group>
      <ng-template #roomNumberSuffixIconButton>
        <button nz-button nzType="primary" nzSearch (click)="findRoom()"><nz-icon nzType="search" /></button>
      </ng-template>
    </nz-form-control>
  </nz-form-item>
  <nz-form-item>
    <nz-form-label nzFor="name">姓名</nz-form-label>
    <nz-form-control>
      <input nz-input formControlName="name" placeholder="请输入姓名" />
    </nz-form-control>
  </nz-form-item>
  <nz-form-item>
    <nz-form-label nzFor="phone">联系电话</nz-form-label>
    <nz-form-control>
      <input nz-input formControlName="phone" placeholder="请输入联系电话" />
    </nz-form-control>
  </nz-form-item>
  <nz-form-item>
    <nz-form-label nzFor="status">状态</nz-form-label>
    <nz-form-control>
      <nz-select formControlName="status" class="custom-select-width">
        <nz-option nzLabel="已预定" [nzValue]="10"></nz-option>
        <nz-option nzLabel="已入驻" [nzValue]="20"></nz-option>
        <nz-option nzLabel="已取消" [nzValue]="30"></nz-option>
      </nz-select>
    </nz-form-control>
  </nz-form-item>
  <button nz-button type="button" nzType="primary" [nzLoading]="searchLoading" (click)="onSearch()">查询</button>
  <button nz-button type="button" class="margin-button" (click)="onReset()">重置</button>
  <button nz-button type="button" class="margin-button" nzType="primary" (click)="onAdd()">新增</button>
  <button nz-button type="button" class="margin-button" nzType="primary" [nzLoading]="searchLoading" (click)="onExport()">导出</button>
</form>
<nz-table #basicTable [nzData]="listOfData" [nzTotal]="total" [nzLoading]="searchLoading" nzSize="small">
  <thead>
    <tr>
      <th>房号</th>
      <th>姓名</th>
      <th>联系电话</th>
      <th>预定入驻时间</th>
      <th>备注</th>
      <th>状态</th>
      <th nzWidth="250px">操作</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let data of basicTable.data">
      <td>{{data.roomNumber}}</td>
      <td>{{data.name}}</td>
      <td>{{data.phone}}</td>
      <td>{{data.checkInTime}}</td>
      <td>{{data.remark}}</td>
      <td>
        <ng-container *ngIf="data.status === 10">已预定</ng-container>
        <ng-container *ngIf="data.status === 20">已入驻</ng-container>
        <ng-container *ngIf="data.status === 30">已取消</ng-container>
      </td>
      <td>
        <button nz-button type="button" nzType="primary" (click)="editRow(data.id)">编辑</button>
        <button nz-button type="button" nzDanger class="margin-button" (click)="delRow(data.id)">删除</button>
        <button nz-button type="button" class="margin-button" (click)="detailRow(data)">详情</button>
      </td>
    </tr>
  </tbody>
</nz-table>
<room-selector (roomSelectedEvent)="handleRoomSelectedEvent($event)"></room-selector>
<reservation-record-add (addedEvent)="onAdded($event)"></reservation-record-add>
<reservation-record-view></reservation-record-view>

// v3_el/src/views/reservationRecord/ReservationRecordList.vue
<template>
  <div class="reservationRecord-list">
    <div class="breadcrumb">
      <el-breadcrumb separator="/">
        <el-breadcrumb-item to="Home" :replace="true">首页</el-breadcrumb-item>
        <el-breadcrumb-item>预定记录列表</el-breadcrumb-item>
      </el-breadcrumb>
    </div>
    <el-form :inline="true" :model="reservationRecordQueryForm" ref="reservationRecordQueryFormRef" :rules="rules">
      <el-form-item label="房号" prop="roomNumber">
        <el-input v-model="reservationRecordQueryForm.roomNumber" placeholder="请选择房号" readonly="readonly">
          <template #suffix>
            <el-icon @click="findRoom"><Search/></el-icon>
          </template>
        </el-input>
      </el-form-item>
      <el-form-item label="姓名" prop="name">
        <el-input v-model="reservationRecordQueryForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
      </el-form-item>
      <el-form-item label="联系电话" prop="phone">
        <el-input v-model="reservationRecordQueryForm.phone" placeholder="请输入联系电话" maxlength="20"></el-input>
      </el-form-item>
      <el-form-item label="状态" prop="status">
        <el-select v-model="reservationRecordQueryForm.status" placeholder="请选择状态" class="select-custom">
          <el-option label="已预定" :value="10"></el-option>
          <el-option label="已入驻" :value="20"></el-option>
          <el-option label="已取消" :value="30"></el-option>
        </el-select>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="onSearch">查询</el-button>
        <el-button @click="onReset">重置</el-button>
        <el-button type="primary" @click="onAdd">新增</el-button>
        <el-button type="primary" @click="onExport">导出</el-button>
      </el-form-item>
    </el-form>

    <el-table
      :data="state.tableData"
      border
      v-loading="state.loading"
      size="small"
      header-cell-class-name="table-header-cell-font"
      cell-class-name="table-cell-font">
      <el-table-column prop="roomNumber" label="房号"></el-table-column>
      <el-table-column prop="name" label="姓名"></el-table-column>
      <el-table-column prop="phone" label="联系电话"></el-table-column>
      <el-table-column prop="checkInTime" label="预定入驻时间"></el-table-column>
      <el-table-column prop="remark" label="备注"></el-table-column>
      <el-table-column prop="status" label="状态">
        <template v-slot="{ row }">
          <div v-if="row.status === 10">已预定</div>
          <div v-if="row.status === 20">已入驻</div>
          <div v-if="row.status === 30">已取消</div>
        </template>
      </el-table-column>
      <el-table-column fixed="right" label="操作" width="250">
        <template v-slot="{ row }">
          <el-button @click.prevent="editRow(row.id)" type="primary">编辑</el-button>
          <el-button @click.prevent="delRow(row.id)" type="danger" plain>删除</el-button>
          <el-button @click.prevent="detailRow(row.id)" type="primary" plain>详情</el-button>
        </template>
      </el-table-column>
    </el-table>
    <div class="table-pagination">
      <el-pagination
        @current-change="changePage"
        :current-page="state.currentPage"
        :page-sizes="state.pageSizes"
        :page-size="state.pageSize"
        background
        layout="total, prev, pager, next, jumper"
        :total="state.total">
      </el-pagination>
    </div>
    <el-dialog v-model="roomSelectorVisible" v-if="roomSelectorVisible" title="房间选择器(双击行选中)" :top="dialogTop" :width="dialogWidth">
      <room-selector @room-selected-event="handleRoomSelectedEvent">
      </room-selector>
    </el-dialog>
    <el-dialog v-model="reservationRecordAddVisible" v-if="reservationRecordAddVisible" :title="reservationRecordAddTitle" :top="dialogTop" :width="dialogWidth">
      <reservation-record-add :id="selectedReservationRecordId" @close-reservation-record-add-event="handleCloseReservationRecordAddEvent" @reset-reservation-record-add-event="handleResetReservationRecordAddEvent">
      </reservation-record-add>
    </el-dialog>
    <el-dialog v-model="reservationRecordViewVisible" v-if="reservationRecordViewVisible" title="预定记录详情" :top="dialogTop" :width="dialogWidth">
      <reservation-record-view :id="selectedReservationRecordId" @close-reservation-record-view-event="handleCloseReservationRecordViewEvent">
      </reservation-record-view>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { inject, onMounted, reactive, ref, toRefs } from 'vue'
import reservationRecordApi from '@/api/reservationRecordApi'
import type { ReservationRecordQueryForm } from '@/types/req/reservationRecordQueryForm'
import type { ReservationRecord } from '@/types/resp/reservationRecord'
import { ElMessage, ElMessageBox, type FormInstance } from 'element-plus'
import type { Result } from '@/types/result'
import type { Page } from '@/types/page'
import { Search } from '@element-plus/icons-vue'
import RoomSelector from '@/views/room/RoomSelector.vue'
import ReservationRecordAdd from '@/views/reservationRecord/ReservationRecordAdd.vue'
import ReservationRecordView from '@/views/reservationRecord/ReservationRecordView.vue'
import { exportToExcel } from '@/composables/exportUtil.ts'
import { getReservationRecordStatusText } from '@/composables/dictTranslator.ts'

const reservationRecordQueryFormRef = ref<FormInstance | null>(null);
const reservationRecordQueryForm = reactive<ReservationRecordQueryForm>({
  roomId: 0,
  roomNumber: '',
  name: '',
  phone: '',
  status: undefined,
})

const state = reactive({
  loading: false,
  tableData: [] as ReservationRecord[], // 数据列表
  total: 0, // 总条数
  currentPage: 1, // 当前页
  pageSize: 10, // 分页大小
  pageSizes: [10, 20, 50]
})
const selectedReservationRecordId = ref<number>(0)
const roomSelectorVisible = ref<boolean>(false)
const reservationRecordAddVisible = ref<boolean>(false)
const reservationRecordViewVisible = ref<boolean>(false)
const reservationRecordAddTitle = ref<string>('')
const dialogTop = ref<string>('')
const dialogWidth = ref<string>('')

const rules = reactive({
});

onMounted(() => {
  onSearch()
  const globalState = inject('globalState', {} as { dialogWidth?: string, dialogTop?: string })
  if (!globalState) {
    throw new Error('globalState is not provided');
  }
  const globalStateRefs = toRefs(globalState)
  if (globalStateRefs.dialogWidth) {
    dialogWidth.value = globalStateRefs.dialogWidth.value || ''
  }
  if (globalStateRefs.dialogTop) {
    dialogTop.value = globalStateRefs.dialogTop.value || ''
  }
})

const getPageData = async () => {
  try {
    state.loading = true
    const resp: Result<Page<ReservationRecord>> = await reservationRecordApi.find(reservationRecordQueryForm)
    if (resp && resp.code === 1) {
      if (resp.data) {
      const page: Page<ReservationRecord> = resp.data
        if (page && page.list.length > 0) {
          state.tableData = page.list
          state.total = page.total
        }
      }
    }
  } catch (e) {
    console.log('获取数据异常', e)
  } finally {
    state.loading = false
  }
}
const onSearch = () => {
  getPageData()
}

const changePage = (val: number) => {
  state.currentPage = val
  getPageData()
}

const onReset = () => {
  if (reservationRecordQueryFormRef.value) {
    reservationRecordQueryFormRef.value.resetFields()
  }
  state.currentPage = 1
  getPageData()
}

const onAdd = () => {
  selectedReservationRecordId.value = 0
  reservationRecordAddVisible.value = true
  reservationRecordAddTitle.value = '预定记录新增'
}
const editRow = (id: number) => {
  selectedReservationRecordId.value = id
  reservationRecordAddVisible.value = true
  reservationRecordAddTitle.value = '预定记录编辑'
}
const delRow = (id: number) => {
  if (!id) {
    return
  }
  ElMessageBox.confirm(
    '确定要删除吗?',
    '删除提示',
    {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning',
    }
  ).then(() => {
    reservationRecordApi.del(id)
      .then((resp) => {
        if (resp && resp.code === 1) {
          ElMessage.success('删除成功!')
          onSearch()
        } else {
          ElMessage.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
        }
      })
      .catch(error => {
        console.error('操作失败:', error)
      })
  }).catch(() => {})
}
const detailRow = (id:number) => {
  selectedReservationRecordId.value = id
  reservationRecordViewVisible.value = true
}

const findRoom = () => {
  roomSelectorVisible.value = true
}

const handleRoomSelectedEvent = (selectedRoom: any) => {
  roomSelectorVisible.value = false
  if (selectedRoom && 'roomId' in selectedRoom && reservationRecordQueryForm.roomId !== selectedRoom['roomId']) {
    reservationRecordQueryForm.roomId = selectedRoom['roomId']
    reservationRecordQueryForm.roomNumber = selectedRoom['roomNumber']
  }
}

const handleCloseReservationRecordViewEvent = () => {
  reservationRecordViewVisible.value = false
}

const handleResetReservationRecordAddEvent = () => {
  reservationRecordAddTitle.value = '预定记录新增'
}

const handleCloseReservationRecordAddEvent = (params: { search?: boolean } | undefined) => {
  if (params && params.search) {
    onSearch()
  }
  reservationRecordAddVisible.value = false
}

const onExport = () => {
  const headers = ['房号','姓名','联系电话','预定入驻时间','备注','状态']
  reservationRecordApi.find(reservationRecordQueryForm).then(data => {
    if (!data || !data.data || data.data.list.length < 1) {
      ElMessage.error('无数据导出')
      return
    }
    const exportData = []
    for (const d of data.data.list) {
      exportData.push([d.roomNumber, d.name, d.phone, d.checkInTime, d.remark, getReservationRecordStatusText(d.status)])
    }
    exportToExcel(headers, exportData)
  })
}
</script>

<style lang="scss">
</style>
