// angular_ngzorro/src/app/reservation-record/reservation-record-selector.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {ReservationRecordService} from '../../service/reservation-record.service';
import {ReservationRecordQueryForm} from '../../types/req/ReservationRecordQueryForm';
import {SharedModule} from '../shared.module';
import {ReservationRecord} from '../../types/resp/ReservationRecord';
import {Page} from '../../types/page';
import {NzModalService} from 'ng-zorro-antd/modal';
import {MODAL_WIDTH} from '../../const';
import {RoomSelectorComponent} from '../room/room-selector.component';

@Component({
  selector: 'reservation-record-selector',
  imports: [
    RoomSelectorComponent,
    SharedModule
  ],
  templateUrl: './reservation-record-selector.component.html',
  standalone: true
})
export class ReservationRecordSelectorComponent implements OnInit {
  searchForm!: FormGroup;
  searchLoading: boolean = false
  listOfData: ReservationRecord[] = [];
  total: number = 0
  isVisible: boolean = false
  title: string = '预定记录选择器(双击行选中)'
  modalWidth: string = MODAL_WIDTH

  @ViewChild(RoomSelectorComponent, { static: false }) roomSelectorComponent!: RoomSelectorComponent;

  @Output() reservationRecordSelectedEvent = new EventEmitter<{}>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private reservationRecordService: ReservationRecordService,
    private modal: NzModalService
  ) {}

  ngOnInit(): void {
    this.searchForm = this.fb.group({
      roomId: [0],
      roomNumber: [''],
      name: [''],
      phone: [''],
      status: [undefined],
    })
    this.onSearch()
  }

  onReset() {
    this.searchForm.reset()
  }

  onSearch() {
    try {
      this.searchLoading = true
      this.reservationRecordService.find(new ReservationRecordQueryForm(this.searchForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          const page: Page<ReservationRecord> | undefined = resp.data
          if (page && page.list.length > 0) {
            this.listOfData = page.list
            this.total = page.total
          }
        },
        complete: () => {
          this.searchLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onRowDblClick(row: ReservationRecord, event: MouseEvent) {
    this.isVisible = false
    this.reservationRecordSelectedEvent.emit({
      reservationRecordId: row.id,
      preName: row.name,
      prePhone: row.phone,
    });
  }

  onBack() {
    this.isVisible = false
  }

  display() {
    this.isVisible = true
    this.searchForm.reset();
  }

  findRoom() {
    this.roomSelectorComponent.display()
  }

  handleRoomSelectedEvent(selectedRoom: { roomId?: number; roomNumber?: string; }) {
    if (selectedRoom && 'roomId' in selectedRoom) {
      this.searchForm.patchValue(selectedRoom);
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form nz-form class="search-form" [formGroup]="searchForm"  (keydown.enter)="$event.preventDefault();onSearch()" nzLayout="inline">
            <nz-form-item>
        <nz-form-label nzFor="roomNumber">房号</nz-form-label>
        <nz-form-control>
          <nz-input-group nzSearch [nzAddOnAfter]="roomNumberSuffixIconButton">
            <input nz-input formControlName="roomNumber" placeholder="请选择房号" readonly />
          </nz-input-group>
          <ng-template #roomNumberSuffixIconButton>
            <button nz-button nzType="primary" nzSearch (click)="findRoom()"><nz-icon nzType="search" /></button>
          </ng-template>
        </nz-form-control>
      </nz-form-item>
<nz-form-item>
        <nz-form-label nzFor="name">姓名</nz-form-label>
        <nz-form-control>
          <input nz-input formControlName="name" placeholder="请输入姓名" />
        </nz-form-control>
      </nz-form-item>
<nz-form-item>
        <nz-form-label nzFor="phone">联系电话</nz-form-label>
        <nz-form-control>
          <input nz-input formControlName="phone" placeholder="请输入联系电话" />
        </nz-form-control>
      </nz-form-item>
      <nz-form-item>
        <nz-form-label nzFor="status">状态</nz-form-label>
        <nz-form-control>
          <nz-select formControlName="status" class="custom-select-width">
            <nz-option nzLabel="已预定" [nzValue]="10"></nz-option>
            <nz-option nzLabel="已入驻" [nzValue]="20"></nz-option>
            <nz-option nzLabel="已取消" [nzValue]="30"></nz-option>
          </nz-select>
        </nz-form-control>
      </nz-form-item>
      <button nz-button type="button" nzType="primary" [nzLoading]="searchLoading" (click)="onSearch()">查询</button>
      <button nz-button type="button" class="margin-button" (click)="onReset()">重置</button>
    </form>
    <nz-table #basicTable [nzData]="listOfData" [nzTotal]="total" [nzLoading]="searchLoading" nzSize="small">
      <thead>
        <tr>
          <th>房号</th>
          <th>姓名</th>
          <th>联系电话</th>
          <th>预定入驻时间</th>
          <th>备注</th>
          <th>状态</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let data of basicTable.data" (dblclick)="onRowDblClick(data, $event)">
          <td>{{data.roomNumber}}</td>
          <td>{{data.name}}</td>
          <td>{{data.phone}}</td>
          <td>{{data.checkInTime}}</td>
          <td>{{data.remark}}</td>
          <td>
            <ng-container *ngIf="data.status === 10">已预定</ng-container>
            <ng-container *ngIf="data.status === 20">已入驻</ng-container>
            <ng-container *ngIf="data.status === 30">已取消</ng-container>
          </td>
        </tr>
      </tbody>
    </nz-table>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
<room-selector (roomSelectedEvent)="handleRoomSelectedEvent($event)"></room-selector>

// v3_el/src/views/reservationRecord/ReservationRecordSelector.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
      <el-form :inline="true" :model="reservationRecordQueryForm" ref="reservationRecordQueryFormRef" :rules="rules">
        <el-form-item label="房号" prop="roomNumber">
          <el-input v-model="reservationRecordQueryForm.roomNumber" placeholder="请选择房号" readonly="readonly">
            <template #suffix>
              <el-icon @click="findRoom"><Search/></el-icon>
            </template>
          </el-input>
        </el-form-item>
        <el-form-item label="姓名" prop="name">
          <el-input v-model="reservationRecordQueryForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
        </el-form-item>
        <el-form-item label="联系电话" prop="phone">
          <el-input v-model="reservationRecordQueryForm.phone" placeholder="请输入联系电话" maxlength="20"></el-input>
        </el-form-item>
        <el-form-item label="状态" prop="status">
          <el-select v-model="reservationRecordQueryForm.status" placeholder="请选择状态" class="select-custom">
            <el-option label="已预定" :value="10"></el-option>
            <el-option label="已入驻" :value="20"></el-option>
            <el-option label="已取消" :value="30"></el-option>
          </el-select>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="onSearch">查询</el-button>
          <el-button @click="onReset">重置</el-button>
        </el-form-item>
      </el-form>

      <el-table
        :data="state.tableData"
        border
        v-loading="state.loading"
        size="small"
        header-cell-class-name="table-header-cell-font"
        cell-class-name="table-cell-font"
        @row-dblclick="reservationRecordSelected">
        <el-table-column prop="roomNumber" label="房号"></el-table-column>
        <el-table-column prop="name" label="姓名"></el-table-column>
        <el-table-column prop="phone" label="联系电话"></el-table-column>
        <el-table-column prop="checkInTime" label="预定入驻时间"></el-table-column>
        <el-table-column prop="remark" label="备注"></el-table-column>
        <el-table-column prop="status" label="状态">
          <template v-slot="{ row }">
            <div v-if="row.status === 10">已预定</div>
            <div v-if="row.status === 20">已入驻</div>
            <div v-if="row.status === 30">已取消</div>
          </template>
        </el-table-column>
      </el-table>
      <div class="table-pagination">
        <el-pagination
          @current-change="changePage"
          :current-page="state.currentPage"
          :page-sizes="state.pageSizes"
          :page-size="state.pageSize"
          background
          layout="total, prev, pager, next, jumper"
          :total="state.total">
        </el-pagination>
      </div>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog v-model="roomSelectorVisible" v-if="roomSelectorVisible" title="房间选择器(双击行选中)" :top="dialogTop" :width="dialogWidth">
      <room-selector @room-selected-event="handleRoomSelectedEvent">
      </room-selector>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { defineEmits, inject, onMounted, reactive, ref, toRefs } from 'vue'
import reservationRecordApi from '@/api/reservationRecordApi'
import type { ReservationRecordQueryForm } from '@/types/req/reservationRecordQueryForm'
import type { ReservationRecord } from '@/types/resp/reservationRecord'
import { type FormInstance } from 'element-plus'
import type { Result } from '@/types/result'
import type { Page } from '@/types/page'
import { Search } from '@element-plus/icons-vue'
import RoomSelector from '@/views/room/RoomSelector.vue'

const reservationRecordQueryFormRef = ref<FormInstance | null>(null);
const reservationRecordQueryForm = reactive<ReservationRecordQueryForm>({
  roomId: 0,
  roomNumber: '',
  name: '',
  phone: '',
  status: undefined,
})
const roomSelectorVisible = ref<boolean>(false)

const state = reactive({
  loading: false,
  tableData: [] as ReservationRecord[], // 数据列表
  total: 0, // 总条数
  currentPage: 1, // 当前页
  pageSize: 10, // 分页大小
  pageSizes: [10, 20, 50]
})

const dialogTop = ref<string>('')
const dialogWidth = ref<string>('')

const rules = reactive({
});

const emit = defineEmits<{
  (e: 'reservationRecordSelectedEvent', data?: {
    reservationRecordId: number,
    preName: string,
    prePhone: string,
    }): void;
}>()

onMounted(() => {
  onSearch()
  const globalState = inject('globalState', {} as { dialogWidth?: string, dialogTop?: string })
  if (!globalState) {
    throw new Error('globalState is not provided');
  }
  const globalStateRefs = toRefs(globalState)
  if (globalStateRefs.dialogWidth) {
    dialogWidth.value = globalStateRefs.dialogWidth.value || ''
  }
  if (globalStateRefs.dialogTop) {
    dialogTop.value = globalStateRefs.dialogTop.value || ''
  }
})

const getPageData = async () => {
  try {
    state.loading = true
    const resp: Result<Page<ReservationRecord>> = await reservationRecordApi.find(reservationRecordQueryForm)
    if (resp && resp.code === 1) {
      if (resp.data) {
        const page: Page<ReservationRecord> = resp.data
        if (page && page.list.length > 0) {
          state.tableData = page.list
          state.total = page.total
        }
      }
    }
  } catch (e) {
    console.log('获取数据异常', e)
  } finally {
    state.loading = false
  }
}
const onSearch = () => {
  getPageData()
}

const changePage = (val: number) => {
  state.currentPage = val
  getPageData()
}

const onReset = () => {
  if (reservationRecordQueryFormRef.value) {
    reservationRecordQueryFormRef.value.resetFields()
  }
  state.currentPage = 1
  getPageData()
}

const reservationRecordSelected = (row: ReservationRecord) => {
  emit('reservationRecordSelectedEvent', {
    reservationRecordId: row.id,
    preName: row.name,
    prePhone: row.phone,
  })
}

const findRoom = () => {
  roomSelectorVisible.value = true
}

const handleRoomSelectedEvent = (selectedRoom: any) => {
  roomSelectorVisible.value = false
  if (selectedRoom && 'roomId' in selectedRoom && reservationRecordQueryForm.roomId !== selectedRoom['roomId']) {
    reservationRecordQueryForm.roomId = selectedRoom['roomId']
    reservationRecordQueryForm.roomNumber = selectedRoom['roomNumber']
  }
}

const onBack = () => {
  emit('reservationRecordSelectedEvent')
}
</script>

<style lang="scss">
</style>
