// angular_ngzorro/src/app/check-in-record/check-in-record-add.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormControl, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {CheckInRecordService} from '../../service/check-in-record.service';
import {SharedModule} from '../shared.module';
import {CheckInRecordForm} from '../../types/req/CheckInRecordForm';
import {MODAL_WIDTH} from '../../const'
import {ReservationRecordSelectorComponent} from '../reservation-record/reservation-record-selector.component';
import {RoomSelectorComponent} from '../room/room-selector.component';

@Component({
  selector: 'check-in-record-add',
  imports: [
    ReservationRecordSelectorComponent,
    RoomSelectorComponent,
    SharedModule
  ],
  templateUrl: './check-in-record-add.component.html',
  standalone: true
})
export class CheckInRecordAddComponent implements OnInit {
  checkInRecordToSave:CheckInRecordForm = {};
  checkInRecordForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增入住记录'
  modalWidth: string = MODAL_WIDTH

  @ViewChild(ReservationRecordSelectorComponent, { static: false }) reservationRecordSelectorComponent!: ReservationRecordSelectorComponent;
  @ViewChild(RoomSelectorComponent, { static: false }) roomSelectorComponent!: RoomSelectorComponent;

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private checkInRecordService: CheckInRecordService
  ) {}

  ngOnInit(): void {
    this.checkInRecordForm = this.fb.group({
      reservationRecordId: [0],
      preName: [''],
      prePhone: [''],
      roomId: [0],
      roomNumber: ['', [Validators.required]],
      name: ['', [Validators.required]],
      phone: [''],
      checkInTime: ['', [Validators.required]],
      checkOutTime: [''],
      roomAmount: [0],
      goodsAmount: [0],
      amount: [0],
      remark: [''],
      status: [undefined],
    })

    const roomAmountControl = this.checkInRecordForm.get('roomAmount') as FormControl;
    const goodsAmountControl = this.checkInRecordForm.get('goodsAmount') as FormControl;

    roomAmountControl.valueChanges.subscribe(() => {
      this.calculateTotal();
    });

    goodsAmountControl.valueChanges.subscribe(() => {
      this.calculateTotal();
    });

    // 初始计算一次
    this.calculateTotal();
  }

  calculateTotal() {
    const roomAmount = this.checkInRecordForm.get('roomAmount')?.value || 0;
    const goodsAmount = this.checkInRecordForm.get('goodsAmount')?.value || 0;

    let amount = 0
    if (!isNaN(roomAmount) && !isNaN(goodsAmount)) {
      amount = roomAmount + goodsAmount;
    }
    this.checkInRecordForm.patchValue({amount: amount});
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.checkInRecordForm.controls) {
        this.checkInRecordForm.controls[i].markAsDirty();
        this.checkInRecordForm.controls[i].updateValueAndValidity();
      }
      if (!this.checkInRecordForm.valid) {
        this.saveLoading = false
        return
      }
      this.checkInRecordService.save(Object.assign(this.checkInRecordToSave, this.checkInRecordForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增入住记录'.slice()
    this.checkInRecordForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改入住记录'
      this.saveLoading = true
      this.checkInRecordService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.checkInRecordToSave = resp.data
            this.checkInRecordForm.patchValue(this.checkInRecordToSave);
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }

  findReservationRecord() {
    this.reservationRecordSelectorComponent.display()
  }

  handleReservationRecordSelectedEvent(selectedReservationRecord: { reservationRecordId?: number; preName?: string;prePhone?: string; }) {
    if (selectedReservationRecord && 'reservationRecordId' in selectedReservationRecord) {
      this.checkInRecordForm.patchValue(selectedReservationRecord);
    }
  }

  findRoom() {
    this.roomSelectorComponent.display()
  }

  handleRoomSelectedEvent(selectedRoom: { roomId?: number; roomNumber?: string; }) {
    if (selectedRoom && 'roomId' in selectedRoom) {
      this.checkInRecordForm.patchValue(selectedRoom);
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="checkInRecordForm" (keydown.enter)="$event.preventDefault()">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="preName">预定人员姓名</nz-form-label>
            <nz-form-control>
              <nz-input-group nzSearch [nzAddOnAfter]="preNameSuffixIconButton">
                <input nz-input formControlName="preName" placeholder="请选择预定人员姓名" readonly />
              </nz-input-group>
              <ng-template #preNameSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findReservationRecord()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="prePhone">预定人员联系电话</nz-form-label>
            <nz-form-control>
              <nz-input-group nzSearch [nzAddOnAfter]="prePhoneSuffixIconButton">
                <input nz-input formControlName="prePhone" placeholder="请选择预定人员联系电话" readonly />
              </nz-input-group>
              <ng-template #prePhoneSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findReservationRecord()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomNumber" nzRequired>房号</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择房号'">
              <nz-input-group nzSearch [nzAddOnAfter]="roomNumberSuffixIconButton">
                <input nz-input formControlName="roomNumber" placeholder="请选择房号" readonly />
              </nz-input-group>
              <ng-template #roomNumberSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findRoom()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name" nzRequired>姓名</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入姓名'">
              <input nz-input formControlName="name" placeholder="请输入姓名" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="phone">联系电话</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="phone" placeholder="请输入联系电话" maxlength="20"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="checkInTime">入驻时间</nz-form-label>
            <nz-form-control >
              <nz-date-picker nzShowTime formControlName="checkInTime" nzFormat="yyyy-MM-dd HH:mm:ss"></nz-date-picker>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="checkOutTime">退房时间</nz-form-label>
            <nz-form-control >
              <nz-date-picker nzShowTime formControlName="checkOutTime" nzFormat="yyyy-MM-dd HH:mm:ss"></nz-date-picker>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomAmount">房费</nz-form-label>
            <nz-form-control>
            <nz-input-number formControlName="roomAmount" [nzMin]="1" [nzMax]="999999" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="goodsAmount">商品消费</nz-form-label>
            <nz-form-control>
            <nz-input-number formControlName="goodsAmount" [nzMin]="1" [nzMax]="999999" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="amount">总金额</nz-form-label>
            <nz-form-control>
            <nz-input-number formControlName="amount" [nzMin]="1" [nzMax]="99999999" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="remark">备注</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="remark" placeholder="请输入备注" maxlength="255"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="status">状态</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="status">
                <nz-option nzLabel="已入驻" [nzValue]="20"></nz-option>
                <nz-option nzLabel="已取消" [nzValue]="30"></nz-option>
                <nz-option nzLabel="已退房" [nzValue]="40"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
<reservation-record-selector (reservationRecordSelectedEvent)="handleReservationRecordSelectedEvent($event)"></reservation-record-selector>
<room-selector (roomSelectedEvent)="handleRoomSelectedEvent($event)"></room-selector>

// v2_el/src/views/checkInRecord/CheckInRecordAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="checkInRecordForm" :label-width="formLabelWidth" ref="refCheckInRecordForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="预定人员姓名" prop="preName">
            <el-input v-model="checkInRecordForm.preName" placeholder="请选择预定人员姓名" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findReservationRecord"></i>
            </el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="预定人员联系电话" prop="prePhone">
            <el-input v-model="checkInRecordForm.prePhone" placeholder="请选择预定人员联系电话" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findReservationRecord"></i>
            </el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="房号" prop="roomNumber">
            <el-input v-model="checkInRecordForm.roomNumber" placeholder="请选择房号" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findRoom"></i>
            </el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="姓名" prop="name">
            <el-input v-model="checkInRecordForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="联系电话" prop="phone">
            <el-input v-model="checkInRecordForm.phone" placeholder="请输入联系电话" maxlength="20"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="入驻时间" prop="checkInTime">
            <el-date-picker
                v-model="checkInRecordForm.checkInTime" type="datetime" placeholder="入驻时间" value-format="yyyy-MM-dd HH:mm:ss">
            </el-date-picker>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="退房时间" prop="checkOutTime">
            <el-date-picker
                v-model="checkInRecordForm.checkOutTime" type="datetime" placeholder="退房时间" value-format="yyyy-MM-dd HH:mm:ss">
            </el-date-picker>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="房费" prop="roomAmount">
            <el-input-number v-model="checkInRecordForm.roomAmount" :min="1" :max="9999999" @change="calculateAmount"></el-input-number>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="商品消费" prop="goodsAmount">
            <el-input-number v-model="checkInRecordForm.goodsAmount" :min="1" :max="9999999" @change="calculateAmount"></el-input-number>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="总金额" prop="amount">
            <el-input v-model="checkInRecordForm.amount" :disabled="true"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="remark" prop="remark">
            <el-input v-model="checkInRecordForm.remark" placeholder="请输入remark" maxlength="255"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="状态" prop="status">
            <el-select v-model="checkInRecordForm.status" placeholder="请选择状态">
              <el-option label="已入驻" :value="20"></el-option>
              <el-option label="已取消" :value="30"></el-option>
              <el-option label="已退房" :value="40"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button type="primary" @click="onReset" plain>重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="reservationRecordSelectorVisible" v-if="reservationRecordSelectorVisible" title="预定记录选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <reservation-record-selector @reservation-record-selected-event="handleReservationRecordSelectedEvent">
      </reservation-record-selector>
    </el-dialog>
    <el-dialog :visible.sync="roomSelectorVisible" v-if="roomSelectorVisible" title="房间选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <room-selector @room-selected-event="handleRoomSelectedEvent">
      </room-selector>
    </el-dialog>
  </div>
</template>

<script>
import checkInRecordApi from '@/api/checkInRecordApi'
import ReservationRecordSelector from "@/views/reservationRecord/ReservationRecordSelector.vue";
import RoomSelector from "@/views/room/RoomSelector.vue";
export default {
  name: 'CheckInRecordAdd',
  components: {ReservationRecordSelector,RoomSelector,},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      checkInRecordForm: {
        reservationRecordId: '',
        preName: '',
        prePhone: '',
        roomId: '',
        roomNumber: '',
        name: '',
        phone: '',
        checkInTime: '',
        checkOutTime: '',
        roomAmount: '',
        goodsAmount: '',
        amount: '',
        remark: '',
        status: ''
      },
      rules: {
        roomNumber:[
          { required: true, message: '请输入房号', trigger: 'blur' }
        ],
        name:[
          { required: true, message: '请输入姓名', trigger: 'blur' }
        ],
      },
      reservationRecordSelectorVisible: false,
      roomSelectorVisible: false,
    }
  },
  created () {
    if (this.id) {
      checkInRecordApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.checkInRecordForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  mounted() {
    this.calculateAmount()
  },
  methods: {
    onReset () {
      this.checkInRecordForm = {
        reservationRecordId: '',
        preName: '',
        prePhone: '',
        roomId: '',
        roomNumber: '',
        name: '',
        phone: '',
        checkInTime: '',
        checkOutTime: '',
        roomAmount: '',
        goodsAmount: '',
        amount: '',
        remark: '',
        status: ''
      }
      this.$emit('reset-check-in-record-add-event')
    },
    onSave () {
      this.$refs.refCheckInRecordForm.validate((valid) => {
        if (valid) {
          checkInRecordApi.save(this.checkInRecordForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-check-in-record-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    findReservationRecord () {
      this.reservationRecordSelectorVisible = true
    },
    handleReservationRecordSelectedEvent (selectedReservationRecord) {
      this.reservationRecordSelectorVisible = false
      if (selectedReservationRecord && 'reservationRecordId' in selectedReservationRecord && this.checkInRecordForm.reservationRecordId !== selectedReservationRecord['reservationRecordId']) {
        this.checkInRecordForm.reservationRecordId = selectedReservationRecord['reservationRecordId']
        this.checkInRecordForm.preName = selectedReservationRecord['preName']
        this.checkInRecordForm.prePhone = selectedReservationRecord['prePhone']
      }
    },
    findRoom () {
      this.roomSelectorVisible = true
    },
    handleRoomSelectedEvent (selectedRoom) {
      this.roomSelectorVisible = false
      if (selectedRoom && 'roomId' in selectedRoom && this.checkInRecordForm.roomId !== selectedRoom['roomId']) {
        this.checkInRecordForm.roomId = selectedRoom['roomId']
        this.checkInRecordForm.roomNumber = selectedRoom['roomNumber']
      }
    },
    onBack () {
      this.$emit('close-check-in-record-add-event')
    },
    calculateAmount() {
      this.checkInRecordForm.amount = this.checkInRecordForm.roomAmount + this.checkInRecordForm.goodsAmount
    }
  }
}
</script>

<style lang="scss">
</style>
