// v2_el/src/views/checkInRecord/CheckInRecordSelector.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
      <el-form :inline="true" :model="searchParams">
        <el-form-item label="房号" prop="roomNumber">
          <el-input v-model="searchParams.roomNumber" placeholder="请选择房号" readonly="readonly">
            <i slot="suffix" class="el-input__icon el-icon-search" @click="findRoom"></i>
          </el-input>
        </el-form-item>
        <el-form-item label="姓名">
            <el-input v-model="searchParams.name" placeholder="请输入姓名" maxlength="64"></el-input>
        </el-form-item>
        <el-form-item label="联系电话">
            <el-input v-model="searchParams.phone" placeholder="请输入联系电话" maxlength="20"></el-input>
        </el-form-item>
        <el-form-item label="状态" prop="status">
          <el-select v-model="searchParams.status" placeholder="请选择状态">
            <el-option label="已入驻" :value="20"></el-option>
            <el-option label="已取消" :value="30"></el-option>
            <el-option label="已退房" :value="40"></el-option>
          </el-select>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="onSearch">查询</el-button>
          <el-button @click="onReset">重置</el-button>
        </el-form-item>
      </el-form>

      <el-table
        :data="pageData.list"
        border
        v-loading="pageData.loading"
        size="mini"
        header-cell-class-name="table-header-cell-font"
        cell-class-name="table-cell-font"
        @row-dblclick="checkInRecordSelected">
      <el-table-column prop="reservationRecordId" label="预定记录id"></el-table-column>
      <el-table-column prop="roomId" label="房间id"></el-table-column>
      <el-table-column prop="name" label="姓名"></el-table-column>
      <el-table-column prop="phone" label="联系电话"></el-table-column>
      <el-table-column prop="checkInTime" label="入驻时间"></el-table-column>
      <el-table-column prop="checkOutTime" label="退房时间"></el-table-column>
      <el-table-column prop="roomAmount" label="房费"></el-table-column>
      <el-table-column prop="goodsAmount" label="商品消费"></el-table-column>
      <el-table-column prop="amount" label="总金额"></el-table-column>
      <el-table-column prop="remark" label="remark"></el-table-column>
      <el-table-column prop="status" label="状态">
        <template v-slot="{ row }">
          <div v-if="row.status === 20">已入驻</div>
          <div v-if="row.status === 30">已取消</div>
          <div v-if="row.status === 40">已退房</div>
        </template>
      </el-table-column>
      </el-table>
      <div class="table-pagination">
        <el-pagination
          @current-change="paginationChange"
          :current-page="pageData.current"
          :page-sizes="pageData.pageSizes"
          :page-size="pageData.size"
          background
          layout="total, prev, pager, next, jumper"
          :total="pageData.count">
        </el-pagination>
      </div>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="roomSelectorVisible" v-if="roomSelectorVisible" title="房间选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <room-selector @room-selected-event="handleRoomSelectedEvent">
      </room-selector>
    </el-dialog>
  </div>
</template>

<script>
import checkInRecordApi from '@/api/checkInRecordApi'
import RoomSelector from "@/views/room/RoomSelector.vue";
import listQueryMixin from '@/mixins/listQueryMixin'
export default {
  name: 'CheckInRecordSelector',
  components: {RoomSelector,},
  mixins: [
    listQueryMixin
  ],
  data () {
    return {
      searchParams: {
        roomId: '',
        roomNumber: '',
        name: '',
        phone: '',
        status: ''
      },
      roomSelectorVisible: false,
    }
  },
  methods: {
    getPageData (p) {
      return checkInRecordApi.find(p)
    },
    onSearch () {
      this._getPageData()
    },
    onReset () {
      this.searchParams = {
        roomId: '',
        roomNumber: '',
        name: '',
        phone: '',
        status: ''
      }
      this.pageData.pageIndex = 1
      this._getPageData()
    },
    checkInRecordSelected (row) {
      this.$emit('check-in-record-selected-event', {
        checkInRecordId: row.id,
        name: row.name,
        phone: row.phone,
      })
    },
    findRoom () {
      this.roomSelectorVisible = true
    },
    handleRoomSelectedEvent (selectedRoom) {
      this.roomSelectorVisible = false
      if (selectedRoom && 'roomId' in selectedRoom && this.searchParams.roomId !== selectedRoom['roomId']) {
        this.searchParams.roomId = selectedRoom['roomId']
        this.searchParams.roomNumber = selectedRoom['roomNumber']
      }
    },
    onBack () {
      this.$emit('check-in-record-selected-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// react_antd/src/pages/checkInRecord/CheckInRecordSelector.tsx
import React, {useEffect, useState} from 'react';
import {Button, Form, Input, Modal, Select, Table, TableProps} from 'antd';
import type {CheckInRecord} from "@/types/resp/checkInRecord";
import checkInRecordApi from '@/api/checkInRecordApi'
import {Result} from "@/types/result";
import {Page} from "@/types/page";
import ReservationRecordSelector from "@/pages/reservationRecord/ReservationRecordSelector.tsx";
import RoomSelector from "@/pages/room/RoomSelector.tsx";


interface CheckInRecordSelectorProps {
  visible: boolean;
  onCheckInRecordSelected: (selectedCheckInRecord: { checkInRecordId?: number; name?: string; phone?: string; }) => void;
  onCloseCheckInRecordSelector: () => void;
}

const CheckInRecordSelector: React.FC<CheckInRecordSelectorProps> = ({visible, onCheckInRecordSelected, onCloseCheckInRecordSelector}) => {

  const [checkInRecordSelectorForm] = Form.useForm();

  const onFinish = async () => {
    await onSearch()
  };

  const onReset = () => {
    checkInRecordSelectorForm.resetFields();
  };

  const [data, setData] = useState<CheckInRecord[]>([]);
  const onSearch = async () => {
    try {
      const resp: Result<Page<CheckInRecord>> = await checkInRecordApi.find(checkInRecordSelectorForm.getFieldsValue())
      if (resp && resp.code === 1) {
        if (resp.data) {
          const page: Page<CheckInRecord> = resp.data
          if (page && page.list.length > 0) {
            setData(page.list)
          }
        }
      }
    } catch (e) {
      console.log('获取数据异常', e)
    }
  };

  const columns: TableProps<CheckInRecord>['columns'] = [
    {title: '预定人员姓名', dataIndex: 'preName', key: 'preName'},
    {title: '预定人员联系电话', dataIndex: 'prePhone', key: 'prePhone'},
    {title: '房号', dataIndex: 'roomNumber', key: 'roomNumber'},
    {title: '姓名', dataIndex: 'name', key: 'name'},
    {title: '联系电话', dataIndex: 'phone', key: 'phone'},
    {title: '入驻时间', key: 'checkInTime', render: (_, record) => (
      <div>{record.checkInTime.format('YYYY-MM-DD HH:mm:ss')}</div>
    )},
    {title: '退房时间', key: 'checkOutTime', render: (_, record) => (
      <div>{record.checkOutTime.format('YYYY-MM-DD HH:mm:ss')}</div>
    )},
    {title: '房费', dataIndex: 'roomAmount', key: 'roomAmount'},
    {title: '商品消费', dataIndex: 'goodsAmount', key: 'goodsAmount'},
    {title: '总金额', dataIndex: 'amount', key: 'amount'},
    {title: 'remark', dataIndex: 'remark', key: 'remark'},
    {title: '状态', key: 'status', render: (_, record) => (
        <span>
        {(function () {
          if (record.status === 20) return '已入驻';
          else if (record.status === 30) return '已取消';
          else if (record.status === 40) return '已退房';
          else return '未知';
        })()}
      </span>
      ),
    },
  ];

  const handleRowDoubleClick = (row: CheckInRecord) => {
    onCheckInRecordSelected({
      checkInRecordId: row.id,
      name: row.name,
      phone: row.phone,
    })
  };

  const selectorFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onCloseCheckInRecordSelector}>关闭</Button>
    </div>
  );

  useEffect(() => {
    if (visible) {
      onSearch();
    }
  }, [visible]);

  const [reservationRecordSelectorVisible, setReservationRecordSelectorVisible] = useState(false);
  const findReservationRecord = () => {
    setReservationRecordSelectorVisible(true);
  }
  const handleReservationRecordSelected = (selectedReservationRecord: { reservationRecordId?: number; preName?: string; prePhone?: string; }) => {
    setReservationRecordSelectorVisible(false)
    if (selectedReservationRecord && 'reservationRecordId' in selectedReservationRecord) {
      checkInRecordSelectorForm.setFieldsValue(Object.assign(checkInRecordSelectorForm.getFieldsValue(), {
      reservationRecordId: selectedReservationRecord['reservationRecordId'],
      preName: selectedReservationRecord['preName'],
      prePhone: selectedReservationRecord['prePhone'],
      }));
    }
  };
  const handleCloseReservationRecordSelector = () => {
    setReservationRecordSelectorVisible(false)
  };
  const [roomSelectorVisible, setRoomSelectorVisible] = useState(false);
  const findRoom = () => {
    setRoomSelectorVisible(true);
  }
  const handleRoomSelected = (selectedRoom: { roomId?: number; roomNumber?: string; }) => {
    setRoomSelectorVisible(false)
    if (selectedRoom && 'roomId' in selectedRoom) {
      checkInRecordSelectorForm.setFieldsValue(Object.assign(checkInRecordSelectorForm.getFieldsValue(), {
      roomId: selectedRoom['roomId'],
      roomNumber: selectedRoom['roomNumber'],
      }));
    }
  };
  const handleCloseRoomSelector = () => {
    setRoomSelectorVisible(false)
  };

  return (
    <Modal title={"入住记录选择器(双击行选中)"} open={visible} onCancel={onCloseCheckInRecordSelector}
        width={'var(--modal-width)'} footer={selectorFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={checkInRecordSelectorForm} onFinish={onFinish} layout={"inline"}>
        <Form.Item name="preName" label="预定人员姓名">
          <Input.Search placeholder="请选择预定人员姓名" onSearch={findReservationRecord} readOnly={true} />
        </Form.Item>
        <Form.Item name="prePhone" label="预定人员联系电话">
          <Input.Search placeholder="请选择预定人员联系电话" onSearch={findReservationRecord} readOnly={true} />
        </Form.Item>
        <Form.Item name="roomNumber" label="房号">
          <Input.Search placeholder="请选择房号" onSearch={findRoom} readOnly={true} />
        </Form.Item>
        <Form.Item name="name" label="姓名">
          <Input maxLength={64} placeholder="请输入姓名"/>
        </Form.Item>
        <Form.Item name="phone" label="联系电话">
          <Input maxLength={20} placeholder="请输入联系电话"/>
        </Form.Item>
        <Form.Item name="status" label="状态">
          <Select placeholder="请选择状态" options={[
            { value: 20, label: <span>已入驻</span> },
            { value: 30, label: <span>已取消</span> },
            { value: 40, label: <span>已退房</span> }
          ]} style={{width: 'var(--select-width)'}} />
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" htmlType="submit">查询</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button onClick={onReset}>重置</Button>
        </Form.Item>
      </Form>
      <Table<CheckInRecord> columns={columns} dataSource={data} size="small" rowKey={record => record.id}
                         pagination={{ position: ["bottomCenter"] }}
                         onRow={(row) => ({
                           onDoubleClick: (event) => {
                             event.preventDefault();
                             handleRowDoubleClick(row);
                           },
                         })}/>
      <ReservationRecordSelector visible={reservationRecordSelectorVisible} onReservationRecordSelected={handleReservationRecordSelected} onCloseReservationRecordSelector={handleCloseReservationRecordSelector} />
      <RoomSelector visible={roomSelectorVisible} onRoomSelected={handleRoomSelected} onCloseRoomSelector={handleCloseRoomSelector} />
    </Modal>
  );
};

export default CheckInRecordSelector;
