// angular_ngzorro/src/app/check-in-record/check-in-record-view.component.ts
import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {SharedModule} from '../shared.module';
import {MODAL_WIDTH} from '../../const'
import {CheckInRecord} from '../../types/resp/CheckInRecord';

@Component({
  selector: 'check-in-record-view',
  imports: [
    SharedModule
  ],
  templateUrl: './check-in-record-view.component.html',
  standalone: true
})
export class CheckInRecordViewComponent implements OnInit {
  checkInRecordForm!: FormGroup;
  isVisible: boolean = false
  title: string = '入住记录详情'
  modalWidth: string = MODAL_WIDTH

  constructor(
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.checkInRecordForm = this.fb.group({
      preName: [''],
      prePhone: [''],
      roomNumber: [''],
      name: [''],
      phone: [''],
      checkInTime: [''],
      checkOutTime: [''],
      roomAmount: [0],
      goodsAmount: [0],
      amount: [0],
      remark: [''],
      status: [undefined],
      createTime: [''],
      modifyTime: [''],
    })
  }

  onBack() {
    this.isVisible = false
  }

  display(checkInRecord: CheckInRecord) {
    this.isVisible = true
    this.checkInRecordForm.patchValue(checkInRecord);
    this.checkInRecordForm.disable();
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="checkInRecordForm">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="preName">预定人员姓名</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="preName" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="prePhone">预定人员联系电话</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="prePhone" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomNumber">房号</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="roomNumber" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name">姓名</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="name" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="phone">联系电话</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="phone" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="checkInTime">入驻时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="checkInTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="checkOutTime">退房时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="checkOutTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomAmount">房费</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="roomAmount" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="goodsAmount">商品消费</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="goodsAmount" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="amount">总金额</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="amount" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="remark">备注</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="remark" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="status">状态</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="status">
                <nz-option nzLabel="已入驻" [nzValue]="20"></nz-option>
                <nz-option nzLabel="已取消" [nzValue]="30"></nz-option>
                <nz-option nzLabel="已退房" [nzValue]="40"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="createTime">创建时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="createTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="modifyTime">最后修改时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="modifyTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>

// react_antd/src/pages/checkInRecord/CheckInRecordView.tsx
import React, {useEffect} from "react";
import {Button, Col, DatePicker, Form, Input, Modal, Row, Select} from "antd";
import {CheckInRecord} from "@/types/resp/checkInRecord";

interface CheckInRecordViewProps {
  visible: boolean;
  viewRow: object;
  onCloseCheckInRecordView: () => void;
}

const CheckInRecordView: React.FC<CheckInRecordViewProps> = ({visible, viewRow, onCloseCheckInRecordView}) => {

  const [form] = Form.useForm<CheckInRecord>();

  const onBack = () => {
    onCloseCheckInRecordView()
  };

  useEffect(() => {
    if (!visible) {
      return
    }
    if (viewRow) {
      form.setFieldsValue(viewRow);
    }
  }, [viewRow]);

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onBack}>关闭</Button>
    </div>
  );

  return (
    <Modal title={"入住记录详情"} open={visible} onCancel={onCloseCheckInRecordView}
        width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={form} labelCol={{span: 6}} disabled={true}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="preName" label="预定人员姓名">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="prePhone" label="预定人员联系电话">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="roomNumber" label="房号">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="name" label="姓名">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="phone" label="联系电话">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="checkInTime" label="入驻时间">
              <DatePicker showTime={true}/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="checkOutTime" label="退房时间">
              <DatePicker showTime={true}/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="roomAmount" label="房费">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="goodsAmount" label="商品消费">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="amount" label="总金额">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="remark" label="remark">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="status" label="状态">
              <Select placeholder="请选择状态" options={[
                { value: 20, label: <span>已入驻</span> },
                { value: 30, label: <span>已取消</span> },
                { value: 40, label: <span>已退房</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="createTime" label="创建时间">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="modifyTime" label="最后修改时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default CheckInRecordView;
