// v3_el/src/views/checkInRecord/CheckInRecordList.vue
<template>
  <div class="checkInRecord-list">
    <div class="breadcrumb">
      <el-breadcrumb separator="/">
        <el-breadcrumb-item to="Home" :replace="true">首页</el-breadcrumb-item>
        <el-breadcrumb-item>入住记录列表</el-breadcrumb-item>
      </el-breadcrumb>
    </div>
    <el-form :inline="true" :model="checkInRecordQueryForm" ref="checkInRecordQueryFormRef" :rules="rules">
      <el-form-item label="房号" prop="roomNumber">
        <el-input v-model="checkInRecordQueryForm.roomNumber" placeholder="请选择房号" readonly="readonly">
          <template #suffix>
            <el-icon @click="findRoom"><Search/></el-icon>
          </template>
        </el-input>
      </el-form-item>
      <el-form-item label="姓名" prop="name">
        <el-input v-model="checkInRecordQueryForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
      </el-form-item>
      <el-form-item label="联系电话" prop="phone">
        <el-input v-model="checkInRecordQueryForm.phone" placeholder="请输入联系电话" maxlength="20"></el-input>
      </el-form-item>
      <el-form-item label="状态" prop="status">
        <el-select v-model="checkInRecordQueryForm.status" placeholder="请选择状态" class="select-custom">
          <el-option label="已入驻" :value="20"></el-option>
          <el-option label="已取消" :value="30"></el-option>
          <el-option label="已退房" :value="40"></el-option>
        </el-select>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="onSearch">查询</el-button>
        <el-button @click="onReset">重置</el-button>
        <el-button type="primary" @click="onAdd">新增</el-button>
        <el-button type="primary" @click="onExport">导出</el-button>
      </el-form-item>
    </el-form>

    <el-table
      :data="state.tableData"
      border
      v-loading="state.loading"
      size="small"
      header-cell-class-name="table-header-cell-font"
      cell-class-name="table-cell-font">
      <el-table-column prop="preName" label="预定人员姓名" width="100"></el-table-column>
      <el-table-column prop="prePhone" label="预定人员联系电话" width="140"></el-table-column>
      <el-table-column prop="roomNumber" label="房号" width="100"></el-table-column>
      <el-table-column prop="name" label="姓名" width="100"></el-table-column>
      <el-table-column prop="phone" label="联系电话" width="100"></el-table-column>
      <el-table-column prop="checkInTime" label="入驻时间" width="140"></el-table-column>
      <el-table-column prop="checkOutTime" label="退房时间" width="140"></el-table-column>
      <el-table-column prop="roomAmount" label="房费" width="100"></el-table-column>
      <el-table-column prop="goodsAmount" label="商品消费" width="100"></el-table-column>
      <el-table-column prop="amount" label="总金额" width="100"></el-table-column>
      <el-table-column prop="remark" label="备注" width="100"></el-table-column>
      <el-table-column prop="status" label="状态" width="100">
        <template v-slot="{ row }">
          <div v-if="row.status === 20">已入驻</div>
          <div v-if="row.status === 30">已取消</div>
          <div v-if="row.status === 40">已退房</div>
        </template>
      </el-table-column>
      <el-table-column fixed="right" label="操作" width="250">
        <template v-slot="{ row }">
          <el-button @click.prevent="editRow(row.id)" type="primary">编辑</el-button>
          <el-button @click.prevent="delRow(row.id)" type="danger" plain>删除</el-button>
          <el-button @click.prevent="detailRow(row.id)" type="primary" plain>详情</el-button>
        </template>
      </el-table-column>
    </el-table>
    <div class="table-pagination">
      <el-pagination
        @current-change="changePage"
        :current-page="state.currentPage"
        :page-sizes="state.pageSizes"
        :page-size="state.pageSize"
        background
        layout="total, prev, pager, next, jumper"
        :total="state.total">
      </el-pagination>
    </div>
    <el-dialog v-model="roomSelectorVisible" v-if="roomSelectorVisible" title="房间选择器(双击行选中)" :top="dialogTop" :width="dialogWidth">
      <room-selector @room-selected-event="handleRoomSelectedEvent">
      </room-selector>
    </el-dialog>
    <el-dialog v-model="checkInRecordAddVisible" v-if="checkInRecordAddVisible" :title="checkInRecordAddTitle" :top="dialogTop" :width="dialogWidth">
      <check-in-record-add :id="selectedCheckInRecordId" @close-check-in-record-add-event="handleCloseCheckInRecordAddEvent" @reset-check-in-record-add-event="handleResetCheckInRecordAddEvent">
      </check-in-record-add>
    </el-dialog>
    <el-dialog v-model="checkInRecordViewVisible" v-if="checkInRecordViewVisible" title="入住记录详情" :top="dialogTop" :width="dialogWidth">
      <check-in-record-view :id="selectedCheckInRecordId" @close-check-in-record-view-event="handleCloseCheckInRecordViewEvent">
      </check-in-record-view>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { inject, onMounted, reactive, ref, toRefs } from 'vue'
import checkInRecordApi from '@/api/checkInRecordApi'
import type { CheckInRecordQueryForm } from '@/types/req/checkInRecordQueryForm'
import type { CheckInRecord } from '@/types/resp/checkInRecord'
import { ElMessage, ElMessageBox, type FormInstance } from 'element-plus'
import type { Result } from '@/types/result'
import type { Page } from '@/types/page'
import { Search } from '@element-plus/icons-vue'
import RoomSelector from '@/views/room/RoomSelector.vue'
import CheckInRecordAdd from '@/views/checkInRecord/CheckInRecordAdd.vue'
import CheckInRecordView from '@/views/checkInRecord/CheckInRecordView.vue'
import { exportToExcel } from '@/composables/exportUtil.ts'
import { getCheckInRecordStatusText } from '@/composables/dictTranslator.ts'

const checkInRecordQueryFormRef = ref<FormInstance | null>(null);
const checkInRecordQueryForm = reactive<CheckInRecordQueryForm>({
  roomId: 0,
  roomNumber: '',
  name: '',
  phone: '',
  status: undefined,
})

const state = reactive({
  loading: false,
  tableData: [] as CheckInRecord[], // 数据列表
  total: 0, // 总条数
  currentPage: 1, // 当前页
  pageSize: 10, // 分页大小
  pageSizes: [10, 20, 50]
})
const selectedCheckInRecordId = ref<number>(0)
const roomSelectorVisible = ref<boolean>(false)
const checkInRecordAddVisible = ref<boolean>(false)
const checkInRecordViewVisible = ref<boolean>(false)
const checkInRecordAddTitle = ref<string>('')
const dialogTop = ref<string>('')
const dialogWidth = ref<string>('')

const rules = reactive({
});

onMounted(() => {
  onSearch()
  const globalState = inject('globalState', {} as { dialogWidth?: string, dialogTop?: string })
  if (!globalState) {
    throw new Error('globalState is not provided');
  }
  const globalStateRefs = toRefs(globalState)
  if (globalStateRefs.dialogWidth) {
    dialogWidth.value = globalStateRefs.dialogWidth.value || ''
  }
  if (globalStateRefs.dialogTop) {
    dialogTop.value = globalStateRefs.dialogTop.value || ''
  }
})

const getPageData = async () => {
  try {
    state.loading = true
    const resp: Result<Page<CheckInRecord>> = await checkInRecordApi.find(checkInRecordQueryForm)
    if (resp && resp.code === 1) {
      if (resp.data) {
      const page: Page<CheckInRecord> = resp.data
        if (page && page.list.length > 0) {
          state.tableData = page.list
          state.total = page.total
        }
      }
    }
  } catch (e) {
    console.log('获取数据异常', e)
  } finally {
    state.loading = false
  }
}
const onSearch = () => {
  getPageData()
}

const changePage = (val: number) => {
  state.currentPage = val
  getPageData()
}

const onReset = () => {
  if (checkInRecordQueryFormRef.value) {
    checkInRecordQueryFormRef.value.resetFields()
  }
  state.currentPage = 1
  getPageData()
}

const onAdd = () => {
  selectedCheckInRecordId.value = 0
  checkInRecordAddVisible.value = true
  checkInRecordAddTitle.value = '入住记录新增'
}
const editRow = (id: number) => {
  selectedCheckInRecordId.value = id
  checkInRecordAddVisible.value = true
  checkInRecordAddTitle.value = '入住记录编辑'
}
const delRow = (id: number) => {
  if (!id) {
    return
  }
  ElMessageBox.confirm(
    '确定要删除吗?',
    '删除提示',
    {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning',
    }
  ).then(() => {
    checkInRecordApi.del(id)
      .then((resp) => {
        if (resp && resp.code === 1) {
          ElMessage.success('删除成功!')
          onSearch()
        } else {
          ElMessage.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
        }
      })
      .catch(error => {
        console.error('操作失败:', error)
      })
  }).catch(() => {})
}
const detailRow = (id:number) => {
  selectedCheckInRecordId.value = id
  checkInRecordViewVisible.value = true
}

const findRoom = () => {
  roomSelectorVisible.value = true
}

const handleRoomSelectedEvent = (selectedRoom: any) => {
  roomSelectorVisible.value = false
  if (selectedRoom && 'roomId' in selectedRoom && checkInRecordQueryForm.roomId !== selectedRoom['roomId']) {
    checkInRecordQueryForm.roomId = selectedRoom['roomId']
    checkInRecordQueryForm.roomNumber = selectedRoom['roomNumber']
  }
}

const handleCloseCheckInRecordViewEvent = () => {
  checkInRecordViewVisible.value = false
}

const handleResetCheckInRecordAddEvent = () => {
  checkInRecordAddTitle.value = '入住记录新增'
}

const handleCloseCheckInRecordAddEvent = (params: { search?: boolean } | undefined) => {
  if (params && params.search) {
    onSearch()
  }
  checkInRecordAddVisible.value = false
}

const onExport = () => {
  const headers = ['预定人员姓名', '预定人员联系电话', '房号', '姓名', '联系电话', '入驻时间', '退房时间', '房费', '商品消费', '总金额', '备注', '状态']
  checkInRecordApi.find(checkInRecordQueryForm).then(data => {
    if (!data || !data.data || data.data.list.length < 1) {
      ElMessage.error('无数据导出')
      return
    }
    const exportData = []
    for (const d of data.data.list) {
      exportData.push([d.preName, d.prePhone, d.roomNumber, d.name, d.phone, d.checkInTime,
        d.checkOutTime, d.roomAmount, d.goodsAmount, d.amount, d.remark, getCheckInRecordStatusText(d.status)])
    }
    exportToExcel(headers, exportData)
  })
}
</script>

<style lang="scss">
</style>

// react_antd/src/pages/checkInRecord/CheckInRecordList.tsx
import React, {useCallback, useEffect, useState} from 'react';
import {Breadcrumb, Button, Form, Input, message, Modal, Select, Space, Table, TableProps} from 'antd';
import {useNavigate} from "react-router-dom";
import type {CheckInRecord} from "@/types/resp/checkInRecord";
import checkInRecordApi from '@/api/checkInRecordApi'
import {Result} from "@/types/result";
import {Page} from "@/types/page";
import CheckInRecordAdd from "@/pages/checkInRecord/CheckInRecordAdd.tsx";
import CheckInRecordView from "@/pages/checkInRecord/CheckInRecordView.tsx";
import ReservationRecordSelector from "@/pages/reservationRecord/ReservationRecordSelector.tsx";
import RoomSelector from "@/pages/room/RoomSelector.tsx";
import {exportToExcel} from "@/utils/exportUtil.ts";
import {getCheckInRecordStatusText} from "@/utils/dictTranslator.ts";


const CheckInRecordList: React.FC = () => {

  const navigate = useNavigate();
  const [messageApi, messageContextHolder] = message.useMessage();
  const [modal, modalContextHolder] = Modal.useModal();

  const handleClick = (path: string) => {
    navigate(path);
  };

  const breadcrumbsItems = [
    {title: '首页', className: 'breadcrumbHome', onClick: () => handleClick('/Home')},
    {title: '入住记录列表'}
  ]

  const [form] = Form.useForm();

  const onFinish = async () => {
    await onSearch()
  };

  const onReset = () => {
    form.resetFields();
  };

  const [data, setData] = useState<CheckInRecord[]>([]);
  const onSearch = async () => {
    try {
      const resp: Result<Page<CheckInRecord>> = await checkInRecordApi.find(form.getFieldsValue())
      if (resp && resp.code === 1) {
        if (resp.data) {
          const page: Page<CheckInRecord> = resp.data
          if (page && page.list.length > 0) {
            setData(page.list)
          }
        }
      }
    } catch (e) {
      console.log('获取数据异常', e)
    }
  };

  const columns: TableProps<CheckInRecord>['columns'] = [
    {title: '预定人员姓名', dataIndex: 'preName', key: 'preName'},
    {title: '预定人员联系电话', dataIndex: 'prePhone', key: 'prePhone'},
    {title: '房号', dataIndex: 'roomNumber', key: 'roomNumber'},
    {title: '姓名', dataIndex: 'name', key: 'name'},
    {title: '联系电话', dataIndex: 'phone', key: 'phone'},
    {title: '入驻时间', key: 'checkInTime', render: (_, record) => (
      <div>{record.checkInTime.format('YYYY-MM-DD HH:mm:ss')}</div>
    )},
    {title: '退房时间', key: 'checkOutTime', render: (_, record) => (
      <div>{record.checkOutTime.format('YYYY-MM-DD HH:mm:ss')}</div>
    )},
    {title: '房费', dataIndex: 'roomAmount', key: 'roomAmount'},
    {title: '商品消费', dataIndex: 'goodsAmount', key: 'goodsAmount'},
    {title: '总金额', dataIndex: 'amount', key: 'amount'},
    {title: 'remark', dataIndex: 'remark', key: 'remark'},
    {title: '状态', key: 'status', render: (_, record) => (
        <span>
        {(function () {
          if (record.status === 20) return '已入驻';
          else if (record.status === 30) return '已取消';
          else if (record.status === 40) return '已退房';
          else return '未知';
        })()}
      </span>
      ),
    },
    {
      title: '操作',
      key: 'action',
      width: '250px',
      render: (_, record) => (
        <Space size="middle">
          <Button type="primary" onClick={() => editRow(record.id)}>编辑</Button>
          <Button danger onClick={() => delRow(record.id)}>删除</Button>
          <Button color="primary" variant="outlined" onClick={() => detailRow(record)}>详情</Button>
        </Space>
      ),
    },
  ];

  const [checkInRecordAddVisible, setCheckInRecordAddVisible] = useState(false);
  const [checkInRecordViewVisible, setCheckInRecordViewVisible] = useState(false);
  const [selectedCheckInRecordId, setSelectedCheckInRecordId] = useState(0)
  const [selectedCheckInRecord, setSelectedCheckInRecord] = useState({})

  const onAdd = () => {
    setSelectedCheckInRecordId(0)
    setCheckInRecordAddVisible(true)
  };

  const editRow = (id: number) => {
    setSelectedCheckInRecordId(id)
    setCheckInRecordAddVisible(true)
  };

  const delRow = useCallback(async (id: number) => {
    const confirmed = await modal.confirm({
      title: '删除提示',
      content: (
        <>
          确定要删除吗?
        </>
      ),
      okText: '确定',
      cancelText: '取消',
      type: 'warning'
    });

    if (confirmed) {
      checkInRecordApi.del(id)
        .then((resp) => {
          if (resp && resp.code === 1) {
            messageApi.success('删除成功!')
            onSearch()
          } else {
            messageApi.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
          }
        })
        .catch(error => {
          console.error('操作失败:', error)
        })
    }
  }, [modal]);

  const detailRow = (record: CheckInRecord) => {
    setSelectedCheckInRecord(record)
    setCheckInRecordViewVisible(true)
  };

  const [reservationRecordSelectorVisible, setReservationRecordSelectorVisible] = useState(false);
  const findReservationRecord = () => {
    setReservationRecordSelectorVisible(true);
  }
  const handleReservationRecordSelected = (selectedReservationRecord: { reservationRecordId?: number; preName?: string; prePhone?: string; }) => {
    setReservationRecordSelectorVisible(false)
    if (selectedReservationRecord && 'reservationRecordId' in selectedReservationRecord) {
      form.setFieldsValue(Object.assign(form.getFieldsValue(), {
      reservationRecordId: selectedReservationRecord['reservationRecordId'],
      preName: selectedReservationRecord['preName'],
      prePhone: selectedReservationRecord['prePhone'],
      }));
    }
  };
  const handleCloseReservationRecordSelector = () => {
    setReservationRecordSelectorVisible(false)
  };
  const [roomSelectorVisible, setRoomSelectorVisible] = useState(false);
  const findRoom = () => {
    setRoomSelectorVisible(true);
  }
  const handleRoomSelected = (selectedRoom: { roomId?: number; roomNumber?: string; }) => {
    setRoomSelectorVisible(false)
    if (selectedRoom && 'roomId' in selectedRoom) {
      form.setFieldsValue(Object.assign(form.getFieldsValue(), {
      roomId: selectedRoom['roomId'],
      roomNumber: selectedRoom['roomNumber'],
      }));
    }
  };
  const handleCloseRoomSelector = () => {
    setRoomSelectorVisible(false)
  };

  const handleCloseCheckInRecordAdd = () => {
    setCheckInRecordAddVisible(false)
  };

  const handleCloseCheckInRecordView = () => {
    setCheckInRecordViewVisible(false)
  };

  const onExport = () => {
    const headers = ['预定人员姓名', '预定人员联系电话', '房号', '姓名', '联系电话', '入驻时间', '退房时间', '房费', '商品消费', '总金额', '备注', '状态']
    checkInRecordApi.find(form.getFieldsValue()).then(data => {
      if (!data || !data.data || data.data.list.length < 1) {
        messageApi.error('无数据导出')
        return
      }
      const exportData = []
      for (const d of data.data.list) {
        exportData.push([d.preName, d.prePhone, d.roomNumber, d.name, d.phone, d.checkInTime,
          d.checkOutTime, d.roomAmount, d.goodsAmount, d.amount, d.remark, getCheckInRecordStatusText(d.status)])
      }
      exportToExcel(headers, exportData)
    })
  }

  useEffect(() => {
    onSearch();

    return () => {
    };
  }, []);

  return (
    <div className="checkInRecordList">
      {messageContextHolder}
      {modalContextHolder}
      <Breadcrumb items={breadcrumbsItems} style={{marginBottom: 'var(--container-margin)'}} />
      <Form form={form} onFinish={onFinish} layout={"inline"}>
        <Form.Item name="preName" label="预定人员姓名">
          <Input.Search placeholder="请选择预定记录" onSearch={findReservationRecord} readOnly={true} />
        </Form.Item>
        <Form.Item name="prePhone" label="预定人员联系电话">
          <Input.Search placeholder="请选择预定记录" onSearch={findReservationRecord} readOnly={true} />
        </Form.Item>
        <Form.Item name="roomNumber" label="房号">
          <Input.Search placeholder="请选择房号" onSearch={findRoom} readOnly={true} />
        </Form.Item>
        <Form.Item name="name" label="姓名">
          <Input maxLength={64} placeholder="请输入姓名"/>
        </Form.Item>
        <Form.Item name="phone" label="联系电话">
          <Input maxLength={20} placeholder="请输入联系电话"/>
        </Form.Item>
        <Form.Item name="status" label="状态">
          <Select placeholder="请选择状态" options={[
            { value: 20, label: <span>已入驻</span> },
            { value: 30, label: <span>已取消</span> },
            { value: 40, label: <span>已退房</span> }
          ]} style={{width: 'var(--select-width)'}} />
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" htmlType="submit">查询</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button onClick={onReset}>重置</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" onClick={onAdd}>新增</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" onClick={onExport}>导出</Button>
        </Form.Item>
      </Form>
      <Table<CheckInRecord> columns={columns} dataSource={data} size="small" rowKey={record => record.id} pagination={{ position: ["bottomCenter"] }} style={{marginTop: 'var(--container-margin)'}} />
      <ReservationRecordSelector visible={reservationRecordSelectorVisible} onReservationRecordSelected={handleReservationRecordSelected} onCloseReservationRecordSelector={handleCloseReservationRecordSelector} />
      <RoomSelector visible={roomSelectorVisible} onRoomSelected={handleRoomSelected} onCloseRoomSelector={handleCloseRoomSelector} />
      <CheckInRecordAdd visible={checkInRecordAddVisible} onCloseCheckInRecordAdd={handleCloseCheckInRecordAdd} id={selectedCheckInRecordId} />
      <CheckInRecordView visible={checkInRecordViewVisible} onCloseCheckInRecordView={handleCloseCheckInRecordView} viewRow={selectedCheckInRecord} />
    </div>
  );
};

export default CheckInRecordList;
