// v2_el/src/views/checkInRecord/CheckInRecordAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="checkInRecordForm" :label-width="formLabelWidth" ref="refCheckInRecordForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="预定人员姓名" prop="preName">
            <el-input v-model="checkInRecordForm.preName" placeholder="请选择预定人员姓名" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findReservationRecord"></i>
            </el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="预定人员联系电话" prop="prePhone">
            <el-input v-model="checkInRecordForm.prePhone" placeholder="请选择预定人员联系电话" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findReservationRecord"></i>
            </el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="房号" prop="roomNumber">
            <el-input v-model="checkInRecordForm.roomNumber" placeholder="请选择房号" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findRoom"></i>
            </el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="姓名" prop="name">
            <el-input v-model="checkInRecordForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="联系电话" prop="phone">
            <el-input v-model="checkInRecordForm.phone" placeholder="请输入联系电话" maxlength="20"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="入驻时间" prop="checkInTime">
            <el-date-picker
                v-model="checkInRecordForm.checkInTime" type="datetime" placeholder="入驻时间" value-format="yyyy-MM-dd HH:mm:ss">
            </el-date-picker>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="退房时间" prop="checkOutTime">
            <el-date-picker
                v-model="checkInRecordForm.checkOutTime" type="datetime" placeholder="退房时间" value-format="yyyy-MM-dd HH:mm:ss">
            </el-date-picker>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="房费" prop="roomAmount">
            <el-input-number v-model="checkInRecordForm.roomAmount" :min="1" :max="9999999" @change="calculateAmount"></el-input-number>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="商品消费" prop="goodsAmount">
            <el-input-number v-model="checkInRecordForm.goodsAmount" :min="1" :max="9999999" @change="calculateAmount"></el-input-number>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="总金额" prop="amount">
            <el-input v-model="checkInRecordForm.amount" :disabled="true"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="remark" prop="remark">
            <el-input v-model="checkInRecordForm.remark" placeholder="请输入remark" maxlength="255"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="状态" prop="status">
            <el-select v-model="checkInRecordForm.status" placeholder="请选择状态">
              <el-option label="已入驻" :value="20"></el-option>
              <el-option label="已取消" :value="30"></el-option>
              <el-option label="已退房" :value="40"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button type="primary" @click="onReset" plain>重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="reservationRecordSelectorVisible" v-if="reservationRecordSelectorVisible" title="预定记录选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <reservation-record-selector @reservation-record-selected-event="handleReservationRecordSelectedEvent">
      </reservation-record-selector>
    </el-dialog>
    <el-dialog :visible.sync="roomSelectorVisible" v-if="roomSelectorVisible" title="房间选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <room-selector @room-selected-event="handleRoomSelectedEvent">
      </room-selector>
    </el-dialog>
  </div>
</template>

<script>
import checkInRecordApi from '@/api/checkInRecordApi'
import ReservationRecordSelector from "@/views/reservationRecord/ReservationRecordSelector.vue";
import RoomSelector from "@/views/room/RoomSelector.vue";
export default {
  name: 'CheckInRecordAdd',
  components: {ReservationRecordSelector,RoomSelector,},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      checkInRecordForm: {
        reservationRecordId: '',
        preName: '',
        prePhone: '',
        roomId: '',
        roomNumber: '',
        name: '',
        phone: '',
        checkInTime: '',
        checkOutTime: '',
        roomAmount: '',
        goodsAmount: '',
        amount: '',
        remark: '',
        status: ''
      },
      rules: {
        roomNumber:[
          { required: true, message: '请输入房号', trigger: 'blur' }
        ],
        name:[
          { required: true, message: '请输入姓名', trigger: 'blur' }
        ],
      },
      reservationRecordSelectorVisible: false,
      roomSelectorVisible: false,
    }
  },
  created () {
    if (this.id) {
      checkInRecordApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.checkInRecordForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  mounted() {
    this.calculateAmount()
  },
  methods: {
    onReset () {
      this.checkInRecordForm = {
        reservationRecordId: '',
        preName: '',
        prePhone: '',
        roomId: '',
        roomNumber: '',
        name: '',
        phone: '',
        checkInTime: '',
        checkOutTime: '',
        roomAmount: '',
        goodsAmount: '',
        amount: '',
        remark: '',
        status: ''
      }
      this.$emit('reset-check-in-record-add-event')
    },
    onSave () {
      this.$refs.refCheckInRecordForm.validate((valid) => {
        if (valid) {
          checkInRecordApi.save(this.checkInRecordForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-check-in-record-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    findReservationRecord () {
      this.reservationRecordSelectorVisible = true
    },
    handleReservationRecordSelectedEvent (selectedReservationRecord) {
      this.reservationRecordSelectorVisible = false
      if (selectedReservationRecord && 'reservationRecordId' in selectedReservationRecord && this.checkInRecordForm.reservationRecordId !== selectedReservationRecord['reservationRecordId']) {
        this.checkInRecordForm.reservationRecordId = selectedReservationRecord['reservationRecordId']
        this.checkInRecordForm.preName = selectedReservationRecord['preName']
        this.checkInRecordForm.prePhone = selectedReservationRecord['prePhone']
      }
    },
    findRoom () {
      this.roomSelectorVisible = true
    },
    handleRoomSelectedEvent (selectedRoom) {
      this.roomSelectorVisible = false
      if (selectedRoom && 'roomId' in selectedRoom && this.checkInRecordForm.roomId !== selectedRoom['roomId']) {
        this.checkInRecordForm.roomId = selectedRoom['roomId']
        this.checkInRecordForm.roomNumber = selectedRoom['roomNumber']
      }
    },
    onBack () {
      this.$emit('close-check-in-record-add-event')
    },
    calculateAmount() {
      this.checkInRecordForm.amount = this.checkInRecordForm.roomAmount + this.checkInRecordForm.goodsAmount
    }
  }
}
</script>

<style lang="scss">
</style>

// react_antd/src/pages/checkInRecord/CheckInRecordAdd.tsx
import React, {useEffect, useState} from "react";
import {Button, Col, DatePicker, Form, Input, InputNumber, message, Modal, Row, Select} from "antd";
import type {Result} from "@/types/result";
import checkInRecordApi from "@/api/checkInRecordApi.ts";
import {CheckInRecord} from "@/types/resp/checkInRecord";
import ReservationRecordSelector from "@/pages/reservationRecord/ReservationRecordSelector.tsx";
import RoomSelector from "@/pages/room/RoomSelector.tsx";

interface CheckInRecordAddProps {
  visible: boolean;
  id: number;
  onCloseCheckInRecordAdd: () => void;
}

const CheckInRecordAdd: React.FC<CheckInRecordAddProps> = ({visible, id, onCloseCheckInRecordAdd}) => {

  const [form] = Form.useForm<CheckInRecord>();
  const [messageApi, messageContextHolder] = message.useMessage();

  const rules = {
    preName: [
      { required: true, message: '请选择预定记录' }
    ],
    prePhone: [
      { required: true, message: '请选择预定记录' }
    ],
    roomNumber: [
      { required: true, message: '请输入房号' }
    ],
    name: [
      { required: true, message: '请输入姓名' }
    ],
    checkInTime: [
      { required: true, message: '请输入入驻时间' }
    ],
  };

  let checkInRecordForm: Partial<CheckInRecord> = {}

  const [title, setTitle] = useState('新增入住记录');

  useEffect(() => {
    if (!visible) {
      return
    }
    if (id) {
      setTitle('编辑入住记录')
      initCheckInRecordFormById(id)
    } else {
      setTitle('新增入住记录')
      form.resetFields();
    }
  }, [visible]);

  const initCheckInRecordFormById = async (id: number) => {
    const resp: Result<CheckInRecord> = await checkInRecordApi.findById(id)
    if (resp && resp.code === 1 && resp.data) {
      checkInRecordForm = resp.data
      form.setFieldsValue(resp.data);
    }
  }

  const onSave = async () => {
    try {
      await form.validateFields()

      let checkInRecord2Save:CheckInRecord = form.getFieldsValue()
      if (id) {
        checkInRecord2Save = Object.assign(checkInRecordForm, checkInRecord2Save)
      }
      const resp: Result<void> = await checkInRecordApi.save(checkInRecord2Save);
      if (!resp || resp.code !== 1) {
        messageApi.error('保存失败:' + (resp.msg ? resp.msg : '未知异常'));
        return
      }
      messageApi.success('保存成功');
      onBack()
    } catch (error) {
      console.error('There was an error submitting the form!', error);
    }
  };

  const onReset = () => {
    setTitle('新增入住记录')
    form.resetFields();
  };
  
  const [reservationRecordSelectorVisible, setReservationRecordSelectorVisible] = useState(false);
  const findReservationRecord = () => {
    setReservationRecordSelectorVisible(true);
  }
  const handleReservationRecordSelected = (selectedReservationRecord: { reservationRecordId?: number; preName?: string; prePhone?: string; }) => {
    setReservationRecordSelectorVisible(false)
    if (selectedReservationRecord && 'reservationRecordId' in selectedReservationRecord) {
      form.setFieldsValue(Object.assign(form.getFieldsValue(), {
      reservationRecordId: selectedReservationRecord['reservationRecordId'],
      preName: selectedReservationRecord['preName'],
      prePhone: selectedReservationRecord['prePhone'],
      }));
    }
  };
  const handleCloseReservationRecordSelector = () => {
    setReservationRecordSelectorVisible(false)
  };
  const [roomSelectorVisible, setRoomSelectorVisible] = useState(false);
  const findRoom = () => {
    setRoomSelectorVisible(true);
  }
  const handleRoomSelected = (selectedRoom: { roomId?: number; roomNumber?: string; }) => {
    setRoomSelectorVisible(false)
    if (selectedRoom && 'roomId' in selectedRoom) {
      form.setFieldsValue(Object.assign(form.getFieldsValue(), {
      roomId: selectedRoom['roomId'],
      roomNumber: selectedRoom['roomNumber'],
      }));
    }
  };
  const handleCloseRoomSelector = () => {
    setRoomSelectorVisible(false)
  };

  const onBack = () => {
    onCloseCheckInRecordAdd()
  };

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onSave}>保存</Button>
      <Button onClick={onReset} style={{marginLeft: 'var(--button-margin-left)'}}>重置</Button>
      <Button type="primary" onClick={onBack} style={{marginLeft: 'var(--button-margin-left)'}}>关闭</Button>
    </div>
  );

  return (
    <Modal title={title} open={visible} onCancel={onCloseCheckInRecordAdd} width={'var(--modal-width)'}
        footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      {messageContextHolder}
      <Form form={form} name="checkInRecordForm" labelCol={{span: 6}}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="preName" label="预定人员姓名" rules={rules.preName}>
              <Input.Search placeholder="请选择预定记录" onSearch={findReservationRecord} readOnly={true} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="prePhone" label="预定人员联系电话" rules={rules.prePhone}>
              <Input.Search placeholder="请选择预定记录" onSearch={findReservationRecord} readOnly={true} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="roomNumber" label="房号" rules={rules.roomNumber}>
              <Input.Search placeholder="请选择房号" onSearch={findRoom} readOnly={true} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="name" label="姓名" rules={rules.name}>
              <Input maxLength={64} placeholder="请输入姓名"/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="phone" label="联系电话">
              <Input maxLength={20} placeholder="请输入联系电话"/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="checkInTime" label="入驻时间" rules={rules.checkInTime}>
              <DatePicker showTime={true}/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="checkOutTime" label="退房时间">
              <DatePicker showTime={true}/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="roomAmount" label="房费">
              <InputNumber min={1} max={99999999} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="goodsAmount" label="商品消费">
              <InputNumber min={1} max={99999999} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="amount" label="总金额">
              <InputNumber min={1} max={99999999} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="remark" label="remark">
              <Input maxLength={255} placeholder="请输入remark"/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="status" label="状态">
              <Select placeholder="请选择状态" options={[
                { value: 20, label: <span>已入驻</span> },
                { value: 30, label: <span>已取消</span> },
                { value: 40, label: <span>已退房</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
      </Form>
      <ReservationRecordSelector visible={reservationRecordSelectorVisible} onReservationRecordSelected={handleReservationRecordSelected} onCloseReservationRecordSelector={handleCloseReservationRecordSelector} />
      <RoomSelector visible={roomSelectorVisible} onRoomSelected={handleRoomSelected} onCloseRoomSelector={handleCloseRoomSelector} />
    </Modal>
  )
}

export default CheckInRecordAdd;
