// react_antd/src/pages/admin/AdminAdd.tsx
import React, {useEffect, useState} from "react";
import {Button, Col, Form, Input, message, Modal, Row} from "antd";
import type {Result} from "@/types/result";
import adminApi from "@/api/adminApi.ts";
import {Admin} from "@/types/resp/admin";

interface AdminAddProps {
  visible: boolean;
  id: number;
  onCloseAdminAdd: () => void;
}

const AdminAdd: React.FC<AdminAddProps> = ({visible, id, onCloseAdminAdd}) => {

  const [form] = Form.useForm<Admin>();
  const [messageApi, messageContextHolder] = message.useMessage();

  const rules = {
    username: [
      { required: true, message: '请输入用户名' }
    ],
    password: [
      { required: true, message: '请输入密码' }
    ],
    name: [
      { required: true, message: '请输入姓名' }
    ],
  };

  let adminForm: Partial<Admin> = {}

  const [title, setTitle] = useState('新增管理员');

  useEffect(() => {
    if (!visible) {
      return
    }
    if (id) {
      setTitle('编辑管理员')
      initAdminFormById(id)
    } else {
      setTitle('新增管理员')
      form.resetFields();
    }
  }, [visible]);

  const initAdminFormById = async (id: number) => {
    const resp: Result<Admin> = await adminApi.findById(id)
    if (resp && resp.code === 1 && resp.data) {
      adminForm = resp.data
      form.setFieldsValue(resp.data);
    }
  }

  const onSave = async () => {
    try {
      await form.validateFields()

      let admin2Save:Admin = form.getFieldsValue()
      if (id) {
        admin2Save = Object.assign(adminForm, admin2Save)
      }
      const resp: Result<void> = await adminApi.save(admin2Save);
      if (!resp || resp.code !== 1) {
        messageApi.error('保存失败:' + (resp.msg ? resp.msg : '未知异常'));
        return
      }
      messageApi.success('保存成功');
      onBack()
    } catch (error) {
      console.error('There was an error submitting the form!', error);
    }
  };

  const onReset = () => {
    setTitle('新增管理员')
    form.resetFields();
  };
  

  const onBack = () => {
    onCloseAdminAdd()
  };

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onSave}>保存</Button>
      <Button onClick={onReset} style={{marginLeft: 'var(--button-margin-left)'}}>重置</Button>
      <Button type="primary" onClick={onBack} style={{marginLeft: 'var(--button-margin-left)'}}>关闭</Button>
    </div>
  );

  return (
    <Modal title={title} open={visible} onCancel={onCloseAdminAdd} width={'var(--modal-width)'}
        footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      {messageContextHolder}
      <Form form={form} name="adminForm" labelCol={{span: 6}}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="username" label="用户名" rules={rules.username}>
              <Input maxLength={64} placeholder="请输入用户名"/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="password" label="密码" rules={rules.password}>
              <Input maxLength={255} placeholder="请输入密码"/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="name" label="姓名" rules={rules.name}>
              <Input maxLength={64} placeholder="请输入姓名"/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default AdminAdd;

// v3_el/src/views/admin/AdminAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
      <el-form label-position="right" :model="adminForm" :label-width="formLabelWidth" ref="adminFormRef" :rules="rules">
        <el-row>
          <el-col :span="11">
            <el-form-item label="用户名" prop="username">
              <el-input v-model="adminForm.username" placeholder="请输入用户名" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="11">
            <el-form-item label="密码" prop="password">
              <el-input v-model="adminForm.password" placeholder="请输入密码" maxlength="255"></el-input>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="11">
            <el-form-item label="姓名" prop="name">
              <el-input v-model="adminForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script setup lang="ts">
import {defineEmits, defineProps, inject, onMounted, reactive, ref, toRefs} from 'vue';
import adminApi from '@/api/adminApi'
import type {FormInstance} from 'element-plus';
import {ElMessage} from 'element-plus'
import type {AdminForm} from "@/types/req/adminForm";
import type {Result} from '@/types/result'
import type {Admin} from "@/types/resp/admin";
import type {Id} from "@/types/id";

const props = defineProps<Id>()
const adminFormRef = ref<FormInstance | null>(null);
const adminForm = reactive<AdminForm>({
  username: '',
  password: '',
  name: ''
})
const emit = defineEmits<{
  (e: 'resetAdminAddEvent'): void;
  (e: 'closeAdminAddEvent', data?: { search: boolean }): void;
}>()

const rules = reactive({
  username: [
    { required: true, message: '请输入用户名', trigger: 'blur' }
  ],
  password: [
    { required: true, message: '请输入密码', trigger: 'blur' }
  ],
  name: [
    { required: true, message: '请输入姓名', trigger: 'blur' }
  ],
});
const formLabelWidth = ref<string>('')

onMounted(() => {
  if (props.id) {
    initAdminFormById(props.id)
  }
  const globalState = inject('globalState', {} as { formLabelWidth?: string })
  if (!globalState) {
    throw new Error('globalState is not provided');
  }
  const globalStateRefs = toRefs(globalState)
  if (globalStateRefs.formLabelWidth) {
    formLabelWidth.value = globalStateRefs.formLabelWidth.value || ''
  }
});

const initAdminFormById = async (id: number) => {
  const resp: Result<Admin> = await adminApi.findById(id)
  if (resp && resp.code === 1 && resp.data) {
    Object.assign(adminForm, resp.data)
  }
}

const onReset = () => {
  if (adminFormRef.value) {
    adminFormRef.value.resetFields()
  }
  emit('resetAdminAddEvent')
}

const onSave = () => {
  if (!adminFormRef.value) {
    return
  }
  adminFormRef.value.validate(async (valid: boolean) => {
    if (valid) {
      const resp: Result<void> = await adminApi.save(adminForm)
      if (resp && resp.code === 1) {
        ElMessage.success('保存成功')
        emit('closeAdminAddEvent', {search: true})
      } else {
        ElMessage.error('保存失败:' + (resp.msg ? resp.msg : ''))
      }
    }
  })
}

const onBack = () => {
  emit('closeAdminAddEvent')
}
</script>

<style lang="scss">
</style>
