// v3_el/src/views/checkInRecord/CheckInRecordSelector.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
      <el-form :inline="true" :model="checkInRecordQueryForm" ref="checkInRecordQueryFormRef" :rules="rules">
        <el-form-item label="房号" prop="roomNumber">
          <el-input v-model="checkInRecordQueryForm.roomNumber" placeholder="请选择房号" readonly="readonly">
            <template #suffix>
              <el-icon @click="findRoom"><Search/></el-icon>
            </template>
          </el-input>
        </el-form-item>
        <el-form-item label="姓名" prop="name">
          <el-input v-model="checkInRecordQueryForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
        </el-form-item>
        <el-form-item label="联系电话" prop="phone">
          <el-input v-model="checkInRecordQueryForm.phone" placeholder="请输入联系电话" maxlength="20"></el-input>
        </el-form-item>
        <el-form-item label="状态" prop="status">
          <el-select v-model="checkInRecordQueryForm.status" placeholder="请选择状态" class="select-custom">
            <el-option label="已入驻" :value="20"></el-option>
            <el-option label="已取消" :value="30"></el-option>
            <el-option label="已退房" :value="40"></el-option>
          </el-select>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="onSearch">查询</el-button>
          <el-button @click="onReset">重置</el-button>
        </el-form-item>
      </el-form>

      <el-table
        :data="state.tableData"
        border
        v-loading="state.loading"
        size="small"
        header-cell-class-name="table-header-cell-font"
        cell-class-name="table-cell-font"
        @row-dblclick="checkInRecordSelected">
        <el-table-column prop="preName" label="预定人员姓名"></el-table-column>
        <el-table-column prop="prePhone" label="预定人员联系电话"></el-table-column>
        <el-table-column prop="roomNumber" label="房号"></el-table-column>
        <el-table-column prop="name" label="姓名"></el-table-column>
        <el-table-column prop="phone" label="联系电话"></el-table-column>
        <el-table-column prop="checkInTime" label="入驻时间"></el-table-column>
        <el-table-column prop="checkOutTime" label="退房时间"></el-table-column>
        <el-table-column prop="roomAmount" label="房费"></el-table-column>
        <el-table-column prop="goodsAmount" label="商品消费"></el-table-column>
        <el-table-column prop="amount" label="总金额"></el-table-column>
        <el-table-column prop="remark" label="remark"></el-table-column>
        <el-table-column prop="status" label="状态">
          <template v-slot="{ row }">
            <div v-if="row.status === 20">已入驻</div>
            <div v-if="row.status === 30">已取消</div>
            <div v-if="row.status === 40">已退房</div>
          </template>
        </el-table-column>
      </el-table>
      <div class="table-pagination">
        <el-pagination
          @current-change="changePage"
          :current-page="state.currentPage"
          :page-sizes="state.pageSizes"
          :page-size="state.pageSize"
          background
          layout="total, prev, pager, next, jumper"
          :total="state.total">
        </el-pagination>
      </div>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog v-model="roomSelectorVisible" v-if="roomSelectorVisible" title="房间选择器(双击行选中)" :top="dialogTop" :width="dialogWidth">
      <room-selector @room-selected-event="handleRoomSelectedEvent">
      </room-selector>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import {onMounted, reactive, ref, inject, toRefs, defineEmits} from 'vue';
import checkInRecordApi from '@/api/checkInRecordApi'
import type {CheckInRecordQueryForm} from "@/types/req/checkInRecordQueryForm";
import type {CheckInRecord} from "@/types/resp/checkInRecord";
import {type FormInstance} from "element-plus";
import type {Result} from "@/types/result";
import type {Page} from "@/types/page";
import { Search } from '@element-plus/icons-vue';
import RoomSelector from "@/views/room/RoomSelector.vue";

const checkInRecordQueryFormRef = ref<FormInstance | null>(null);
const checkInRecordQueryForm = reactive<CheckInRecordQueryForm>({
  roomId: 0,
  roomNumber: '',
  name: '',
  phone: '',
  status: undefined,
})
const roomSelectorVisible = ref<boolean>(false)

const state = reactive({
  loading: false,
  tableData: [] as CheckInRecord[], // 数据列表
  total: 0, // 总条数
  currentPage: 1, // 当前页
  pageSize: 10, // 分页大小
  pageSizes: [10, 20, 50]
})

const dialogTop = ref<string>('')
const dialogWidth = ref<string>('')

const rules = reactive({
});

const emit = defineEmits<{
  (e: 'checkInRecordSelectedEvent', data?: {
    checkInRecordId: number,
    name: string,
    phone: string,
    }): void;
}>()

onMounted(() => {
  onSearch()
  const globalState = inject('globalState', {} as { dialogWidth?: string, dialogTop?: string })
  if (!globalState) {
    throw new Error('globalState is not provided');
  }
  const globalStateRefs = toRefs(globalState)
  if (globalStateRefs.dialogWidth) {
    dialogWidth.value = globalStateRefs.dialogWidth.value || ''
  }
  if (globalStateRefs.dialogTop) {
    dialogTop.value = globalStateRefs.dialogTop.value || ''
  }
})

const getPageData = async () => {
  try {
    state.loading = true
    const resp: Result<Page<CheckInRecord>> = await checkInRecordApi.find(checkInRecordQueryForm)
    if (resp && resp.code === 1) {
      if (resp.data) {
        const page: Page<CheckInRecord> = resp.data
        if (page && page.list.length > 0) {
          state.tableData = page.list
          state.total = page.total
        }
      }
    }
  } catch (e) {
    console.log('获取数据异常', e)
  } finally {
    state.loading = false
  }
}
const onSearch = () => {
  getPageData()
}

const changePage = (val: number) => {
  state.currentPage = val
  getPageData()
}

const onReset = () => {
  if (checkInRecordQueryFormRef.value) {
    checkInRecordQueryFormRef.value.resetFields()
  }
  state.currentPage = 1
  getPageData()
}

const checkInRecordSelected = (row: CheckInRecord) => {
  emit('checkInRecordSelectedEvent', {
    checkInRecordId: row.id,
    name: row.name,
    phone: row.phone,
  })
}

const findRoom = () => {
  roomSelectorVisible.value = true
}

const handleRoomSelectedEvent = (selectedRoom: any) => {
  roomSelectorVisible.value = false
  if (selectedRoom && 'roomId' in selectedRoom && checkInRecordQueryForm.roomId !== selectedRoom['roomId']) {
    checkInRecordQueryForm.roomId = selectedRoom['roomId']
    checkInRecordQueryForm.roomNumber = selectedRoom['roomNumber']
  }
}

const onBack = () => {
  emit('checkInRecordSelectedEvent')
}
</script>

<style lang="scss">
</style>

// angular_ngzorro/src/app/check-in-record/check-in-record-selector.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {CheckInRecordService} from '../../service/check-in-record.service';
import {CheckInRecordQueryForm} from '../../types/req/CheckInRecordQueryForm';
import {SharedModule} from '../shared.module';
import {CheckInRecord} from '../../types/resp/CheckInRecord';
import {Page} from '../../types/page';
import {NzModalService} from 'ng-zorro-antd/modal';
import {MODAL_WIDTH} from '../../const';
import {ReservationRecordSelectorComponent} from '../reservation-record/reservation-record-selector.component';
import {RoomSelectorComponent} from '../room/room-selector.component';

@Component({
  selector: 'check-in-record-selector',
  imports: [
    ReservationRecordSelectorComponent,
    RoomSelectorComponent,
    SharedModule
  ],
  templateUrl: './check-in-record-selector.component.html',
  standalone: true
})
export class CheckInRecordSelectorComponent implements OnInit {
  searchForm!: FormGroup;
  searchLoading: boolean = false
  listOfData: CheckInRecord[] = [];
  total: number = 0
  isVisible: boolean = false
  title: string = '入住记录选择器(双击行选中)'
  modalWidth: string = MODAL_WIDTH

  @ViewChild(ReservationRecordSelectorComponent, { static: false }) reservationRecordSelectorComponent!: ReservationRecordSelectorComponent;
  @ViewChild(RoomSelectorComponent, { static: false }) roomSelectorComponent!: RoomSelectorComponent;

  @Output() checkInRecordSelectedEvent = new EventEmitter<{}>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private checkInRecordService: CheckInRecordService,
    private modal: NzModalService
  ) {}

  ngOnInit(): void {
    this.searchForm = this.fb.group({
      reservationRecordId: [0],
      preName: [''],
      prePhone: [''],
      roomId: [0],
      roomNumber: [''],
      name: [''],
      phone: [''],
      status: [undefined],
    })
    this.onSearch()
  }

  onReset() {
    this.searchForm.reset()
  }

  onSearch() {
    try {
      this.searchLoading = true
      this.checkInRecordService.find(new CheckInRecordQueryForm(this.searchForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          const page: Page<CheckInRecord> | undefined = resp.data
          if (page && page.list.length > 0) {
            this.listOfData = page.list
            this.total = page.total
          }
        },
        complete: () => {
          this.searchLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onRowDblClick(row: CheckInRecord, event: MouseEvent) {
    this.isVisible = false
    this.checkInRecordSelectedEvent.emit({
      checkInRecordId: row.id,
      name: row.name,
      phone: row.phone,
    });
  }

  onBack() {
    this.isVisible = false
  }

  display() {
    this.isVisible = true
    this.searchForm.reset();
  }

  findReservationRecord() {
    this.reservationRecordSelectorComponent.display()
  }

  handleReservationRecordSelectedEvent(selectedReservationRecord: { reservationRecordId?: number; preName?: string;prePhone?: string; }) {
    if (selectedReservationRecord && 'reservationRecordId' in selectedReservationRecord) {
      this.searchForm.patchValue(selectedReservationRecord);
    }
  }
  findRoom() {
    this.roomSelectorComponent.display()
  }

  handleRoomSelectedEvent(selectedRoom: { roomId?: number; roomNumber?: string; }) {
    if (selectedRoom && 'roomId' in selectedRoom) {
      this.searchForm.patchValue(selectedRoom);
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form nz-form class="search-form" [formGroup]="searchForm" (keydown.enter)="$event.preventDefault();onSearch()" nzLayout="inline">
            <nz-form-item>
        <nz-form-label nzFor="preName">预定人员姓名</nz-form-label>
        <nz-form-control>
          <nz-input-group nzSearch [nzAddOnAfter]="preNameSuffixIconButton">
            <input nz-input formControlName="preName" placeholder="请选择预定人员姓名" readonly />
          </nz-input-group>
          <ng-template #preNameSuffixIconButton>
            <button nz-button nzType="primary" nzSearch (click)="findReservationRecord()"><nz-icon nzType="search" /></button>
          </ng-template>
        </nz-form-control>
      </nz-form-item>
      <nz-form-item>
        <nz-form-label nzFor="prePhone">预定人员联系电话</nz-form-label>
        <nz-form-control>
          <nz-input-group nzSearch [nzAddOnAfter]="prePhoneSuffixIconButton">
            <input nz-input formControlName="prePhone" placeholder="请选择预定人员联系电话" readonly />
          </nz-input-group>
          <ng-template #prePhoneSuffixIconButton>
            <button nz-button nzType="primary" nzSearch (click)="findReservationRecord()"><nz-icon nzType="search" /></button>
          </ng-template>
        </nz-form-control>
      </nz-form-item>
      <nz-form-item>
        <nz-form-label nzFor="roomNumber">房号</nz-form-label>
        <nz-form-control>
          <nz-input-group nzSearch [nzAddOnAfter]="roomNumberSuffixIconButton">
            <input nz-input formControlName="roomNumber" placeholder="请选择房号" readonly />
          </nz-input-group>
          <ng-template #roomNumberSuffixIconButton>
            <button nz-button nzType="primary" nzSearch (click)="findRoom()"><nz-icon nzType="search" /></button>
          </ng-template>
        </nz-form-control>
      </nz-form-item>
<nz-form-item>
        <nz-form-label nzFor="name">姓名</nz-form-label>
        <nz-form-control>
          <input nz-input formControlName="name" placeholder="请输入姓名" />
        </nz-form-control>
      </nz-form-item>
<nz-form-item>
        <nz-form-label nzFor="phone">联系电话</nz-form-label>
        <nz-form-control>
          <input nz-input formControlName="phone" placeholder="请输入联系电话" />
        </nz-form-control>
      </nz-form-item>
      <nz-form-item>
        <nz-form-label nzFor="status">状态</nz-form-label>
        <nz-form-control>
          <nz-select formControlName="status" class="custom-select-width">
            <nz-option nzLabel="已入驻" [nzValue]="20"></nz-option>
            <nz-option nzLabel="已取消" [nzValue]="30"></nz-option>
            <nz-option nzLabel="已退房" [nzValue]="40"></nz-option>
          </nz-select>
        </nz-form-control>
      </nz-form-item>
      <button nz-button type="button" nzType="primary" [nzLoading]="searchLoading" (click)="onSearch()">查询</button>
      <button nz-button type="button" class="margin-button" (click)="onReset()">重置</button>
    </form>
    <nz-table #basicTable [nzData]="listOfData" [nzTotal]="total" [nzLoading]="searchLoading" nzSize="small">
      <thead>
        <tr>
          <th>预定人员姓名</th>
          <th>预定人员联系电话</th>
          <th>房号</th>
          <th>姓名</th>
          <th>联系电话</th>
          <th>入驻时间</th>
          <th>退房时间</th>
          <th>房费</th>
          <th>商品消费</th>
          <th>总金额</th>
          <th>备注</th>
          <th>状态</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let data of basicTable.data" (dblclick)="onRowDblClick(data, $event)">
          <td>{{data.preName}}</td>
          <td>{{data.prePhone}}</td>
          <td>{{data.roomNumber}}</td>
          <td>{{data.name}}</td>
          <td>{{data.phone}}</td>
          <td>{{data.checkInTime}}</td>
          <td>{{data.checkOutTime}}</td>
          <td>{{data.roomAmount}}</td>
          <td>{{data.goodsAmount}}</td>
          <td>{{data.amount}}</td>
          <td>{{data.remark}}</td>
          <td>
            <ng-container *ngIf="data.status === 20">已入驻</ng-container>
            <ng-container *ngIf="data.status === 30">已取消</ng-container>
            <ng-container *ngIf="data.status === 40">已退房</ng-container>
          </td>
        </tr>
      </tbody>
    </nz-table>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
<reservation-record-selector (reservationRecordSelectedEvent)="handleReservationRecordSelectedEvent($event)"></reservation-record-selector>
<room-selector (roomSelectedEvent)="handleRoomSelectedEvent($event)"></room-selector>
