// v2_el/src/views/roomMaintenanceRecord/RoomMaintenanceRecordView.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="roomMaintenanceRecordForm" label-width="150px" disabled="disabled">
      <el-row>
        <el-col :span="11">
          <el-form-item label="房号">
            <el-input v-model="roomMaintenanceRecordForm.roomNumber"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="姓名">
            <el-input v-model="roomMaintenanceRecordForm.staffName"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="联系电话">
            <el-input v-model="roomMaintenanceRecordForm.staffPhone"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="开始时间">
            <el-input v-model="roomMaintenanceRecordForm.startTime"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="结束时间">
            <el-input v-model="roomMaintenanceRecordForm.endTime"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="维护内容">
            <el-input v-model="roomMaintenanceRecordForm.content"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="创建时间">
            <el-input v-model="roomMaintenanceRecordForm.createTime"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="12" :offset="6">
          <div class="form-button-container">
            <el-button @click="onBack" type="primary">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script>
import roomMaintenanceRecordApi from '@/api/roomMaintenanceRecordApi'
export default {
  name: 'RoomMaintenanceRecordView',
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      roomMaintenanceRecordForm: {
      }
    }
  },
  created () {
    if (this.id) {
      roomMaintenanceRecordApi.findById(this.id)
          .then(resp => {
            if (resp && resp.code === 1) {
              this.roomMaintenanceRecordForm = resp.data
            } else {
              this.$message.error('获取数据失败')
            }
          })
          .catch(error => {
            console.error('获取数据失败:', error)
          })
    }
  },
  methods: {
    onBack () {
      this.$emit('close-room-maintenance-record-view-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// react_antd/src/pages/roomMaintenanceRecord/RoomMaintenanceRecordView.tsx
import React, {useEffect} from "react";
import {Button, Col, DatePicker, Form, Input, Modal, Row} from "antd";
import {RoomMaintenanceRecord} from "@/types/resp/roomMaintenanceRecord";

interface RoomMaintenanceRecordViewProps {
  visible: boolean;
  viewRow: object;
  onCloseRoomMaintenanceRecordView: () => void;
}

const RoomMaintenanceRecordView: React.FC<RoomMaintenanceRecordViewProps> = ({visible, viewRow, onCloseRoomMaintenanceRecordView}) => {

  const [form] = Form.useForm<RoomMaintenanceRecord>();

  const onBack = () => {
    onCloseRoomMaintenanceRecordView()
  };

  useEffect(() => {
    if (!visible) {
      return
    }
    if (viewRow) {
      form.setFieldsValue(viewRow);
    }
  }, [viewRow]);

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onBack}>关闭</Button>
    </div>
  );

  return (
    <Modal title={"房间维护记录详情"} open={visible} onCancel={onCloseRoomMaintenanceRecordView}
        width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={form} labelCol={{span: 6}} disabled={true}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="roomNumber" label="房号">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="staffName" label="员工姓名">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="staffPhone" label="员工联系电话">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="startTime" label="开始时间">
              <DatePicker showTime={true}/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="endTime" label="结束时间">
              <DatePicker showTime={true}/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="content" label="维护内容">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="createTime" label="创建时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default RoomMaintenanceRecordView;
