// react_antd/src/pages/reservationRecord/ReservationRecordList.tsx
import React, {useCallback, useEffect, useState} from 'react';
import {Breadcrumb, Button, Form, Input, message, Modal, Select, Space, Table, TableProps} from 'antd';
import {useNavigate} from "react-router-dom";
import type {ReservationRecord} from "@/types/resp/reservationRecord";
import reservationRecordApi from '@/api/reservationRecordApi'
import {Result} from "@/types/result";
import {Page} from "@/types/page";
import ReservationRecordAdd from "@/pages/reservationRecord/ReservationRecordAdd.tsx";
import ReservationRecordView from "@/pages/reservationRecord/ReservationRecordView.tsx";
import RoomSelector from "@/pages/room/RoomSelector.tsx";
import {exportToExcel} from "@/utils/exportUtil.ts";
import {getReservationRecordStatusText} from "@/utils/dictTranslator.ts";


const ReservationRecordList: React.FC = () => {

  const navigate = useNavigate();
  const [messageApi, messageContextHolder] = message.useMessage();
  const [modal, modalContextHolder] = Modal.useModal();

  const handleClick = (path: string) => {
    navigate(path);
  };

  const breadcrumbsItems = [
    {title: '首页', className: 'breadcrumbHome', onClick: () => handleClick('/Home')},
    {title: '预定记录列表'}
  ]

  const [form] = Form.useForm();

  const onFinish = async () => {
    await onSearch()
  };

  const onReset = () => {
    form.resetFields();
  };

  const [data, setData] = useState<ReservationRecord[]>([]);
  const onSearch = async () => {
    try {
      const resp: Result<Page<ReservationRecord>> = await reservationRecordApi.find(form.getFieldsValue())
      if (resp && resp.code === 1) {
        if (resp.data) {
          const page: Page<ReservationRecord> = resp.data
          if (page && page.list.length > 0) {
            setData(page.list)
          }
        }
      }
    } catch (e) {
      console.log('获取数据异常', e)
    }
  };

  const columns: TableProps<ReservationRecord>['columns'] = [
    {title: '房号', dataIndex: 'roomNumber', key: 'roomNumber'},
    {title: '姓名', dataIndex: 'name', key: 'name'},
    {title: '联系电话', dataIndex: 'phone', key: 'phone'},
    {title: '预定入驻时间', key: 'checkInTime', render: (_, record) => (
      <div>{record.checkInTime.format('YYYY-MM-DD HH:mm:ss')}</div>
    )},
    {title: '备注', dataIndex: 'remark', key: 'remark'},
    {title: '状态', key: 'status', render: (_, record) => (
        <span>
        {(function () {
          if (record.status === 10) return '已预定';
          else if (record.status === 20) return '已入驻';
          else if (record.status === 30) return '已取消';
          else return '未知';
        })()}
      </span>
      ),
    },
    {
      title: '操作',
      key: 'action',
      width: '250px',
      render: (_, record) => (
        <Space size="middle">
          <Button type="primary" onClick={() => editRow(record.id)}>编辑</Button>
          <Button danger onClick={() => delRow(record.id)}>删除</Button>
          <Button color="primary" variant="outlined" onClick={() => detailRow(record)}>详情</Button>
        </Space>
      ),
    },
  ];

  const [reservationRecordAddVisible, setReservationRecordAddVisible] = useState(false);
  const [reservationRecordViewVisible, setReservationRecordViewVisible] = useState(false);
  const [selectedReservationRecordId, setSelectedReservationRecordId] = useState(0)
  const [selectedReservationRecord, setSelectedReservationRecord] = useState({})

  const onAdd = () => {
    setSelectedReservationRecordId(0)
    setReservationRecordAddVisible(true)
  };

  const editRow = (id: number) => {
    setSelectedReservationRecordId(id)
    setReservationRecordAddVisible(true)
  };

  const delRow = useCallback(async (id: number) => {
    const confirmed = await modal.confirm({
      title: '删除提示',
      content: (
        <>
          确定要删除吗?
        </>
      ),
      okText: '确定',
      cancelText: '取消',
      type: 'warning'
    });

    if (confirmed) {
      reservationRecordApi.del(id)
        .then((resp) => {
          if (resp && resp.code === 1) {
            messageApi.success('删除成功!')
            onSearch()
          } else {
            messageApi.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
          }
        })
        .catch(error => {
          console.error('操作失败:', error)
        })
    }
  }, [modal]);

  const detailRow = (record: ReservationRecord) => {
    setSelectedReservationRecord(record)
    setReservationRecordViewVisible(true)
  };

  const [roomSelectorVisible, setRoomSelectorVisible] = useState(false);
  const findRoom = () => {
    setRoomSelectorVisible(true);
  }
  const handleRoomSelected = (selectedRoom: { roomId?: number; roomNumber?: string; }) => {
    setRoomSelectorVisible(false)
    if (selectedRoom && 'roomId' in selectedRoom) {
      form.setFieldsValue(Object.assign(form.getFieldsValue(), {
      roomId: selectedRoom['roomId'],
      roomNumber: selectedRoom['roomNumber'],
      }));
    }
  };
  const handleCloseRoomSelector = () => {
    setRoomSelectorVisible(false)
  };

  const handleCloseReservationRecordAdd = () => {
    setReservationRecordAddVisible(false)
  };

  const handleCloseReservationRecordView = () => {
    setReservationRecordViewVisible(false)
  };

  const onExport = () => {
    const headers = ['房号','姓名','联系电话','预定入驻时间','备注','状态']
    reservationRecordApi.find(form.getFieldsValue()).then(data => {
      if (!data || !data.data || data.data.list.length < 1) {
        messageApi.error('无数据导出')
        return
      }
      const exportData = []
      for (const d of data.data.list) {
        exportData.push([d.roomNumber, d.name, d.phone, d.checkInTime, d.remark, getReservationRecordStatusText(d.status)])
      }
      exportToExcel(headers, exportData)
    })
  }

  useEffect(() => {
    onSearch();

    return () => {
    };
  }, []);

  return (
    <div className="reservationRecordList">
      {messageContextHolder}
      {modalContextHolder}
      <Breadcrumb items={breadcrumbsItems} style={{marginBottom: 'var(--container-margin)'}} />
      <Form form={form} onFinish={onFinish} layout={"inline"}>
        <Form.Item name="roomNumber" label="房号">
          <Input.Search placeholder="请选择房号" onSearch={findRoom} readOnly={true} />
        </Form.Item>
        <Form.Item name="name" label="姓名">
          <Input maxLength={64} placeholder="请输入姓名"/>
        </Form.Item>
        <Form.Item name="phone" label="联系电话">
          <Input maxLength={20} placeholder="请输入联系电话"/>
        </Form.Item>
        <Form.Item name="status" label="状态">
          <Select placeholder="请选择状态" options={[
            { value: 10, label: <span>已预定</span> },
            { value: 20, label: <span>已入驻</span> },
            { value: 30, label: <span>已取消</span> }
          ]} style={{width: 'var(--select-width)'}} />
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" htmlType="submit">查询</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button onClick={onReset}>重置</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" onClick={onAdd}>新增</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" onClick={onExport}>导出</Button>
        </Form.Item>
      </Form>
      <Table<ReservationRecord> columns={columns} dataSource={data} size="small" rowKey={record => record.id} pagination={{ position: ["bottomCenter"] }} style={{marginTop: 'var(--container-margin)'}} />
      <RoomSelector visible={roomSelectorVisible} onRoomSelected={handleRoomSelected} onCloseRoomSelector={handleCloseRoomSelector} />
      <ReservationRecordAdd visible={reservationRecordAddVisible} onCloseReservationRecordAdd={handleCloseReservationRecordAdd} id={selectedReservationRecordId} />
      <ReservationRecordView visible={reservationRecordViewVisible} onCloseReservationRecordView={handleCloseReservationRecordView} viewRow={selectedReservationRecord} />
    </div>
  );
};

export default ReservationRecordList;

// v2_el/src/views/reservationRecord/ReservationRecordList.vue
<template>
  <div class="reservation-record-list">
    <div class="breadcrumb">
      <el-breadcrumb separator="/">
        <el-breadcrumb-item to="Home" :replace="true">首页</el-breadcrumb-item>
        <el-breadcrumb-item>预定记录列表</el-breadcrumb-item>
      </el-breadcrumb>
    </div>
    <el-form :inline="true" :model="searchParams">
      <el-form-item label="房号" prop="roomNumber">
        <el-input v-model="searchParams.roomNumber" placeholder="请选择房号" readonly="readonly">
          <i slot="suffix" class="el-input__icon el-icon-search" @click="findRoom"></i>
        </el-input>
      </el-form-item>
      <el-form-item label="姓名">
        <el-input v-model="searchParams.name" placeholder="请输入姓名" maxlength="64"></el-input>
      </el-form-item>
      <el-form-item label="联系电话">
        <el-input v-model="searchParams.phone" placeholder="请输入联系电话" maxlength="20"></el-input>
      </el-form-item>
      <el-form-item label="状态" prop="status">
        <el-select v-model="searchParams.status" placeholder="请选择状态">
          <el-option label="已预定" :value="10"></el-option>
          <el-option label="已入驻" :value="20"></el-option>
          <el-option label="已取消" :value="30"></el-option>
        </el-select>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="onSearch">查询</el-button>
        <el-button @click="onReset">重置</el-button>
        <el-button type="primary" @click="onAdd">新增</el-button>
        <el-button type="primary" @click="onExport">导出</el-button>
      </el-form-item>
    </el-form>

    <el-table
      :data="pageData.list"
      border
      v-loading="pageData.loading"
      size="mini"
      header-cell-class-name="table-header-cell-font"
      cell-class-name="table-cell-font">
      <el-table-column prop="roomNumber" label="房号"></el-table-column>
      <el-table-column prop="name" label="姓名"></el-table-column>
      <el-table-column prop="phone" label="联系电话"></el-table-column>
      <el-table-column prop="checkInTime" label="预定入驻时间"></el-table-column>
      <el-table-column prop="remark" label="备注"></el-table-column>
      <el-table-column prop="status" label="状态">
        <template v-slot="{ row }">
          <div v-if="row.status === 10">已预定</div>
          <div v-if="row.status === 20">已入驻</div>
          <div v-if="row.status === 30">已取消</div>
        </template>
      </el-table-column>
      <el-table-column fixed="right" label="操作" width="250">
        <template v-slot="{ row }">
          <el-button @click.native.prevent="editRow(row.id)" type="primary">编辑</el-button>
          <el-button @click.native.prevent="delRow(row.id)" type="danger" plain>删除</el-button>
          <el-button @click.native.prevent="detailRow(row.id)" type="primary" plain>详情</el-button>
        </template>
      </el-table-column>
    </el-table>
    <div class="table-pagination">
      <el-pagination
        @current-change="paginationChange"
        :current-page="pageData.current"
        :page-sizes="pageData.pageSizes"
        :page-size="pageData.size"
        background
        layout="total, prev, pager, next, jumper"
        :total="pageData.count">
      </el-pagination>
    </div>
    <el-dialog :visible.sync="roomSelectorVisible" v-if="roomSelectorVisible" title="房间选择器(双击行选中)" :top="dialogTop" :width="dialogWidth">
      <room-selector @room-selected-event="handleRoomSelectedEvent">
      </room-selector>
    </el-dialog>
    <el-dialog :visible.sync="reservationRecordAddVisible" v-if="reservationRecordAddVisible" :title="reservationRecordAddTitle" :top="dialogTop" :width="dialogWidth" :modal-append-to-body="true">
      <reservation-record-add :id="selectedReservationRecordId" @close-reservation-record-add-event="handleCloseReservationRecordAddEvent" @reset-reservation-record-add-event="handleResetReservationRecordAddEvent">
      </reservation-record-add>
    </el-dialog>
    <el-dialog :visible.sync="reservationRecordViewVisible" v-if="reservationRecordViewVisible" title="预定记录详情" :top="dialogTop" :width="dialogWidth">
      <reservation-record-view :id="selectedReservationRecordId" @close-reservation-record-view-event="handleCloseReservationRecordViewEvent">
      </reservation-record-view>
    </el-dialog>
  </div>
</template>

<script>
import reservationRecordApi from '@/api/reservationRecordApi'
import RoomSelector from "@/views/room/RoomSelector.vue";
import ReservationRecordAdd from "@/views/reservationRecord/ReservationRecordAdd.vue"
import ReservationRecordView from "@/views/reservationRecord/ReservationRecordView.vue"
import listQueryMixin from '@/mixins/listQueryMixin'
import {getReservationRecordStatusText} from "@/utils/dictTranslator";

export default {
  name: 'ReservationRecordList',
  components: {RoomSelector,ReservationRecordAdd, ReservationRecordView},
  mixins: [
    listQueryMixin
  ],
  data () {
    return {
      searchParams: {
        roomId: '',
        roomNumber: '',
        name: '',
        phone: '',
        status: ''
      },
      roomSelectorVisible: false,
      reservationRecordAddVisible: false,
      reservationRecordAddTitle: '',
      reservationRecordViewVisible: false,
      selectedReservationRecordId: 0
    }
  },
  methods: {
    getPageData (p) {
      return reservationRecordApi.find(p)
    },
    onSearch () {
      this._getPageData()
    },
    onReset () {
      this.searchParams = {
        roomId: '',
        roomNumber: '',
        name: '',
        phone: '',
        status: ''
      }
      this.pageData.pageIndex = 1
      this._getPageData()
    },
    onAdd () {
      this.selectedReservationRecordId = ''
      this.reservationRecordAddVisible = true
      this.reservationRecordAddTitle = '预定记录新增'
    },
    onExport () {
      const headers = ['房号','姓名','联系电话','预定入驻时间','备注','状态']
      const params = Object.assign(this.getPaginationParams(), this.searchParams)
      this.getPageData(params).then(data => {
        if (!data || !data.data || data.data.list.length < 1) {
          this.$message.error('无数据导出')
          return
        }
        const exportData = []
        for (const d of data.data.list) {
          exportData.push([d.roomNumber, d.name, d.phone, d.checkInTime, d.remark, getReservationRecordStatusText(d.status)])
        }
        this.exportToExcel(headers, exportData)
      })
    },
    editRow (id) {
      this.selectedReservationRecordId = id
      this.reservationRecordAddVisible = true
      this.reservationRecordAddTitle = '预定记录编辑'
    },
    delRow (id) {
      if (!id) {
        return
      }
      this.$confirm('确定要删除吗?', '删除提示', {
        confirmButtonText: '确定',
        cancelButtonText: '取消',
        type: 'warning'
      }).then(() => {
        reservationRecordApi.del(id)
          .then((resp) => {
            if (resp && resp.code === 1) {
              this.$message.success('删除成功!')
              this.onSearch()
            } else {
              this.$message.error('删除失败:' + (resp.msg ? resp.msg : '原因未知'))
            }
          })
          .catch(error => {
            console.error('删除数据失败:', error)
          })
      }).catch(() => {})
    },
    detailRow (id) {
      this.selectedReservationRecordId = id
      this.reservationRecordViewVisible = true
    },
    findRoom () {
      this.roomSelectorVisible = true
    },
    handleRoomSelectedEvent (selectedRoom) {
      this.roomSelectorVisible = false
      if (selectedRoom && 'roomId' in selectedRoom && this.searchParams.roomId !== selectedRoom['roomId']) {
        this.searchParams.roomId = selectedRoom['roomId']
        this.searchParams.roomNumber = selectedRoom['roomNumber']
      }
    },
    handleCloseReservationRecordViewEvent () {
      this.reservationRecordViewVisible = false
    },
    handleResetReservationRecordAddEvent () {
      this.reservationRecordAddTitle = '预定记录新增'
    },
    handleCloseReservationRecordAddEvent (params) {
      if (params && params.search) {
        this.onSearch()
      }
      this.reservationRecordAddVisible = false
    }
  }
}
</script>

<style lang="scss">
</style>
