// angular_ngzorro/src/app/reservation-record/reservation-record-add.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {ReservationRecordService} from '../../service/reservation-record.service';
import {SharedModule} from '../shared.module';
import {ReservationRecordForm} from '../../types/req/ReservationRecordForm';
import {MODAL_WIDTH} from '../../const'
import {RoomSelectorComponent} from '../room/room-selector.component';

@Component({
  selector: 'reservation-record-add',
  imports: [
    RoomSelectorComponent,
    SharedModule
  ],
  templateUrl: './reservation-record-add.component.html',
  standalone: true
})
export class ReservationRecordAddComponent implements OnInit {
  reservationRecordToSave:ReservationRecordForm = {};
  reservationRecordForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增预定记录'
  modalWidth: string = MODAL_WIDTH

  @ViewChild(RoomSelectorComponent, { static: false }) roomSelectorComponent!: RoomSelectorComponent;

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private reservationRecordService: ReservationRecordService
  ) {}

  ngOnInit(): void {
    this.reservationRecordForm = this.fb.group({
      roomId: [0],
      roomNumber: ['', [Validators.required]],
      name: ['', [Validators.required]],
      phone: [''],
      checkInTime: [''],
      remark: [''],
      status: [undefined],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.reservationRecordForm.controls) {
        this.reservationRecordForm.controls[i].markAsDirty();
        this.reservationRecordForm.controls[i].updateValueAndValidity();
      }
      if (!this.reservationRecordForm.valid) {
        this.saveLoading = false
        return
      }
      this.reservationRecordService.save(Object.assign(this.reservationRecordToSave, this.reservationRecordForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增预定记录'.slice()
    this.reservationRecordForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改预定记录'
      this.saveLoading = true
      this.reservationRecordService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.reservationRecordToSave = resp.data
            this.reservationRecordForm.patchValue(this.reservationRecordToSave);
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }

  findRoom() {
    this.roomSelectorComponent.display()
  }

  handleRoomSelectedEvent(selectedRoom: { roomId?: number; roomNumber?: string; }) {
    if (selectedRoom && 'roomId' in selectedRoom) {
      this.reservationRecordForm.patchValue(selectedRoom);
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="reservationRecordForm" (keydown.enter)="$event.preventDefault()">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomNumber" nzRequired>房号</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择房号'">
              <nz-input-group nzSearch [nzAddOnAfter]="roomNumberSuffixIconButton">
                <input nz-input formControlName="roomNumber" placeholder="请选择房号" readonly />
              </nz-input-group>
              <ng-template #roomNumberSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findRoom()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name" nzRequired>姓名</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入姓名'">
              <input nz-input formControlName="name" placeholder="请输入姓名" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="phone">联系电话</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="phone" placeholder="请输入联系电话" maxlength="20"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="checkInTime">预定入驻时间</nz-form-label>
            <nz-form-control >
              <nz-date-picker nzShowTime formControlName="checkInTime" nzFormat="yyyy-MM-dd HH:mm:ss"></nz-date-picker>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="remark">备注</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="remark" placeholder="请输入备注" maxlength="255"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="status">状态</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="status">
                <nz-option nzLabel="已预定" [nzValue]="10"></nz-option>
                <nz-option nzLabel="已入驻" [nzValue]="20"></nz-option>
                <nz-option nzLabel="已取消" [nzValue]="30"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
<room-selector (roomSelectedEvent)="handleRoomSelectedEvent($event)"></room-selector>

// v2_el/src/views/reservationRecord/ReservationRecordAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="reservationRecordForm" :label-width="formLabelWidth" ref="refReservationRecordForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="房号" prop="roomNumber">
            <el-input v-model="reservationRecordForm.roomNumber" placeholder="请选择房号" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findRoom"></i>
            </el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="姓名" prop="name">
            <el-input v-model="reservationRecordForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="联系电话" prop="phone">
            <el-input v-model="reservationRecordForm.phone" placeholder="请输入联系电话" maxlength="20"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="预定入驻时间" prop="checkInTime">
            <el-date-picker
                v-model="reservationRecordForm.checkInTime" type="datetime" placeholder="预定入驻时间" value-format="yyyy-MM-dd HH:mm:ss">
            </el-date-picker>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="备注" prop="remark">
            <el-input v-model="reservationRecordForm.remark" placeholder="请输入备注" maxlength="255"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="状态" prop="status">
            <el-select v-model="reservationRecordForm.status" placeholder="请选择状态">
              <el-option label="已预定" :value="10"></el-option>
              <el-option label="已入驻" :value="20"></el-option>
              <el-option label="已取消" :value="30"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button type="primary" @click="onReset" plain>重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="roomSelectorVisible" v-if="roomSelectorVisible" title="房间选择器(双击行选中)" :top="dialogTop" :width="dialogWidth">
      <room-selector @room-selected-event="handleRoomSelectedEvent">
      </room-selector>
    </el-dialog>
  </div>
</template>

<script>
import reservationRecordApi from '@/api/reservationRecordApi'
import RoomSelector from "@/views/room/RoomSelector.vue";
export default {
  name: 'ReservationRecordAdd',
  components: {RoomSelector,},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      reservationRecordForm: {
        roomId: '',
        roomNumber: '',
        name: '',
        phone: '',
        checkInTime: '',
        remark: '',
        status: ''
      },
      rules: {
        roomNumber:[
          { required: true, message: '请输入房号', trigger: 'blur' }
        ],
        name:[
          { required: true, message: '请输入姓名', trigger: 'blur' }
        ],
      },
      roomSelectorVisible: false,
    }
  },
  created () {
    if (this.id) {
      reservationRecordApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.reservationRecordForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.reservationRecordForm = {
        roomId: '',
        roomNumber: '',
        name: '',
        phone: '',
        checkInTime: '',
        remark: '',
        status: ''
      }
      this.$emit('reset-reservation-record-add-event')
    },
    onSave () {
      this.$refs.refReservationRecordForm.validate((valid) => {
        if (valid) {
          reservationRecordApi.save(this.reservationRecordForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-reservation-record-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    findRoom () {
      this.roomSelectorVisible = true
    },
    handleRoomSelectedEvent (selectedRoom) {
      this.roomSelectorVisible = false
      if (selectedRoom && 'roomId' in selectedRoom && this.searchParams.roomId !== selectedRoom['roomId']) {
        this.searchParams.roomId = selectedRoom['roomId']
        this.searchParams.roomNumber = selectedRoom['roomNumber']
      }
    },
    onBack () {
      this.$emit('close-reservation-record-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>
