// v3_el/src/views/checkInRecordDetail/CheckInRecordDetailView.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="checkInRecordDetailForm" :label-width="formLabelWidth" disabled="disabled">
      <el-row>
        <el-col :span="11">
          <el-form-item label="姓名">
            <el-input v-model="checkInRecordDetailForm.name"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="联系电话">
            <el-input v-model="checkInRecordDetailForm.phone"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="商品名称">
            <el-input v-model="checkInRecordDetailForm.goodsName"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="价格">
            <el-input v-model="checkInRecordDetailForm.goodsPrice"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="数量">
            <el-input v-model="checkInRecordDetailForm.qty"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="单价">
            <el-input v-model="checkInRecordDetailForm.price"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="总价">
            <el-input v-model="checkInRecordDetailForm.amount"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="创建时间">
            <el-input v-model="checkInRecordDetailForm.createTime"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="12" :offset="6">
          <div class="form-button-container">
            <el-button @click="onBack" type="primary">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script setup lang="ts">
import {defineEmits, defineProps, onMounted, reactive, ref, inject, toRefs} from 'vue';
import checkInRecordDetailApi from '@/api/checkInRecordDetailApi'
import type {CheckInRecordDetail} from "@/types/resp/checkInRecordDetail";
import type {Id} from "@/types/id"

const checkInRecordDetailForm = reactive<Partial<CheckInRecordDetail>>({});
const props = defineProps<Id>()
const emit = defineEmits<{
  (e: 'closeCheckInRecordDetailViewEvent'): void;
}>()
const formLabelWidth = ref<string>('')

onMounted(() => {
  initCheckInRecordDetailById(props.id)
  const globalState = inject('globalState', {} as { formLabelWidth?: string })
  if (!globalState) {
    throw new Error('globalState is not provided');
  }
  const globalStateRefs = toRefs(globalState)
  if (globalStateRefs.formLabelWidth) {
    formLabelWidth.value = globalStateRefs.formLabelWidth.value || ''
  }
})

const initCheckInRecordDetailById = async (id: number) => {
  const resp = await checkInRecordDetailApi.findById(id)
  if (resp && resp.code === 1 && resp.data) {
    Object.assign(checkInRecordDetailForm, resp.data)
  }
}
const onBack = () => {
  emit('closeCheckInRecordDetailViewEvent')
}
</script>

<style lang="scss">
</style>

// react_antd/src/pages/checkInRecordDetail/CheckInRecordDetailView.tsx
import React, {useEffect} from "react";
import {Button, Col, Form, Input, Modal, Row} from "antd";
import {CheckInRecordDetail} from "@/types/resp/checkInRecordDetail";

interface CheckInRecordDetailViewProps {
  visible: boolean;
  viewRow: object;
  onCloseCheckInRecordDetailView: () => void;
}

const CheckInRecordDetailView: React.FC<CheckInRecordDetailViewProps> = ({visible, viewRow, onCloseCheckInRecordDetailView}) => {

  const [form] = Form.useForm<CheckInRecordDetail>();

  const onBack = () => {
    onCloseCheckInRecordDetailView()
  };

  useEffect(() => {
    if (!visible) {
      return
    }
    if (viewRow) {
      form.setFieldsValue(viewRow);
    }
  }, [viewRow]);

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onBack}>关闭</Button>
    </div>
  );

  return (
    <Modal title={"入住消费商品详情"} open={visible} onCancel={onCloseCheckInRecordDetailView}
        width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={form} labelCol={{span: 6}} disabled={true}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="name" label="姓名">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="phone" label="联系电话">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="goodsName" label="商品名称">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="goodsPrice" label="价格">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="qty" label="数量">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="price" label="单价">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="amount" label="总价">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="createTime" label="创建时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default CheckInRecordDetailView;
