// angular_ngzorro/src/app/check-in-record-detail/check-in-record-detail-view.component.ts
import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {SharedModule} from '../shared.module';
import {MODAL_WIDTH} from '../../const'
import {CheckInRecordDetail} from '../../types/resp/CheckInRecordDetail';

@Component({
  selector: 'check-in-record-detail-view',
  imports: [
    SharedModule
  ],
  templateUrl: './check-in-record-detail-view.component.html',
  standalone: true
})
export class CheckInRecordDetailViewComponent implements OnInit {
  checkInRecordDetailForm!: FormGroup;
  isVisible: boolean = false
  title: string = '入住消费商品详情'
  modalWidth: string = MODAL_WIDTH

  constructor(
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.checkInRecordDetailForm = this.fb.group({
      name: [''],
      phone: [''],
      goodsName: [''],
      goodsPrice: [0],
      qty: [0],
      price: [0],
      amount: [0],
      createTime: [''],
    })
  }

  onBack() {
    this.isVisible = false
  }

  display(checkInRecordDetail: CheckInRecordDetail) {
    this.isVisible = true
    this.checkInRecordDetailForm.patchValue(checkInRecordDetail);
    this.checkInRecordDetailForm.disable();
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="checkInRecordDetailForm">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name">入住人员姓名</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="name" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="phone">入住人员联系电话</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="phone" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="goodsName">商品名称</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="goodsName" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="goodsPrice">商品价格</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="goodsPrice" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="qty">数量</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="qty" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="price">单价</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="price" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="amount">总价</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="amount" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="createTime">创建时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="createTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>

// react_antd/src/pages/checkInRecordDetail/CheckInRecordDetailView.tsx
import React, {useEffect} from "react";
import {Button, Col, Form, Input, Modal, Row} from "antd";
import {CheckInRecordDetail} from "@/types/resp/checkInRecordDetail";

interface CheckInRecordDetailViewProps {
  visible: boolean;
  viewRow: object;
  onCloseCheckInRecordDetailView: () => void;
}

const CheckInRecordDetailView: React.FC<CheckInRecordDetailViewProps> = ({visible, viewRow, onCloseCheckInRecordDetailView}) => {

  const [form] = Form.useForm<CheckInRecordDetail>();

  const onBack = () => {
    onCloseCheckInRecordDetailView()
  };

  useEffect(() => {
    if (!visible) {
      return
    }
    if (viewRow) {
      form.setFieldsValue(viewRow);
    }
  }, [viewRow]);

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onBack}>关闭</Button>
    </div>
  );

  return (
    <Modal title={"入住消费商品详情"} open={visible} onCancel={onCloseCheckInRecordDetailView}
        width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={form} labelCol={{span: 6}} disabled={true}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="name" label="姓名">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="phone" label="联系电话">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="goodsName" label="商品名称">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="goodsPrice" label="价格">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="qty" label="数量">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="price" label="单价">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="amount" label="总价">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="createTime" label="创建时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default CheckInRecordDetailView;
