// react_antd/src/pages/chart/ChartList.tsx
import React, {useEffect} from "react";
import * as echarts from 'echarts';
import {Col, Row} from "antd";

const ChartList: React.FC = () => {

  const displayChart1 = () => {
    const chart1 = echarts.init(document.getElementById('chart1'));
    const option1 = {
      xAxis: {
        type: 'category',
        data: ['软件工程', '会计学', '汉语言文学', '应用数学', '心理学', '电子信息', '智能建造'],
        axisLabel: {
          rotate: 45
        }
      },
      yAxis: {
        type: 'value'
      },
      series: [
        {
          data: [120, 200, 150, 80, 70, 110, 130],
          type: 'bar'
        }
      ]
    };

    chart1.setOption(option1);
  }

  const displayChart2 = () => {
    const chart2 = echarts.init(document.getElementById('chart2'));
    const option2 = {
      title: {
        text: '考勤数据',
        subtext: '仅供参考',
        left: 'center'
      },
      tooltip: {
        trigger: 'item'
      },
      legend: {
        orient: 'vertical',
        left: 'left'
      },
      series: [
        {
          name: '考勤数据',
          type: 'pie',
          radius: '50%',
          data: [
            { value: 235, name: '出勤' },
            { value: 6, name: '缺勤' },
            { value: 25, name: '迟到' }
          ],
          emphasis: {
            itemStyle: {
              shadowBlur: 10,
              shadowOffsetX: 0,
              shadowColor: 'rgba(0, 0, 0, 0.5)'
            }
          }
        }
      ]
    };

    chart2.setOption(option2);
  }

  useEffect(() => {
    displayChart1()
    displayChart2()
    return () => {
    };
  }, []);

  return (
    <>
      <Row gutter={10}>
        <Col span={11}>
          <div id="chart1" style={{height: 400, width: "100%"}}></div>
        </Col>
        <Col span={11}>
          <div id="chart2" style={{height: 400, width: "100%"}}></div>
        </Col>
      </Row>
    </>
  );
};

export default ChartList;

// v3_el/src/views/chart/ChartList.vue
<template>
  <div>
    <el-row>
      <el-col :span="12">
        <div id="chart1" style="height: 400px; width: 100%;"></div>
      </el-col>
      <el-col :span="12">
        <div id="chart2" style="height: 400px; width: 100%;"></div>
      </el-col>
    </el-row>
  </div>
</template>

<script setup lang="ts">
import * as echarts from 'echarts';
import {onMounted} from "vue";

onMounted(() => {
  displayChart1()
  displayChart2()
})

const displayChart1 = () => {
  const chartDom = document.getElementById('chart1');
  const myChart = echarts.init(chartDom);
  const option = {
    title: {
      text: '销售额',
      subtext: '2010',
      left: 'center',
      top: 'top',
      textStyle: {
        fontSize: 20
      },
      subtextStyle: {
        fontSize: 14
      }
    },
    xAxis: {
      type: 'category',
      data: ['1月', '2月', '3月', '4月', '5月', '6月', '7月'],
      axisLabel: {
        rotate: 45
      }
    },
    yAxis: {
      type: 'value'
    },
    series: [
      {
        data: [12320, 14300, 15550, 8230, 7530, 11220, 13130],
        type: 'bar'
      }
    ]
  };

  myChart.setOption(option);
}

const displayChart2 = () => {
  const chartDom = document.getElementById('chart2');
  const myChart = echarts.init(chartDom);
  const option = {
    title: {
      text: '入驻比例',
      subtext: '2010-07',
      left: 'center'
    },
    tooltip: {
      trigger: 'item'
    },
    legend: {
      orient: 'vertical',
      left: 'left'
    },
    series: [
      {
        name: '考勤数据',
        type: 'pie',
        radius: '50%',
        data: [
          { value: 24, name: '标准单人间' },
          { value: 6, name: '豪华单人间' },
          { value: 55, name: '标准双人间' },
          { value: 9, name: '豪华双人间' },
          { value: 4, name: '标准套房' },
          { value: 2, name: '豪华套房' }
        ],
        emphasis: {
          itemStyle: {
            shadowBlur: 10,
            shadowOffsetX: 0,
            shadowColor: 'rgba(0, 0, 0, 0.5)'
          }
        }
      }
    ]
  };

  myChart.setOption(option);
}
</script>

<style lang="scss">
</style>
