// v3_el/src/views/Home.vue
<template>
  <div class="home">
    <div class="home-container">{{ $t('welcomeMessage') }}</div>
    <div class="home-container">{{ $t('ad1')}}</div>
    <div class="home-container">{{ $t('ad2')}}</div>
    <div class="home-container">{{ $t('ad3')}}</div>
    <div class="home-container"><img src="../assets/weixinqrcode_small.jpg" :alt="$t('weixinAlt')"/></div>
  </div>
</template>

<script setup lang="ts">
</script>

<style scoped>
.home-container{
  width: 100%;
  display: flex;
  justify-content: center;
  font-size: 22px;
  margin: 10px auto 0;
}
</style>

// angular_ngzorro/src/app/home/home.component.ts
import {Component} from '@angular/core';
import {ad1, ad2, ad3, WEIXIN_ALT, WELCOME_MESSAGE} from '../../const';
import {environment} from '../../environments/environment';

@Component({
  selector: 'app-home',
  imports: [
  ],
  templateUrl: './home.component.html',
  standalone: true,
  styleUrl: './home.component.less'
})
export class HomeComponent {
  welcomeMessage: string = WELCOME_MESSAGE
  ad1: string = ad1
  ad2: string = ad2
  ad3: string = ad3
  weixinAlt: string = WEIXIN_ALT
  imagePath = `${environment.deployUrl}assets/weixinqrcode_small.jpg`
}

<div class="home">{{ welcomeMessage }}</div>
<div class="home">{{ ad1 }}</div>
<div class="home">{{ ad2 }}</div>
<div class="home">{{ ad3 }}</div>
<div class="home"><img [src]="imagePath" [alt]="weixinAlt"/></div>
