// react_antd/src/pages/roomMaintenanceRecord/RoomMaintenanceRecordView.tsx
import React, {useEffect} from "react";
import {Button, Col, DatePicker, Form, Input, Modal, Row} from "antd";
import {RoomMaintenanceRecord} from "@/types/resp/roomMaintenanceRecord";

interface RoomMaintenanceRecordViewProps {
  visible: boolean;
  viewRow: object;
  onCloseRoomMaintenanceRecordView: () => void;
}

const RoomMaintenanceRecordView: React.FC<RoomMaintenanceRecordViewProps> = ({visible, viewRow, onCloseRoomMaintenanceRecordView}) => {

  const [form] = Form.useForm<RoomMaintenanceRecord>();

  const onBack = () => {
    onCloseRoomMaintenanceRecordView()
  };

  useEffect(() => {
    if (!visible) {
      return
    }
    if (viewRow) {
      form.setFieldsValue(viewRow);
    }
  }, [viewRow]);

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onBack}>关闭</Button>
    </div>
  );

  return (
    <Modal title={"房间维护记录详情"} open={visible} onCancel={onCloseRoomMaintenanceRecordView}
        width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={form} labelCol={{span: 6}} disabled={true}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="roomNumber" label="房号">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="staffName" label="员工姓名">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="staffPhone" label="员工联系电话">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="startTime" label="开始时间">
              <DatePicker showTime={true}/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="endTime" label="结束时间">
              <DatePicker showTime={true}/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="content" label="维护内容">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="createTime" label="创建时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default RoomMaintenanceRecordView;

// angular_ngzorro/src/app/room-maintenance-record/room-maintenance-record-view.component.ts
import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {SharedModule} from '../shared.module';
import {MODAL_WIDTH} from '../../const'
import {RoomMaintenanceRecord} from '../../types/resp/RoomMaintenanceRecord';

@Component({
  selector: 'room-maintenance-record-view',
  imports: [
    SharedModule
  ],
  templateUrl: './room-maintenance-record-view.component.html',
  standalone: true
})
export class RoomMaintenanceRecordViewComponent implements OnInit {
  roomMaintenanceRecordForm!: FormGroup;
  isVisible: boolean = false
  title: string = '房间维护记录详情'
  modalWidth: string = MODAL_WIDTH

  constructor(
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.roomMaintenanceRecordForm = this.fb.group({
      roomNumber: [''],
      staffName: [''],
      staffPhone: [''],
      startTime: [''],
      endTime: [''],
      content: [''],
      createTime: [''],
    })
  }

  onBack() {
    this.isVisible = false
  }

  display(roomMaintenanceRecord: RoomMaintenanceRecord) {
    this.isVisible = true
    this.roomMaintenanceRecordForm.patchValue(roomMaintenanceRecord);
    this.roomMaintenanceRecordForm.disable();
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="roomMaintenanceRecordForm">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomNumber">房号</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="roomNumber" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="staffName">员工姓名</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="staffName" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="staffPhone">员工联系电话</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="staffPhone" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="startTime">开始时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="startTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="endTime">结束时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="endTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="content">维护内容</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="content" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="createTime">创建时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="createTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
