// react_antd/src/pages/goods/GoodsAdd.tsx
import React, {useEffect, useState} from "react";
import {Button, Col, Form, Input, InputNumber, message, Modal, Row} from "antd";
import type {Result} from "@/types/result";
import goodsApi from "@/api/goodsApi.ts";
import {Goods} from "@/types/resp/goods";

interface GoodsAddProps {
  visible: boolean;
  id: number;
  onCloseGoodsAdd: () => void;
}

const GoodsAdd: React.FC<GoodsAddProps> = ({visible, id, onCloseGoodsAdd}) => {

  const [form] = Form.useForm<Goods>();
  const [messageApi, messageContextHolder] = message.useMessage();

  const rules = {
    name: [
      { required: true, message: '请输入商品名称' }
    ],
    price: [
      { required: true, message: '请输入价格' }
    ],
  };

  let goodsForm: Partial<Goods> = {}

  const [title, setTitle] = useState('新增商品');

  useEffect(() => {
    if (!visible) {
      return
    }
    if (id) {
      setTitle('编辑商品')
      initGoodsFormById(id)
    } else {
      setTitle('新增商品')
      form.resetFields();
    }
  }, [visible]);

  const initGoodsFormById = async (id: number) => {
    const resp: Result<Goods> = await goodsApi.findById(id)
    if (resp && resp.code === 1 && resp.data) {
      goodsForm = resp.data
      form.setFieldsValue(resp.data);
    }
  }

  const onSave = async () => {
    try {
      await form.validateFields()

      let goods2Save:Goods = form.getFieldsValue()
      if (id) {
        goods2Save = Object.assign(goodsForm, goods2Save)
      }
      const resp: Result<void> = await goodsApi.save(goods2Save);
      if (!resp || resp.code !== 1) {
        messageApi.error('保存失败:' + (resp.msg ? resp.msg : '未知异常'));
        return
      }
      messageApi.success('保存成功');
      onBack()
    } catch (error) {
      console.error('There was an error submitting the form!', error);
    }
  };

  const onReset = () => {
    setTitle('新增商品')
    form.resetFields();
  };
  

  const onBack = () => {
    onCloseGoodsAdd()
  };

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onSave}>保存</Button>
      <Button onClick={onReset} style={{marginLeft: 'var(--button-margin-left)'}}>重置</Button>
      <Button type="primary" onClick={onBack} style={{marginLeft: 'var(--button-margin-left)'}}>关闭</Button>
    </div>
  );

  return (
    <Modal title={title} open={visible} onCancel={onCloseGoodsAdd} width={'var(--modal-width)'}
        footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      {messageContextHolder}
      <Form form={form} name="goodsForm" labelCol={{span: 6}}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="name" label="商品名称" rules={rules.name}>
              <Input maxLength={255} placeholder="请输入商品名称"/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="price" label="价格" rules={rules.price}>
              <InputNumber min={1} max={9999} precision={2} step={0.1} />
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default GoodsAdd;

// v3_el/src/views/goods/GoodsAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
      <el-form label-position="right" :model="goodsForm" :label-width="formLabelWidth" ref="goodsFormRef" :rules="rules">
        <el-row>
          <el-col :span="11">
            <el-form-item label="商品名称" prop="name">
              <el-input v-model="goodsForm.name" placeholder="请输入商品名称" maxlength="255"></el-input>
            </el-form-item>
          </el-col>
          <el-col :span="11">
            <el-form-item label="价格" prop="price">
              <el-input-number v-model="goodsForm.price" :precision="2" :step="0.1" :min="1" :max="9999"></el-input-number>
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button @click="onReset">重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script setup lang="ts">
import {defineEmits, defineProps, onMounted, reactive, ref, inject, toRefs} from 'vue';
import goodsApi from '@/api/goodsApi'
import type {FormInstance} from 'element-plus';
import {ElMessage} from 'element-plus'
import type {GoodsForm} from "@/types/req/goodsForm";
import type {Result} from '@/types/result'
import type {Goods} from "@/types/resp/goods";
import type {Id} from "@/types/id";

const props = defineProps<Id>()
const goodsFormRef = ref<FormInstance | null>(null);
let goodsForm = reactive<GoodsForm>({
  name: '',
  price: 0,
})
const emit = defineEmits<{
  (e: 'resetGoodsAddEvent'): void;
  (e: 'closeGoodsAddEvent', data?: { search: boolean }): void;
}>()

const rules = reactive({
  name: [
    { required: true, message: '请输入商品名称', trigger: 'blur' }
  ],
  price: [
    { required: true, message: '请输入价格', trigger: 'blur' }
  ],
});
const formLabelWidth = ref<string>('')

onMounted(() => {
  if (props.id) {
    initGoodsFormById(props.id)
  }
  const globalState = inject('globalState', {} as { formLabelWidth?: string })
  if (!globalState) {
    throw new Error('globalState is not provided');
  }
  const globalStateRefs = toRefs(globalState)
  if (globalStateRefs.formLabelWidth) {
    formLabelWidth.value = globalStateRefs.formLabelWidth.value || ''
  }
});

const initGoodsFormById = async (id: number) => {
  const resp: Result<Goods> = await goodsApi.findById(id)
  if (resp && resp.code === 1 && resp.data) {
    Object.assign(goodsForm, resp.data)
  }
}

const onReset = () => {
  if (goodsFormRef.value) {
    goodsFormRef.value.resetFields()
  }
  emit('resetGoodsAddEvent')
}

const onSave = () => {
  if (!goodsFormRef.value) {
    return
  }
  goodsFormRef.value.validate(async (valid: boolean) => {
    if (valid) {
      const resp: Result<void> = await goodsApi.save(goodsForm)
      if (resp && resp.code === 1) {
        ElMessage.success('保存成功')
        emit('closeGoodsAddEvent', {search: true})
      } else {
        ElMessage.error('保存失败:' + (resp.msg ? resp.msg : ''))
      }
    }
  })
}

const onBack = () => {
  emit('closeGoodsAddEvent')
}
</script>

<style lang="scss">
</style>
