// angular_ngzorro/src/app/room/room-add.component.ts
import {Component, EventEmitter, OnInit, Output} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {RoomService} from '../../service/room.service';
import {SharedModule} from '../shared.module';
import {RoomForm} from '../../types/req/RoomForm';
import {MODAL_WIDTH} from '../../const'

@Component({
  selector: 'room-add',
  imports: [
    SharedModule
  ],
  templateUrl: './room-add.component.html',
  standalone: true
})
export class RoomAddComponent implements OnInit {
  roomToSave:RoomForm = {};
  roomForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增房间'
  modalWidth: string = MODAL_WIDTH

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private roomService: RoomService
  ) {}

  ngOnInit(): void {
    this.roomForm = this.fb.group({
      roomNumber: ['', [Validators.required]],
      roomType: [undefined, [Validators.required]],
      price: [0],
      area: [''],
      floorNumber: [''],
      bedType: [''],
      maxOccupancy: [0],
      freeWifi: [undefined],
      existWindow: [undefined],
      freeBreakfast: [undefined],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.roomForm.controls) {
        this.roomForm.controls[i].markAsDirty();
        this.roomForm.controls[i].updateValueAndValidity();
      }
      if (!this.roomForm.valid) {
        this.saveLoading = false
        return
      }
      this.roomService.save(Object.assign(this.roomToSave, this.roomForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增房间'.slice()
    this.roomForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改房间'
      this.saveLoading = true
      this.roomService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.roomToSave = resp.data
            this.roomForm.patchValue(this.roomToSave);
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="roomForm">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomNumber" nzRequired>房号</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入房号'">
              <input nz-input formControlName="roomNumber" placeholder="请输入房号" maxlength="32"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomType" nzRequired>房型</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择房型'">
              <nz-select formControlName="roomType">
                <nz-option nzLabel="标准单人间" [nzValue]="10"></nz-option>
                <nz-option nzLabel="豪华单人间" [nzValue]="11"></nz-option>
                <nz-option nzLabel="标准双人间" [nzValue]="20"></nz-option>
                <nz-option nzLabel="豪华双人间" [nzValue]="21"></nz-option>
                <nz-option nzLabel="标准套房" [nzValue]="90"></nz-option>
                <nz-option nzLabel="豪华套房" [nzValue]="91"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="price">价格</nz-form-label>
            <nz-form-control>
            <nz-input-number formControlName="price" [nzMin]="1" [nzMax]="99999999" [nzPrecision]="2" [nzStep]="0.1" nzPlaceHolder="Digital" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="area">面积</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="area" placeholder="请输入面积" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="floorNumber">楼层</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="floorNumber" placeholder="请输入楼层" maxlength="32"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="bedType">床型</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="bedType" placeholder="请输入床型" maxlength="50"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="maxOccupancy">入住人数</nz-form-label>
            <nz-form-control>
            <nz-input-number formControlName="maxOccupancy" [nzMin]="1" [nzMax]="10" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="freeWifi">wifi是否免费</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="freeWifi">
                <nz-option nzLabel="否" [nzValue]="0"></nz-option>
                <nz-option nzLabel="是" [nzValue]="1"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="existWindow">是否有窗</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="existWindow">
                <nz-option nzLabel="否" [nzValue]="0"></nz-option>
                <nz-option nzLabel="是" [nzValue]="1"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="freeBreakfast">是否有免费早餐</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="freeBreakfast">
                <nz-option nzLabel="否" [nzValue]="0"></nz-option>
                <nz-option nzLabel="是" [nzValue]="1"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>

// v2_el/src/views/room/RoomAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="roomForm" :label-width="formLabelWidth" ref="refRoomForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="房号" prop="roomNumber">
            <el-input v-model="roomForm.roomNumber" placeholder="请输入房号" maxlength="32"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="房型" prop="roomType">
            <el-select v-model="roomForm.roomType" placeholder="请选择房型">
              <el-option label="标准单人间" :value="10"></el-option>
              <el-option label="豪华单人间" :value="11"></el-option>
              <el-option label="标准双人间" :value="20"></el-option>
              <el-option label="豪华双人间" :value="21"></el-option>
              <el-option label="标准套房" :value="90"></el-option>
              <el-option label="豪华套房" :value="91"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="价格" prop="price">
            <el-input-number v-model="roomForm.price" :precision="2" :step="0.1" :min="1" :max="99999999"></el-input-number>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="面积" prop="area">
            <el-input v-model="roomForm.area" placeholder="请输入面积" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="楼层" prop="floorNumber">
            <el-input v-model="roomForm.floorNumber" placeholder="请输入楼层" maxlength="32"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="床型" prop="bedType">
            <el-input v-model="roomForm.bedType" placeholder="请输入床型" maxlength="50"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="入住人数" prop="maxOccupancy">
            <el-input-number v-model="roomForm.maxOccupancy" :min="1" :max="10"></el-input-number>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="wifi是否免费" prop="freeWifi">
            <el-select v-model="roomForm.freeWifi" placeholder="请选择wifi是否免费">
              <el-option label="否" :value="0"></el-option>
              <el-option label="是" :value="1"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="是否有窗" prop="existWindow">
            <el-select v-model="roomForm.existWindow" placeholder="请选择是否有窗">
              <el-option label="否" :value="0"></el-option>
              <el-option label="是" :value="1"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="是否有免费早餐" prop="freeBreakfast">
            <el-select v-model="roomForm.freeBreakfast" placeholder="请选择是否有免费早餐">
              <el-option label="否" :value="0"></el-option>
              <el-option label="是" :value="1"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button type="primary" @click="onReset" plain>重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script>
import roomApi from '@/api/roomApi'
export default {
  name: 'RoomAdd',
  components: {},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      roomForm: {
        roomNumber: '',
        roomType: '',
        price: '',
        area: '',
        floorNumber: '',
        bedType: '',
        maxOccupancy: '',
        freeWifi: '',
        existWindow: '',
        freeBreakfast: ''
      },
      rules: {
        roomNumber:[
          { required: true, message: '请输入房号', trigger: 'blur' }
        ],
        roomType:[
          { required: true, message: '请输入房型', trigger: 'blur' }
        ],
      },
    }
  },
  created () {
    if (this.id) {
      roomApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.roomForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.roomForm = {
        roomNumber: '',
        roomType: '',
        price: '',
        area: '',
        floorNumber: '',
        bedType: '',
        maxOccupancy: '',
        freeWifi: '',
        existWindow: '',
        freeBreakfast: ''
      }
      this.$emit('reset-room-add-event')
    },
    onSave () {
      this.$refs.refRoomForm.validate((valid) => {
        if (valid) {
          roomApi.save(this.roomForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-room-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    onBack () {
      this.$emit('close-room-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>
