// react_antd/src/pages/staff/StaffSelector.tsx
import React, {useEffect, useState} from 'react';
import {Button, Form, Input, Modal, Table, TableProps} from 'antd';
import type {Staff} from "@/types/resp/staff";
import staffApi from '@/api/staffApi'
import {Result} from "@/types/result";
import {Page} from "@/types/page";


interface StaffSelectorProps {
  visible: boolean;
  onStaffSelected: (selectedStaff: { staffId?: number;staffName?: string;staffPhone?: string; }) => void;
  onCloseStaffSelector: () => void;
}

const StaffSelector: React.FC<StaffSelectorProps> = ({visible, onStaffSelected, onCloseStaffSelector}) => {

  const [staffSelectorForm] = Form.useForm();

  const onFinish = async () => {
    await onSearch()
  };

  const onReset = () => {
    staffSelectorForm.resetFields();
  };

  const [data, setData] = useState<Staff[]>([]);
  const onSearch = async () => {
    try {
      const resp: Result<Page<Staff>> = await staffApi.find(staffSelectorForm.getFieldsValue())
      if (resp && resp.code === 1) {
        if (resp.data) {
          const page: Page<Staff> = resp.data
          if (page && page.list.length > 0) {
            setData(page.list)
          }
        }
      }
    } catch (e) {
      console.log('获取数据异常', e)
    }
  };

  const columns: TableProps<Staff>['columns'] = [
    {title: '姓名', dataIndex: 'name', key: 'name'},
    {title: '联系电话', dataIndex: 'phone', key: 'phone'},
    {title: '岗位', dataIndex: 'position', key: 'position'},
    {title: '特长', dataIndex: 'specialty', key: 'specialty'},
  ];

  const handleRowDoubleClick = (row: Staff) => {
    onStaffSelected({
      staffId: row.id,
      staffName: row.name,
      staffPhone: row.phone,
    })
  };

  const selectorFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onCloseStaffSelector}>关闭</Button>
    </div>
  );

  useEffect(() => {
    if (visible) {
      onSearch();
    }
  }, [visible]);


  return (
    <Modal title={"员工选择器(双击行选中)"} open={visible} onCancel={onCloseStaffSelector}
        width={'var(--modal-width)'} footer={selectorFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={staffSelectorForm} onFinish={onFinish} layout={"inline"}>
        <Form.Item name="name" label="姓名">
          <Input maxLength={64} placeholder="请输入姓名"/>
        </Form.Item>
        <Form.Item name="phone" label="联系电话">
          <Input maxLength={20} placeholder="请输入联系电话"/>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" htmlType="submit">查询</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button onClick={onReset}>重置</Button>
        </Form.Item>
      </Form>
      <Table<Staff> columns={columns} dataSource={data} size="small" rowKey={record => record.id}
                         pagination={{ position: ["bottomCenter"] }}
                         onRow={(row) => ({
                           onDoubleClick: (event) => {
                             event.preventDefault();
                             handleRowDoubleClick(row);
                           },
                         })}/>
    </Modal>
  );
};

export default StaffSelector;

// v2_el/src/views/staff/StaffSelector.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
      <el-form :inline="true" :model="searchParams">
        <el-form-item label="姓名">
            <el-input v-model="searchParams.name" placeholder="请输入姓名" maxlength="64"></el-input>
        </el-form-item>
        <el-form-item label="联系电话">
            <el-input v-model="searchParams.phone" placeholder="请输入联系电话" maxlength="20"></el-input>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="onSearch">查询</el-button>
          <el-button @click="onReset">重置</el-button>
        </el-form-item>
      </el-form>

      <el-table
        :data="pageData.list"
        border
        v-loading="pageData.loading"
        size="mini"
        header-cell-class-name="table-header-cell-font"
        cell-class-name="table-cell-font"
        @row-dblclick="staffSelected">
      <el-table-column prop="name" label="姓名"></el-table-column>
      <el-table-column prop="phone" label="联系电话"></el-table-column>
      <el-table-column prop="position" label="岗位"></el-table-column>
      <el-table-column prop="specialty" label="特长"></el-table-column>
      </el-table>
      <div class="table-pagination">
        <el-pagination
          @current-change="paginationChange"
          :current-page="pageData.current"
          :page-sizes="pageData.pageSizes"
          :page-size="pageData.size"
          background
          layout="total, prev, pager, next, jumper"
          :total="pageData.count">
        </el-pagination>
      </div>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script>
import staffApi from '@/api/staffApi'
import listQueryMixin from '@/mixins/listQueryMixin'
export default {
  name: 'StaffSelector',
  components: {},
  mixins: [
    listQueryMixin
  ],
  data () {
    return {
      searchParams: {
        name: '',
        phone: ''
      },
    }
  },
  methods: {
    getPageData (p) {
      return staffApi.find(p)
    },
    onSearch () {
      this._getPageData()
    },
    onReset () {
      this.searchParams = {
        name: '',
        phone: ''
      }
      this.pageData.pageIndex = 1
      this._getPageData()
    },
    staffSelected (row) {
      this.$emit('staff-selected-event', {
        staffId: row.id,
        staffName: row.name,
        staffPhone: row.phone,
      })
    },
    onBack () {
      this.$emit('staff-selected-event')
    }
  }
}
</script>

<style lang="scss">
</style>
