// angular_ngzorro/src/app/check-in-record/check-in-record-list.component.ts
import {Component, OnInit, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {CheckInRecordService} from '../../service/check-in-record.service';
import {CheckInRecordQueryForm} from '../../types/req/CheckInRecordQueryForm';
import {SharedModule} from '../shared.module';
import {CheckInRecord} from '../../types/resp/CheckInRecord';
import {Page} from '../../types/page';
import {CheckInRecordAddComponent} from './check-in-record-add.component';
import {CheckInRecordViewComponent} from './check-in-record-view.component';
import {NzModalService} from 'ng-zorro-antd/modal';
import {ReservationRecordSelectorComponent} from '../reservation-record/reservation-record-selector.component';
import {RoomSelectorComponent} from '../room/room-selector.component';
import {exportToExcel} from '../../util/exportUtil';
import {getCheckInRecordStatusText} from '../../util/dictTranslator';

@Component({
  selector: 'check-in-record-list',
  imports: [
    ReservationRecordSelectorComponent,
    RoomSelectorComponent,
    CheckInRecordAddComponent,
    CheckInRecordViewComponent,
    SharedModule
  ],
  templateUrl: './check-in-record-list.component.html',
  standalone: true
})
export class CheckInRecordListComponent implements OnInit {
  searchForm!: FormGroup;
  searchLoading: boolean = false
  listOfData: CheckInRecord[] = [];
  total: number = 0

  @ViewChild(ReservationRecordSelectorComponent, { static: false }) reservationRecordSelectorComponent!: ReservationRecordSelectorComponent;
  @ViewChild(RoomSelectorComponent, { static: false }) roomSelectorComponent!: RoomSelectorComponent;
  @ViewChild(CheckInRecordAddComponent, { static: false }) checkInRecordAddComponent!: CheckInRecordAddComponent;
  @ViewChild(CheckInRecordViewComponent, { static: false }) checkInRecordViewComponent!: CheckInRecordViewComponent;

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private checkInRecordService: CheckInRecordService,
    private modal: NzModalService
  ) {}

  ngOnInit(): void {
    this.searchForm = this.fb.group({
      reservationRecordId: [0],
      preName: [''],
      prePhone: [''],
      roomId: [0],
      roomNumber: [''],
      name: [''],
      phone: [''],
      status: [undefined],
    })
    this.onSearch()
  }

  onReset() {
    this.searchForm.reset()
  }

  onSearch() {
    try {
      this.searchLoading = true
      this.checkInRecordService.find(new CheckInRecordQueryForm(this.searchForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          const page: Page<CheckInRecord> | undefined = resp.data
          if (page && page.list.length > 0) {
            this.listOfData = page.list
            this.total = page.total
          }
        },
        complete: () => {
          this.searchLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onAdd() {
    this.checkInRecordAddComponent.display(0)
  }

  onExport() {
    try {
      const headers = ['预定人员姓名', '预定人员联系电话', '房号', '姓名', '联系电话', '入驻时间', '退房时间', '房费', '商品消费', '总金额', '备注', '状态']
      this.searchLoading = true
      this.checkInRecordService.find(new CheckInRecordQueryForm(this.searchForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1 || !resp.data || resp.data.list.length < 1) {
            this.message.error('无数据导出')
            return
          }
          const exportData = []
          for (const d of resp.data.list) {
            exportData.push([d.preName, d.prePhone, d.roomNumber, d.name, d.phone, d.checkInTime,
              d.checkOutTime, d.roomAmount, d.goodsAmount, d.amount, d.remark, getCheckInRecordStatusText(d.status)])
          }
          exportToExcel(headers, exportData)
        },
        complete: () => {
          this.searchLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  editRow(id: number) {
    this.checkInRecordAddComponent.display(id)
  }

  delRow(id: number) {
    this.modal.confirm({
      nzTitle: '<i>删除提示</i>',
      nzContent: '<b>确定要删除吗?</b>',
      nzOnOk: () => {
        this.checkInRecordService.del(id).subscribe({
          next: (resp) => {
            if (resp && resp.code === 1) {
              this.message.success('删除成功!')
              this.onSearch()
            } else {
              this.message.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
            }
          },
          complete: () => {
            this.searchLoading = false
          }
        })
      }
    });
  }

  detailRow(record: CheckInRecord) {
    this.checkInRecordViewComponent.display(record)
  }

  findReservationRecord() {
    this.reservationRecordSelectorComponent.display()
  }

  handleReservationRecordSelectedEvent(selectedReservationRecord: { reservationRecordId?: number; preName?: string;prePhone?: string; }) {
    if (selectedReservationRecord && 'reservationRecordId' in selectedReservationRecord) {
      this.searchForm.patchValue(selectedReservationRecord);
    }
  }

  findRoom() {
    this.roomSelectorComponent.display()
  }

  handleRoomSelectedEvent(selectedRoom: { roomId?: number; roomNumber?: string; }) {
    if (selectedRoom && 'roomId' in selectedRoom) {
      this.searchForm.patchValue(selectedRoom);
    }
  }

  onAdded(addedFlag: boolean) {
    if (addedFlag) {
      this.onSearch()
    }
  }
}

<nz-breadcrumb class="breadcrumb">
  <nz-breadcrumb-item>
    <a>首页</a>
  </nz-breadcrumb-item>
  <nz-breadcrumb-item>入住记录列表</nz-breadcrumb-item>
</nz-breadcrumb>
<form nz-form class="search-form" [formGroup]="searchForm" (keydown.enter)="$event.preventDefault();onSearch()" nzLayout="inline">
  <nz-form-item>
    <nz-form-label nzFor="preName">预定人员姓名</nz-form-label>
    <nz-form-control>
      <nz-input-group nzSearch [nzAddOnAfter]="preNameSuffixIconButton">
        <input nz-input formControlName="preName" placeholder="请选择预定人员姓名" readonly />
      </nz-input-group>
      <ng-template #preNameSuffixIconButton>
        <button nz-button nzType="primary" nzSearch (click)="findReservationRecord()"><nz-icon nzType="search" /></button>
      </ng-template>
    </nz-form-control>
  </nz-form-item>
  <nz-form-item>
    <nz-form-label nzFor="prePhone">预定人员联系电话</nz-form-label>
    <nz-form-control>
      <nz-input-group nzSearch [nzAddOnAfter]="prePhoneSuffixIconButton">
        <input nz-input formControlName="prePhone" placeholder="请选择预定人员联系电话" readonly />
      </nz-input-group>
      <ng-template #prePhoneSuffixIconButton>
        <button nz-button nzType="primary" nzSearch (click)="findReservationRecord()"><nz-icon nzType="search" /></button>
      </ng-template>
    </nz-form-control>
  </nz-form-item>
  <nz-form-item>
    <nz-form-label nzFor="roomNumber">房号</nz-form-label>
    <nz-form-control>
      <nz-input-group nzSearch [nzAddOnAfter]="roomNumberSuffixIconButton">
        <input nz-input formControlName="roomNumber" placeholder="请选择房号" readonly />
      </nz-input-group>
      <ng-template #roomNumberSuffixIconButton>
        <button nz-button nzType="primary" nzSearch (click)="findRoom()"><nz-icon nzType="search" /></button>
      </ng-template>
    </nz-form-control>
  </nz-form-item>
  <nz-form-item>
    <nz-form-label nzFor="name">姓名</nz-form-label>
    <nz-form-control>
      <input nz-input formControlName="name" placeholder="请输入姓名" />
    </nz-form-control>
  </nz-form-item>
  <nz-form-item>
    <nz-form-label nzFor="phone">联系电话</nz-form-label>
    <nz-form-control>
      <input nz-input formControlName="phone" placeholder="请输入联系电话" />
    </nz-form-control>
  </nz-form-item>
  <nz-form-item>
    <nz-form-label nzFor="status">状态</nz-form-label>
    <nz-form-control>
      <nz-select formControlName="status" class="custom-select-width">
        <nz-option nzLabel="已入驻" [nzValue]="20"></nz-option>
        <nz-option nzLabel="已取消" [nzValue]="30"></nz-option>
        <nz-option nzLabel="已退房" [nzValue]="40"></nz-option>
      </nz-select>
    </nz-form-control>
  </nz-form-item>
  <button nz-button type="button" nzType="primary" [nzLoading]="searchLoading" (click)="onSearch()">查询</button>
  <button nz-button type="button" class="margin-button" (click)="onReset()">重置</button>
  <button nz-button type="button" class="margin-button" nzType="primary" (click)="onAdd()">新增</button>
  <button nz-button type="button" class="margin-button" nzType="primary" [nzLoading]="searchLoading" (click)="onExport()">导出</button>
</form>
<nz-table #basicTable [nzData]="listOfData" [nzTotal]="total" [nzLoading]="searchLoading" nzSize="small">
  <thead>
    <tr>
      <th>预定人员姓名</th>
      <th>预定人员联系电话</th>
      <th>房号</th>
      <th>姓名</th>
      <th>联系电话</th>
      <th>入驻时间</th>
      <th>退房时间</th>
      <th>房费</th>
      <th>商品消费</th>
      <th>总金额</th>
      <th>备注</th>
      <th>状态</th>
      <th nzWidth="250px">操作</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let data of basicTable.data">
      <td>{{data.preName}}</td>
      <td>{{data.prePhone}}</td>
      <td>{{data.roomNumber}}</td>
      <td>{{data.name}}</td>
      <td>{{data.phone}}</td>
      <td>{{data.checkInTime}}</td>
      <td>{{data.checkOutTime}}</td>
      <td>{{data.roomAmount}}</td>
      <td>{{data.goodsAmount}}</td>
      <td>{{data.amount}}</td>
      <td>{{data.remark}}</td>
      <td>
        <ng-container *ngIf="data.status === 20">已入驻</ng-container>
        <ng-container *ngIf="data.status === 30">已取消</ng-container>
        <ng-container *ngIf="data.status === 40">已退房</ng-container>
      </td>
      <td>
        <button nz-button type="button" nzType="primary" (click)="editRow(data.id)">编辑</button>
        <button nz-button type="button" nzDanger class="margin-button" (click)="delRow(data.id)">删除</button>
        <button nz-button type="button" class="margin-button" (click)="detailRow(data)">详情</button>
      </td>
    </tr>
  </tbody>
</nz-table>
<reservation-record-selector (reservationRecordSelectedEvent)="handleReservationRecordSelectedEvent($event)"></reservation-record-selector>
<room-selector (roomSelectedEvent)="handleRoomSelectedEvent($event)"></room-selector>
<check-in-record-add (addedEvent)="onAdded($event)"></check-in-record-add>
<check-in-record-view></check-in-record-view>

// v3_el/src/views/checkInRecord/CheckInRecordList.vue
<template>
  <div class="checkInRecord-list">
    <div class="breadcrumb">
      <el-breadcrumb separator="/">
        <el-breadcrumb-item to="Home" :replace="true">首页</el-breadcrumb-item>
        <el-breadcrumb-item>入住记录列表</el-breadcrumb-item>
      </el-breadcrumb>
    </div>
    <el-form :inline="true" :model="checkInRecordQueryForm" ref="checkInRecordQueryFormRef" :rules="rules">
      <el-form-item label="房号" prop="roomNumber">
        <el-input v-model="checkInRecordQueryForm.roomNumber" placeholder="请选择房号" readonly="readonly">
          <template #suffix>
            <el-icon @click="findRoom"><Search/></el-icon>
          </template>
        </el-input>
      </el-form-item>
      <el-form-item label="姓名" prop="name">
        <el-input v-model="checkInRecordQueryForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
      </el-form-item>
      <el-form-item label="联系电话" prop="phone">
        <el-input v-model="checkInRecordQueryForm.phone" placeholder="请输入联系电话" maxlength="20"></el-input>
      </el-form-item>
      <el-form-item label="状态" prop="status">
        <el-select v-model="checkInRecordQueryForm.status" placeholder="请选择状态" class="select-custom">
          <el-option label="已入驻" :value="20"></el-option>
          <el-option label="已取消" :value="30"></el-option>
          <el-option label="已退房" :value="40"></el-option>
        </el-select>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="onSearch">查询</el-button>
        <el-button @click="onReset">重置</el-button>
        <el-button type="primary" @click="onAdd">新增</el-button>
        <el-button type="primary" @click="onExport">导出</el-button>
      </el-form-item>
    </el-form>

    <el-table
      :data="state.tableData"
      border
      v-loading="state.loading"
      size="small"
      header-cell-class-name="table-header-cell-font"
      cell-class-name="table-cell-font">
      <el-table-column prop="preName" label="预定人员姓名" width="100"></el-table-column>
      <el-table-column prop="prePhone" label="预定人员联系电话" width="140"></el-table-column>
      <el-table-column prop="roomNumber" label="房号" width="100"></el-table-column>
      <el-table-column prop="name" label="姓名" width="100"></el-table-column>
      <el-table-column prop="phone" label="联系电话" width="100"></el-table-column>
      <el-table-column prop="checkInTime" label="入驻时间" width="140"></el-table-column>
      <el-table-column prop="checkOutTime" label="退房时间" width="140"></el-table-column>
      <el-table-column prop="roomAmount" label="房费" width="100"></el-table-column>
      <el-table-column prop="goodsAmount" label="商品消费" width="100"></el-table-column>
      <el-table-column prop="amount" label="总金额" width="100"></el-table-column>
      <el-table-column prop="remark" label="备注" width="100"></el-table-column>
      <el-table-column prop="status" label="状态" width="100">
        <template v-slot="{ row }">
          <div v-if="row.status === 20">已入驻</div>
          <div v-if="row.status === 30">已取消</div>
          <div v-if="row.status === 40">已退房</div>
        </template>
      </el-table-column>
      <el-table-column fixed="right" label="操作" width="250">
        <template v-slot="{ row }">
          <el-button @click.prevent="editRow(row.id)" type="primary">编辑</el-button>
          <el-button @click.prevent="delRow(row.id)" type="danger" plain>删除</el-button>
          <el-button @click.prevent="detailRow(row.id)" type="primary" plain>详情</el-button>
        </template>
      </el-table-column>
    </el-table>
    <div class="table-pagination">
      <el-pagination
        @current-change="changePage"
        :current-page="state.currentPage"
        :page-sizes="state.pageSizes"
        :page-size="state.pageSize"
        background
        layout="total, prev, pager, next, jumper"
        :total="state.total">
      </el-pagination>
    </div>
    <el-dialog v-model="roomSelectorVisible" v-if="roomSelectorVisible" title="房间选择器(双击行选中)" :top="dialogTop" :width="dialogWidth">
      <room-selector @room-selected-event="handleRoomSelectedEvent">
      </room-selector>
    </el-dialog>
    <el-dialog v-model="checkInRecordAddVisible" v-if="checkInRecordAddVisible" :title="checkInRecordAddTitle" :top="dialogTop" :width="dialogWidth">
      <check-in-record-add :id="selectedCheckInRecordId" @close-check-in-record-add-event="handleCloseCheckInRecordAddEvent" @reset-check-in-record-add-event="handleResetCheckInRecordAddEvent">
      </check-in-record-add>
    </el-dialog>
    <el-dialog v-model="checkInRecordViewVisible" v-if="checkInRecordViewVisible" title="入住记录详情" :top="dialogTop" :width="dialogWidth">
      <check-in-record-view :id="selectedCheckInRecordId" @close-check-in-record-view-event="handleCloseCheckInRecordViewEvent">
      </check-in-record-view>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { inject, onMounted, reactive, ref, toRefs } from 'vue'
import checkInRecordApi from '@/api/checkInRecordApi'
import type { CheckInRecordQueryForm } from '@/types/req/checkInRecordQueryForm'
import type { CheckInRecord } from '@/types/resp/checkInRecord'
import { ElMessage, ElMessageBox, type FormInstance } from 'element-plus'
import type { Result } from '@/types/result'
import type { Page } from '@/types/page'
import { Search } from '@element-plus/icons-vue'
import RoomSelector from '@/views/room/RoomSelector.vue'
import CheckInRecordAdd from '@/views/checkInRecord/CheckInRecordAdd.vue'
import CheckInRecordView from '@/views/checkInRecord/CheckInRecordView.vue'
import { exportToExcel } from '@/composables/exportUtil.ts'
import { getCheckInRecordStatusText } from '@/composables/dictTranslator.ts'

const checkInRecordQueryFormRef = ref<FormInstance | null>(null);
const checkInRecordQueryForm = reactive<CheckInRecordQueryForm>({
  roomId: 0,
  roomNumber: '',
  name: '',
  phone: '',
  status: undefined,
})

const state = reactive({
  loading: false,
  tableData: [] as CheckInRecord[], // 数据列表
  total: 0, // 总条数
  currentPage: 1, // 当前页
  pageSize: 10, // 分页大小
  pageSizes: [10, 20, 50]
})
const selectedCheckInRecordId = ref<number>(0)
const roomSelectorVisible = ref<boolean>(false)
const checkInRecordAddVisible = ref<boolean>(false)
const checkInRecordViewVisible = ref<boolean>(false)
const checkInRecordAddTitle = ref<string>('')
const dialogTop = ref<string>('')
const dialogWidth = ref<string>('')

const rules = reactive({
});

onMounted(() => {
  onSearch()
  const globalState = inject('globalState', {} as { dialogWidth?: string, dialogTop?: string })
  if (!globalState) {
    throw new Error('globalState is not provided');
  }
  const globalStateRefs = toRefs(globalState)
  if (globalStateRefs.dialogWidth) {
    dialogWidth.value = globalStateRefs.dialogWidth.value || ''
  }
  if (globalStateRefs.dialogTop) {
    dialogTop.value = globalStateRefs.dialogTop.value || ''
  }
})

const getPageData = async () => {
  try {
    state.loading = true
    const resp: Result<Page<CheckInRecord>> = await checkInRecordApi.find(checkInRecordQueryForm)
    if (resp && resp.code === 1) {
      if (resp.data) {
      const page: Page<CheckInRecord> = resp.data
        if (page && page.list.length > 0) {
          state.tableData = page.list
          state.total = page.total
        }
      }
    }
  } catch (e) {
    console.log('获取数据异常', e)
  } finally {
    state.loading = false
  }
}
const onSearch = () => {
  getPageData()
}

const changePage = (val: number) => {
  state.currentPage = val
  getPageData()
}

const onReset = () => {
  if (checkInRecordQueryFormRef.value) {
    checkInRecordQueryFormRef.value.resetFields()
  }
  state.currentPage = 1
  getPageData()
}

const onAdd = () => {
  selectedCheckInRecordId.value = 0
  checkInRecordAddVisible.value = true
  checkInRecordAddTitle.value = '入住记录新增'
}
const editRow = (id: number) => {
  selectedCheckInRecordId.value = id
  checkInRecordAddVisible.value = true
  checkInRecordAddTitle.value = '入住记录编辑'
}
const delRow = (id: number) => {
  if (!id) {
    return
  }
  ElMessageBox.confirm(
    '确定要删除吗?',
    '删除提示',
    {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning',
    }
  ).then(() => {
    checkInRecordApi.del(id)
      .then((resp) => {
        if (resp && resp.code === 1) {
          ElMessage.success('删除成功!')
          onSearch()
        } else {
          ElMessage.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
        }
      })
      .catch(error => {
        console.error('操作失败:', error)
      })
  }).catch(() => {})
}
const detailRow = (id:number) => {
  selectedCheckInRecordId.value = id
  checkInRecordViewVisible.value = true
}

const findRoom = () => {
  roomSelectorVisible.value = true
}

const handleRoomSelectedEvent = (selectedRoom: any) => {
  roomSelectorVisible.value = false
  if (selectedRoom && 'roomId' in selectedRoom && checkInRecordQueryForm.roomId !== selectedRoom['roomId']) {
    checkInRecordQueryForm.roomId = selectedRoom['roomId']
    checkInRecordQueryForm.roomNumber = selectedRoom['roomNumber']
  }
}

const handleCloseCheckInRecordViewEvent = () => {
  checkInRecordViewVisible.value = false
}

const handleResetCheckInRecordAddEvent = () => {
  checkInRecordAddTitle.value = '入住记录新增'
}

const handleCloseCheckInRecordAddEvent = (params: { search?: boolean } | undefined) => {
  if (params && params.search) {
    onSearch()
  }
  checkInRecordAddVisible.value = false
}

const onExport = () => {
  const headers = ['预定人员姓名', '预定人员联系电话', '房号', '姓名', '联系电话', '入驻时间', '退房时间', '房费', '商品消费', '总金额', '备注', '状态']
  checkInRecordApi.find(checkInRecordQueryForm).then(data => {
    if (!data || !data.data || data.data.list.length < 1) {
      ElMessage.error('无数据导出')
      return
    }
    const exportData = []
    for (const d of data.data.list) {
      exportData.push([d.preName, d.prePhone, d.roomNumber, d.name, d.phone, d.checkInTime,
        d.checkOutTime, d.roomAmount, d.goodsAmount, d.amount, d.remark, getCheckInRecordStatusText(d.status)])
    }
    exportToExcel(headers, exportData)
  })
}
</script>

<style lang="scss">
</style>
