// react_antd/src/pages/staff/StaffList.tsx
import React, {useCallback, useEffect, useState} from 'react';
import {Breadcrumb, Button, Form, Input, message, Modal, Space, Table, TableProps} from 'antd';
import {useNavigate} from "react-router-dom";
import type {Staff} from "@/types/resp/staff";
import staffApi from '@/api/staffApi'
import {Result} from "@/types/result";
import {Page} from "@/types/page";
import StaffAdd from "@/pages/staff/StaffAdd.tsx";
import StaffView from "@/pages/staff/StaffView.tsx";


const StaffList: React.FC = () => {

  const navigate = useNavigate();
  const [messageApi, messageContextHolder] = message.useMessage();
  const [modal, modalContextHolder] = Modal.useModal();

  const handleClick = (path: string) => {
    navigate(path);
  };

  const breadcrumbsItems = [
    {title: '首页', className: 'breadcrumbHome', onClick: () => handleClick('/Home')},
    {title: '员工列表'}
  ]

  const [form] = Form.useForm();

  const onFinish = async () => {
    await onSearch()
  };

  const onReset = () => {
    form.resetFields();
  };

  const [data, setData] = useState<Staff[]>([]);
  const onSearch = async () => {
    try {
      const resp: Result<Page<Staff>> = await staffApi.find(form.getFieldsValue())
      if (resp && resp.code === 1) {
        if (resp.data) {
          const page: Page<Staff> = resp.data
          if (page && page.list.length > 0) {
            setData(page.list)
          }
        }
      }
    } catch (e) {
      console.log('获取数据异常', e)
    }
  };

  const columns: TableProps<Staff>['columns'] = [
    {title: '姓名', dataIndex: 'name', key: 'name'},
    {title: '联系电话', dataIndex: 'phone', key: 'phone'},
    {title: '岗位', dataIndex: 'position', key: 'position'},
    {title: '特长', dataIndex: 'specialty', key: 'specialty'},
    {
      title: '操作',
      key: 'action',
      width: '250px',
      render: (_, record) => (
        <Space size="middle">
          <Button type="primary" onClick={() => editRow(record.id)}>编辑</Button>
          <Button danger onClick={() => delRow(record.id)}>删除</Button>
          <Button color="primary" variant="outlined" onClick={() => detailRow(record)}>详情</Button>
        </Space>
      ),
    },
  ];

  const [staffAddVisible, setStaffAddVisible] = useState(false);
  const [staffViewVisible, setStaffViewVisible] = useState(false);
  const [selectedStaffId, setSelectedStaffId] = useState(0)
  const [selectedStaff, setSelectedStaff] = useState({})

  const onAdd = () => {
    setSelectedStaffId(0)
    setStaffAddVisible(true)
  };

  const editRow = (id: number) => {
    setSelectedStaffId(id)
    setStaffAddVisible(true)
  };

  const delRow = useCallback(async (id: number) => {
    const confirmed = await modal.confirm({
      title: '删除提示',
      content: (
        <>
          确定要删除吗?
        </>
      ),
      okText: '确定',
      cancelText: '取消',
      type: 'warning'
    });

    if (confirmed) {
      staffApi.del(id)
        .then((resp) => {
          if (resp && resp.code === 1) {
            messageApi.success('删除成功!')
            onSearch()
          } else {
            messageApi.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
          }
        })
        .catch(error => {
          console.error('操作失败:', error)
        })
    }
  }, [modal]);

  const detailRow = (record: Staff) => {
    setSelectedStaff(record)
    setStaffViewVisible(true)
  };


  const handleCloseStaffAdd = () => {
    setStaffAddVisible(false)
  };

  const handleCloseStaffView = () => {
    setStaffViewVisible(false)
  };

  useEffect(() => {
    onSearch();

    return () => {
    };
  }, []);

  return (
    <div className="staffList">
      {messageContextHolder}
      {modalContextHolder}
      <Breadcrumb items={breadcrumbsItems} style={{marginBottom: 'var(--container-margin)'}} />
      <Form form={form} onFinish={onFinish} layout={"inline"}>
        <Form.Item name="name" label="姓名">
          <Input maxLength={64} placeholder="请输入姓名"/>
        </Form.Item>
        <Form.Item name="phone" label="联系电话">
          <Input maxLength={20} placeholder="请输入联系电话"/>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" htmlType="submit">查询</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button onClick={onReset}>重置</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" onClick={onAdd}>新增</Button>
        </Form.Item>
      </Form>
      <Table<Staff> columns={columns} dataSource={data} size="small" rowKey={record => record.id} pagination={{ position: ["bottomCenter"] }} style={{marginTop: 'var(--container-margin)'}} />
      <StaffAdd visible={staffAddVisible} onCloseStaffAdd={handleCloseStaffAdd} id={selectedStaffId} />
      <StaffView visible={staffViewVisible} onCloseStaffView={handleCloseStaffView} viewRow={selectedStaff} />
    </div>
  );
};

export default StaffList;

// v3_el/src/views/staff/StaffList.vue
<template>
  <div class="staff-list">
    <div class="breadcrumb">
      <el-breadcrumb separator="/">
        <el-breadcrumb-item to="Home" :replace="true">首页</el-breadcrumb-item>
        <el-breadcrumb-item>员工列表</el-breadcrumb-item>
      </el-breadcrumb>
    </div>
    <el-form :inline="true" :model="staffQueryForm" ref="staffQueryFormRef" :rules="rules">
      <el-form-item label="姓名" prop="name">
        <el-input v-model="staffQueryForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
      </el-form-item>
      <el-form-item label="联系电话" prop="phone">
        <el-input v-model="staffQueryForm.phone" placeholder="请输入联系电话" maxlength="20"></el-input>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="onSearch">查询</el-button>
        <el-button @click="onReset">重置</el-button>
        <el-button type="primary" @click="onAdd">新增</el-button>
      </el-form-item>
    </el-form>

    <el-table
      :data="state.tableData"
      border
      v-loading="state.loading"
      size="small"
      header-cell-class-name="table-header-cell-font"
      cell-class-name="table-cell-font">
      <el-table-column prop="name" label="姓名"></el-table-column>
      <el-table-column prop="phone" label="联系电话"></el-table-column>
      <el-table-column prop="position" label="岗位"></el-table-column>
      <el-table-column prop="specialty" label="特长"></el-table-column>
      <el-table-column fixed="right" label="操作" width="250">
        <template v-slot="{ row }">
          <el-button @click.native.prevent="editRow(row.id)" type="primary">编辑</el-button>
          <el-button @click.native.prevent="delRow(row.id)" type="danger" plain>删除</el-button>
          <el-button @click.native.prevent="detailRow(row.id)" type="primary" plain>详情</el-button>
        </template>
      </el-table-column>
    </el-table>
    <div class="table-pagination">
      <el-pagination
        @current-change="changePage"
        :current-page="state.currentPage"
        :page-sizes="state.pageSizes"
        :page-size="state.pageSize"
        background
        layout="total, prev, pager, next, jumper"
        :total="state.total">
      </el-pagination>
    </div>
    <el-dialog v-model="staffAddVisible" v-if="staffAddVisible" :title="staffAddTitle" :top="dialogTop" :width="dialogWidth">
      <staff-add :id="selectedStaffId" @close-staff-add-event="handleCloseStaffAddEvent" @reset-staff-add-event="handleResetStaffAddEvent">
      </staff-add>
    </el-dialog>
    <el-dialog v-model="staffViewVisible" v-if="staffViewVisible" title="员工详情" :top="dialogTop" :width="dialogWidth">
      <staff-view :id="selectedStaffId" @close-staff-view-event="handleCloseStaffViewEvent">
      </staff-view>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import {onMounted, reactive, ref, inject, toRefs} from 'vue';
import staffApi from '@/api/staffApi'
import type {StaffQueryForm} from "@/types/req/staffQueryForm";
import type {Staff} from "@/types/resp/staff";
import {ElMessage, ElMessageBox, type FormInstance} from "element-plus";
import type {Result} from "@/types/result";
import type {Page} from "@/types/page";
import StaffAdd from "@/views/staff/StaffAdd.vue"
import StaffView from "@/views/staff/StaffView.vue"

const staffQueryFormRef = ref<FormInstance | null>(null);
let staffQueryForm = reactive<StaffQueryForm>({
  name: '',
  phone: '',
})

const state = reactive({
  loading: false,
  tableData: [] as Staff[], // 数据列表
  total: 0, // 总条数
  currentPage: 1, // 当前页
  pageSize: 10, // 分页大小
  pageSizes: [10, 20, 50]
})
const selectedStaffId = ref<number>(0)
const staffAddVisible = ref<boolean>(false)
const staffViewVisible = ref<boolean>(false)
const staffAddTitle = ref<string>('')
const dialogTop = ref<string>('')
const dialogWidth = ref<string>('')

const rules = reactive({
});

onMounted(() => {
  onSearch()
  const globalState = inject('globalState', {} as { dialogWidth?: string, dialogTop?: string })
  if (!globalState) {
    throw new Error('globalState is not provided');
  }
  const globalStateRefs = toRefs(globalState)
  if (globalStateRefs.dialogWidth) {
    dialogWidth.value = globalStateRefs.dialogWidth.value || ''
  }
  if (globalStateRefs.dialogTop) {
    dialogTop.value = globalStateRefs.dialogTop.value || ''
  }
})

const getPageData = async () => {
  try {
    state.loading = true
    const resp: Result<Page<Staff>> = await staffApi.find(staffQueryForm)
    if (resp && resp.code === 1) {
      if (resp.data) {
      const page: Page<Staff> = resp.data
        if (page && page.list.length > 0) {
          state.tableData = page.list
          state.total = page.total
        }
      }
    }
  } catch (e) {
    console.log('获取数据异常', e)
  } finally {
    state.loading = false
  }
}
const onSearch = () => {
  getPageData()
}

const changePage = (val: number) => {
  state.currentPage = val
  getPageData()
}

const onReset = () => {
  if (staffQueryFormRef.value) {
    staffQueryFormRef.value.resetFields()
  }
  state.currentPage = 1
  getPageData()
}

const onAdd = () => {
  selectedStaffId.value = 0
  staffAddVisible.value = true
  staffAddTitle.value = '员工新增'
}
const editRow = (id: number) => {
  selectedStaffId.value = id
  staffAddVisible.value = true
  staffAddTitle.value = '员工编辑'
}
const delRow = (id: number) => {
  if (!id) {
    return
  }
  ElMessageBox.confirm(
    '确定要删除吗?',
    '删除提示',
    {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning',
    }
  ).then(() => {
    staffApi.del(id)
      .then((resp) => {
        if (resp && resp.code === 1) {
          ElMessage.success('删除成功!')
          onSearch()
        } else {
          ElMessage.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
        }
      })
      .catch(error => {
        console.error('操作失败:', error)
      })
  }).catch(() => {})
}
const detailRow = (id:number) => {
  selectedStaffId.value = id
  staffViewVisible.value = true
}

const handleCloseStaffViewEvent = () => {
  staffViewVisible.value = false
}

const handleResetStaffAddEvent = () => {
  staffAddTitle.value = '员工新增'
}

const handleCloseStaffAddEvent = (params: { search?: boolean } | undefined) => {
  if (params && params.search) {
    onSearch()
  }
  staffAddVisible.value = false
}
</script>

<style lang="scss">
</style>
