// react_antd/src/pages/reservationRecord/ReservationRecordView.tsx
import React, {useEffect} from "react";
import {Button, Col, DatePicker, Form, Input, Modal, Row, Select} from "antd";
import {ReservationRecord} from "@/types/resp/reservationRecord";

interface ReservationRecordViewProps {
  visible: boolean;
  viewRow: object;
  onCloseReservationRecordView: () => void;
}

const ReservationRecordView: React.FC<ReservationRecordViewProps> = ({visible, viewRow, onCloseReservationRecordView}) => {

  const [form] = Form.useForm<ReservationRecord>();

  const onBack = () => {
    onCloseReservationRecordView()
  };

  useEffect(() => {
    if (!visible) {
      return
    }
    if (viewRow) {
      form.setFieldsValue(viewRow);
    }
  }, [viewRow]);

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onBack}>关闭</Button>
    </div>
  );

  return (
    <Modal title={"预定记录详情"} open={visible} onCancel={onCloseReservationRecordView}
        width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={form} labelCol={{span: 6}} disabled={true}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="roomNumber" label="房号">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="name" label="姓名">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="phone" label="联系电话">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="checkInTime" label="预定入驻时间">
              <DatePicker showTime={true}/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="remark" label="备注">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="status" label="状态">
              <Select placeholder="请选择状态" options={[
                { value: 10, label: <span>已预定</span> },
                { value: 20, label: <span>已入驻</span> },
                { value: 30, label: <span>已取消</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="createTime" label="创建时间">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="modifyTime" label="最后修改时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default ReservationRecordView;

// angular_ngzorro/src/app/reservation-record/reservation-record-view.component.ts
import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {SharedModule} from '../shared.module';
import {MODAL_WIDTH} from '../../const'
import {ReservationRecord} from '../../types/resp/ReservationRecord';

@Component({
  selector: 'reservation-record-view',
  imports: [
    SharedModule
  ],
  templateUrl: './reservation-record-view.component.html',
  standalone: true
})
export class ReservationRecordViewComponent implements OnInit {
  reservationRecordForm!: FormGroup;
  isVisible: boolean = false
  title: string = '预定记录详情'
  modalWidth: string = MODAL_WIDTH

  constructor(
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.reservationRecordForm = this.fb.group({
      roomNumber: [''],
      name: [''],
      phone: [''],
      checkInTime: [''],
      remark: [''],
      status: [undefined],
      createTime: [''],
      modifyTime: [''],
    })
  }

  onBack() {
    this.isVisible = false
  }

  display(reservationRecord: ReservationRecord) {
    this.isVisible = true
    this.reservationRecordForm.patchValue(reservationRecord);
    this.reservationRecordForm.disable();
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="reservationRecordForm">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomNumber">房号</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="roomNumber" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name">姓名</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="name" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="phone">联系电话</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="phone" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="checkInTime">预定入驻时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="checkInTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="remark">备注</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="remark" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="status">状态</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="status">
                <nz-option nzLabel="已预定" [nzValue]="10"></nz-option>
                <nz-option nzLabel="已入驻" [nzValue]="20"></nz-option>
                <nz-option nzLabel="已取消" [nzValue]="30"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="createTime">创建时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="createTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="modifyTime">最后修改时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="modifyTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
