// v3_el/src/views/Home.vue
<template>
  <div class="home">
    <div class="home-container">{{ $t('welcomeMessage') }}</div>
    <div class="home-container">{{ $t('ad1')}}</div>
    <div class="home-container">{{ $t('ad2')}}</div>
    <div class="home-container">{{ $t('ad3')}}</div>
    <div class="home-container"><img src="../assets/weixinqrcode_small.jpg" :alt="$t('weixinAlt')"/></div>
  </div>
</template>

<script setup lang="ts">
</script>

<style scoped>
.home-container{
  width: 100%;
  display: flex;
  justify-content: center;
  font-size: 22px;
  margin: 10px auto 0;
}
</style>

// react_antd/src/pages/Home.tsx
import React from 'react';
import {useTranslation} from "react-i18next";
import weixinqrcode from '@/assets/weixinqrcode_small.jpg'

const Home: React.FC = () => {
  const { t } = useTranslation();
  const homeStyle = {
    width: '100%',
    margin: '0 auto',
    display: 'flex',
    justifyContent: 'center',
    fontSize: '22px',
    marginTop: 10
  }

  return (
    <>
      <div style={homeStyle}>{t('welcomeMessage')}</div>
      <div style={homeStyle}>{t('ad1')}</div>
      <div style={homeStyle}>{t('ad2')}</div>
      <div style={homeStyle}>{t('ad3')}</div>
      <div style={homeStyle}><img src={weixinqrcode} alt={t('weixinAlt')}/></div>
    </>
  )
};

export default Home;
