// v2_el/src/views/Login.vue
<template>
  <div class="login-page">
    <div class="login">
      <div class="login__logo"></div>
      <div class="login__title">{{ $t('title') }}</div>
      <el-form :model="loginForm" :rules="rules" ref="loginForm" @keyup.enter.native="onLogin">
        <el-form-item prop="username">
          <el-input v-model="loginForm.username" placeholder="请输入用户名"></el-input>
        </el-form-item>
        <el-form-item prop="password">
          <el-input v-model="loginForm.password" type="password" placeholder="请输入密码"></el-input>
        </el-form-item>
        <el-form-item prop="verificationCode">
          <el-input v-model="loginForm.verificationCode" placeholder="请输入验证码"></el-input>
        </el-form-item>
        <el-form-item>
          <canvas id="captchaCanvas" width="150" height="50" @click="drawCaptcha"></canvas>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="onLogin" class="login__btn" :loading="loading">登录</el-button>
        </el-form-item>
      </el-form>
    </div>
    <div class="footer">
      <span>版权所有 &copy; 2024 - 2026 <a href="http://www.52ejn.com" target="_blank">源码学习网</a></span><a href="http://beian.miit.gov.cn" target="_blank">粤ICP备2024308896号-1</a>
    </div>
  </div>
</template>

<script>
import userApi from '@/api/userApi'
import captchaMixin from "@/mixins/captchaMixin";
import {ADMIN_USERNAME, PASSWORD} from "@/const";
export default {
  // eslint-disable-next-line vue/multi-word-component-names
  name: 'Login',
  mixins: [
    captchaMixin
  ],
  data () {
    return {
      loginForm: {
        username: ADMIN_USERNAME,
        password: PASSWORD,
        verificationCode: ''
      },
      rules: {
        username: [
          { required: true, message: '用户名不能为空', trigger: 'blur' }
        ],
        password: [
          { required: true, message: '密码不能为空', trigger: 'blur' }
        ],
        verificationCode: [
          { required: true, message: '验证码不能为空', trigger: 'blur' }
        ]
      },
      loading: false
    }
  },
  created () {
    if (this.$route.query.type) {
      this.loginForm.type = Number(this.$route.query.type)
    }
  },
  methods: {
    onLogin () {
      this.$refs.loginForm.validate(async (valid) => {
        if (valid) {
          if (this.generatedVerificationCode.toLowerCase() !== this.loginForm.verificationCode.toLowerCase()) {
            this.$message.error('验证码错误')
            this.refreshCaptcha()
            return
          }
          this.loading = true
          // 登录验证
          userApi.login(this.loginForm)
            .then(resp => {
              if (resp && resp.code === 1) {
                this.$message.success('登录成功')
                const lt = resp.data
                sessionStorage.setItem('backendToken', lt.token)
                sessionStorage.setItem('uid', lt.uid)
                sessionStorage.setItem('username', lt.username)
                this.$router.replace({ path: '/Home' })
              } else {
                this.$message.error(resp && resp.msg ? resp.msg : '登录失败，用户名或密码错误')
                this.refreshCaptcha()
                this.loading = false
              }
            })
            .catch(error => {
              console.log('登录失败', error)
              this.$message.error('登录失败，用户名或密码错误')
              this.refreshCaptcha()
              this.loading = false
            })
        } else {
          this.refreshCaptcha()
          return false
        }
      })
    },
    refreshCaptcha () {
      this.loginForm.verificationCode = ''
      this.loginForm.username = ADMIN_USERNAME
      this.loginForm.password = PASSWORD
      this.drawCaptcha()
    }
  }
}
</script>

<style lang="scss">
@import "../assets/styles/var";

.login-page {
  width: 100vw;
  height: 100vh;
  padding-top: 60px;
  background-color: $primary-color;

  .login {
    width: 400px;
    margin: 0 auto;
    padding: 20px;
    background: #f5f5f5;
    box-shadow: 0 0 8px 0 $box-shadow-base;
    border-radius: 6px;

    div {
      text-align: center;
    }

    @at-root #{&}__logo {
      img {
        width: 30%;
      }
    }

    @at-root #{&}__title {
      margin: 10px 0;
      font-size: 36px;
      text-transform: uppercase;
    }

    @at-root #{&}__subtitle {
      margin-bottom: 20px;
      text-transform: uppercase;
      letter-spacing: 10px;
    }
  }
}

.footer {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  padding: 1rem;
  background-color: transparent;
  color: #fff;
  text-align: center;
  a {
    color: #ffffff;
    padding-left: 5px;
  }
}
</style>

// react_antd/src/pages/Login.tsx
import React, {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import userApi from '@/api/userApi'
import type {LoginForm} from '@/types/req/loginForm'
import type {Result} from '@/types/result'
import type {LoginSession} from '@/types/resp/loginSession'
import {Button, Form, Input, message} from 'antd';
import Captcha from '@/components/Captcha';
import {useTranslation} from "react-i18next";
import '@/assets/styles/login.css'
import {ADMIN_USERNAME, PASSWORD} from "@/const";
import {generateCaptcha} from "@/utils/verificationCode.ts";

type MessageType = 'success' | 'warning' | 'error';

// 定义校验规则
const rules = {
  username: [
    { required: true, message: '请输入用户名' },
  ],
  password: [
    { required: true, message: '请输入密码' }
  ],
  verificationCode: [
    { required: true, message: '请输入验证码' }
  ]
};

const Login: React.FC = () => {
  const navigate = useNavigate();

  const [messageApi, messageContextHolder] = message.useMessage();

  const openNotification = (messageType: MessageType, msg: string, onCloseCallback?: () => void) => {
    messageApi.open({
      type: messageType,
      content: msg,
      duration: 1,
      onClose: () => {
        if (onCloseCallback) {
          onCloseCallback(); // 如果提供了回调，则执行它
        }
      }
    });
  };

  const handleLoginSuccess = (type: MessageType, msg: string) => {
    openNotification(type, msg, () => {
      const lastPath = sessionStorage.getItem('lastPath')
      if (lastPath && lastPath.trim() !== '') {
        sessionStorage.removeItem('lastPath')
        navigate(lastPath);
      } else {
        navigate('/Home');
      }
    });
  };
  const handleLoginError = (type: MessageType, msg: string) => {
    openNotification(type, msg);
  };

  const initialLoginForm: LoginForm = {
    username: ADMIN_USERNAME,
    password: PASSWORD,
    verificationCode: ''
  }

  const { t } = useTranslation();
  const [form] = Form.useForm();
  const [loginForm, setLoginForm] = useState(initialLoginForm);

  // 当表单值改变时更新 loginForm 状态
  const handleValuesChange = (changedValues: Partial<LoginForm>) => {
    setLoginForm((prevState) => ({
      ...prevState,
      ...changedValues
    }));
  };

  const [generatedCaptcha, setGeneratedCaptcha] = useState(generateCaptcha());

  const refreshCaptcha = () => {
    setLoginForm(initialLoginForm);
    form.setFieldsValue(initialLoginForm);
    const newCaptcha = generateCaptcha();
    setGeneratedCaptcha(newCaptcha);
  };

  const handleLogin = async () => {
    try {
      await form.validateFields()
      if (loginForm.verificationCode.toUpperCase() !== generatedCaptcha.toUpperCase()) {
        openNotification('error', '验证码不正确')
        refreshCaptcha()
        return
      }

        // 假设这里有一个验证登录的函数，返回true或false
      const resp: Result<LoginSession> = await userApi.login(loginForm);
      if (!resp || resp.code !== 1) {
        const errorMsg = resp && resp.msg ? resp.msg : '操作异常'
        handleLoginError('error', errorMsg)
        refreshCaptcha()
        return
      }
      const loginSession: LoginSession | undefined = resp.data
      if (loginSession) {
        sessionStorage.setItem('loginToken', loginSession.token)
        sessionStorage.setItem('uid', String(loginSession.uid))
        sessionStorage.setItem('username', loginSession.username)
      }
      handleLoginSuccess('success', '登录成功')
    } catch (error) {
      console.error('There was an error submitting the form!', error);
    }
  };

  const handleKeyPress = (event: React.KeyboardEvent) => {
    if (event.key === 'Enter') {
      event.preventDefault(); // 防止默认行为
      handleLogin();
    }
  };

  return (
    <div className="login-page">
      {messageContextHolder}
      <div className="login">
        <div className="title">
          {t('title')}
        </div>
        <Form form={form} autoComplete="off" initialValues={initialLoginForm} onValuesChange={handleValuesChange}>
          <Form.Item name="username" rules={rules.username}>
            <Input placeholder={'请输入用户名'}/>
          </Form.Item>

          <Form.Item name="password" rules={rules.password}>
            <Input.Password placeholder={'请输入密码'}/>
          </Form.Item>

          <Form.Item name="verificationCode" rules={rules.verificationCode}>
            <Input placeholder={'请输入验证码'} onKeyUp={handleKeyPress}/>
          </Form.Item>

          <Captcha captcha={generatedCaptcha} onRefresh={refreshCaptcha}/>
        </Form>
        <div className="btn-container">
          <Button type="primary" onClick={handleLogin}>登录</Button>
        </div>
      </div>
      <div className="footer">
        <span>版权所有 &copy; 2024 - 2026 <a href="http://www.52ejn.com" target="_blank">源码学习网</a></span>
        <a href="http://beian.miit.gov.cn" target="_blank">粤ICP备2024308896号-1</a>
      </div>
    </div>
  );
};

export default Login;
