// angular_ngzorro/src/app/goods/goods-add.component.ts
import {Component, EventEmitter, OnInit, Output} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {GoodsService} from '../../service/goods.service';
import {SharedModule} from '../shared.module';
import {GoodsForm} from '../../types/req/GoodsForm';
import {MODAL_WIDTH} from '../../const'

@Component({
  selector: 'goods-add',
  imports: [
    SharedModule
  ],
  templateUrl: './goods-add.component.html',
  standalone: true
})
export class GoodsAddComponent implements OnInit {
  goodsToSave:GoodsForm = {};
  goodsForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增商品'
  modalWidth: string = MODAL_WIDTH

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private goodsService: GoodsService
  ) {}

  ngOnInit(): void {
    this.goodsForm = this.fb.group({
      name: ['', [Validators.required]],
      price: [0, [Validators.required]],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.goodsForm.controls) {
        this.goodsForm.controls[i].markAsDirty();
        this.goodsForm.controls[i].updateValueAndValidity();
      }
      if (!this.goodsForm.valid) {
        this.saveLoading = false
        return
      }
      this.goodsService.save(Object.assign(this.goodsToSave, this.goodsForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增商品'.slice()
    this.goodsForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改商品'
      this.saveLoading = true
      this.goodsService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.goodsToSave = resp.data
            this.goodsForm.patchValue(this.goodsToSave);
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="goodsForm">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name" nzRequired>商品名称</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入商品名称'">
              <input nz-input formControlName="name" placeholder="请输入商品名称" maxlength="255"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="price" nzRequired>价格</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择价格'">
            <nz-input-number formControlName="price" [nzMin]="1" [nzMax]="9999" [nzPrecision]="2" [nzStep]="0.1" nzPlaceHolder="Digital" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>

// react_antd/src/pages/goods/GoodsAdd.tsx
import React, {useEffect, useState} from "react";
import {Button, Col, Form, Input, InputNumber, message, Modal, Row} from "antd";
import type {Result} from "@/types/result";
import goodsApi from "@/api/goodsApi.ts";
import {Goods} from "@/types/resp/goods";

interface GoodsAddProps {
  visible: boolean;
  id: number;
  onCloseGoodsAdd: () => void;
}

const GoodsAdd: React.FC<GoodsAddProps> = ({visible, id, onCloseGoodsAdd}) => {

  const [form] = Form.useForm<Goods>();
  const [messageApi, messageContextHolder] = message.useMessage();

  const rules = {
    name: [
      { required: true, message: '请输入商品名称' }
    ],
    price: [
      { required: true, message: '请输入价格' }
    ],
  };

  let goodsForm: Partial<Goods> = {}

  const [title, setTitle] = useState('新增商品');

  useEffect(() => {
    if (!visible) {
      return
    }
    if (id) {
      setTitle('编辑商品')
      initGoodsFormById(id)
    } else {
      setTitle('新增商品')
      form.resetFields();
    }
  }, [visible]);

  const initGoodsFormById = async (id: number) => {
    const resp: Result<Goods> = await goodsApi.findById(id)
    if (resp && resp.code === 1 && resp.data) {
      goodsForm = resp.data
      form.setFieldsValue(resp.data);
    }
  }

  const onSave = async () => {
    try {
      await form.validateFields()

      let goods2Save:Goods = form.getFieldsValue()
      if (id) {
        goods2Save = Object.assign(goodsForm, goods2Save)
      }
      const resp: Result<void> = await goodsApi.save(goods2Save);
      if (!resp || resp.code !== 1) {
        messageApi.error('保存失败:' + (resp.msg ? resp.msg : '未知异常'));
        return
      }
      messageApi.success('保存成功');
      onBack()
    } catch (error) {
      console.error('There was an error submitting the form!', error);
    }
  };

  const onReset = () => {
    setTitle('新增商品')
    form.resetFields();
  };
  

  const onBack = () => {
    onCloseGoodsAdd()
  };

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onSave}>保存</Button>
      <Button onClick={onReset} style={{marginLeft: 'var(--button-margin-left)'}}>重置</Button>
      <Button type="primary" onClick={onBack} style={{marginLeft: 'var(--button-margin-left)'}}>关闭</Button>
    </div>
  );

  return (
    <Modal title={title} open={visible} onCancel={onCloseGoodsAdd} width={'var(--modal-width)'}
        footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      {messageContextHolder}
      <Form form={form} name="goodsForm" labelCol={{span: 6}}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="name" label="商品名称" rules={rules.name}>
              <Input maxLength={255} placeholder="请输入商品名称"/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="price" label="价格" rules={rules.price}>
              <InputNumber min={1} max={9999} precision={2} step={0.1} />
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default GoodsAdd;
