// v2_el/src/views/goods/GoodsView.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="goodsForm" label-width="150px" disabled="disabled">
      <el-row>
        <el-col :span="11">
          <el-form-item label="商品名称">
            <el-input v-model="goodsForm.name"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="价格">
            <el-input v-model="goodsForm.price"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="创建时间">
            <el-input v-model="goodsForm.createTime"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="最后修改时间">
            <el-input v-model="goodsForm.modifyTime"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="12" :offset="6">
          <div class="form-button-container">
            <el-button @click="onBack" type="primary">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script>
import goodsApi from '@/api/goodsApi'
export default {
  name: 'GoodsView',
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      goodsForm: {
      }
    }
  },
  created () {
    if (this.id) {
      goodsApi.findById(this.id)
          .then(resp => {
            if (resp && resp.code === 1) {
              this.goodsForm = resp.data
            } else {
              this.$message.error('获取数据失败')
            }
          })
          .catch(error => {
            console.error('获取数据失败:', error)
          })
    }
  },
  methods: {
    onBack () {
      this.$emit('close-goods-view-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// react_antd/src/pages/goods/GoodsView.tsx
import React, {useEffect} from "react";
import {Button, Col, Form, Input, Modal, Row} from "antd";
import {Goods} from "@/types/resp/goods";

interface GoodsViewProps {
  visible: boolean;
  viewRow: object;
  onCloseGoodsView: () => void;
}

const GoodsView: React.FC<GoodsViewProps> = ({visible, viewRow, onCloseGoodsView}) => {

  const [form] = Form.useForm<Goods>();

  const onBack = () => {
    onCloseGoodsView()
  };

  useEffect(() => {
    if (!visible) {
      return
    }
    if (viewRow) {
      form.setFieldsValue(viewRow);
    }
  }, [viewRow]);

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onBack}>关闭</Button>
    </div>
  );

  return (
    <Modal title={"商品详情"} open={visible} onCancel={onCloseGoodsView}
        width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={form} labelCol={{span: 6}} disabled={true}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="name" label="商品名称">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="price" label="价格">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="createTime" label="创建时间">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="modifyTime" label="最后修改时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default GoodsView;
