// react_antd/src/pages/checkInRecordDetail/CheckInRecordDetailView.tsx
import React, {useEffect} from "react";
import {Button, Col, Form, Input, Modal, Row} from "antd";
import {CheckInRecordDetail} from "@/types/resp/checkInRecordDetail";

interface CheckInRecordDetailViewProps {
  visible: boolean;
  viewRow: object;
  onCloseCheckInRecordDetailView: () => void;
}

const CheckInRecordDetailView: React.FC<CheckInRecordDetailViewProps> = ({visible, viewRow, onCloseCheckInRecordDetailView}) => {

  const [form] = Form.useForm<CheckInRecordDetail>();

  const onBack = () => {
    onCloseCheckInRecordDetailView()
  };

  useEffect(() => {
    if (!visible) {
      return
    }
    if (viewRow) {
      form.setFieldsValue(viewRow);
    }
  }, [viewRow]);

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onBack}>关闭</Button>
    </div>
  );

  return (
    <Modal title={"入住消费商品详情"} open={visible} onCancel={onCloseCheckInRecordDetailView}
        width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={form} labelCol={{span: 6}} disabled={true}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="name" label="姓名">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="phone" label="联系电话">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="goodsName" label="商品名称">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="goodsPrice" label="价格">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="qty" label="数量">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="price" label="单价">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="amount" label="总价">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="createTime" label="创建时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default CheckInRecordDetailView;

// v2_el/src/views/checkInRecordDetail/CheckInRecordDetailView.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="checkInRecordDetailForm" label-width="150px" disabled="disabled">
      <el-row>
        <el-col :span="11">
          <el-form-item label="姓名">
            <el-input v-model="checkInRecordDetailForm.name"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="联系电话">
            <el-input v-model="checkInRecordDetailForm.phone"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="商品名称">
            <el-input v-model="checkInRecordDetailForm.goodsName"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="价格">
            <el-input v-model="checkInRecordDetailForm.goodsPrice"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="数量">
            <el-input v-model="checkInRecordDetailForm.qty"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="单价">
            <el-input v-model="checkInRecordDetailForm.price"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="总价">
            <el-input v-model="checkInRecordDetailForm.amount"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="创建时间">
            <el-input v-model="checkInRecordDetailForm.createTime"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="12" :offset="6">
          <div class="form-button-container">
            <el-button @click="onBack" type="primary">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script>
import checkInRecordDetailApi from '@/api/checkInRecordDetailApi'
export default {
  name: 'CheckInRecordDetailView',
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      checkInRecordDetailForm: {
      }
    }
  },
  created () {
    if (this.id) {
      checkInRecordDetailApi.findById(this.id)
          .then(resp => {
            if (resp && resp.code === 1) {
              this.checkInRecordDetailForm = resp.data
            } else {
              this.$message.error('获取数据失败')
            }
          })
          .catch(error => {
            console.error('获取数据失败:', error)
          })
    }
  },
  methods: {
    onBack () {
      this.$emit('close-check-in-record-detail-view-event')
    }
  }
}
</script>

<style lang="scss">
</style>
