// angular_ngzorro/src/app/check-in-record-detail/check-in-record-detail-add.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormControl, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {CheckInRecordDetailService} from '../../service/check-in-record-detail.service';
import {SharedModule} from '../shared.module';
import {CheckInRecordDetailForm} from '../../types/req/CheckInRecordDetailForm';
import {MODAL_WIDTH} from '../../const'
import {CheckInRecordSelectorComponent} from '../check-in-record/check-in-record-selector.component';
import {GoodsSelectorComponent} from '../goods/goods-selector.component';

@Component({
  selector: 'check-in-record-detail-add',
  imports: [
    CheckInRecordSelectorComponent,
    GoodsSelectorComponent,
    SharedModule
  ],
  templateUrl: './check-in-record-detail-add.component.html',
  standalone: true
})
export class CheckInRecordDetailAddComponent implements OnInit {
  checkInRecordDetailToSave:CheckInRecordDetailForm = {};
  checkInRecordDetailForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增入住消费商品'
  modalWidth: string = MODAL_WIDTH

  @ViewChild(CheckInRecordSelectorComponent, { static: false }) checkInRecordSelectorComponent!: CheckInRecordSelectorComponent;
  @ViewChild(GoodsSelectorComponent, { static: false }) goodsSelectorComponent!: GoodsSelectorComponent;

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private checkInRecordDetailService: CheckInRecordDetailService
  ) {}

  ngOnInit(): void {
    this.checkInRecordDetailForm = this.fb.group({
      checkInRecordId: [0],
      name: ['', [Validators.required]],
      phone: ['', [Validators.required]],
      goodsId: [0],
      goodsName: ['', [Validators.required]],
      goodsPrice: [0, [Validators.required]],
      qty: [0, [Validators.required]],
      price: [0, [Validators.required]],
      amount: [0],
    })

    const priceControl = this.checkInRecordDetailForm.get('price') as FormControl;
    const qtyControl = this.checkInRecordDetailForm.get('qty') as FormControl;

    priceControl.valueChanges.subscribe(() => {
      this.calculateTotal();
    });

    qtyControl.valueChanges.subscribe(() => {
      this.calculateTotal();
    });

    // 初始计算一次
    this.calculateTotal();
  }

  calculateTotal() {
    const qty = this.checkInRecordDetailForm.get('qty')?.value || 0;
    const price = this.checkInRecordDetailForm.get('price')?.value || 0;

    let amount = 0
    if (!isNaN(qty) && !isNaN(price)) {
      amount = qty * price;
    }
    this.checkInRecordDetailForm.patchValue({amount: amount});
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.checkInRecordDetailForm.controls) {
        this.checkInRecordDetailForm.controls[i].markAsDirty();
        this.checkInRecordDetailForm.controls[i].updateValueAndValidity();
      }
      if (!this.checkInRecordDetailForm.valid) {
        this.saveLoading = false
        return
      }
      this.checkInRecordDetailService.save(Object.assign(this.checkInRecordDetailToSave, this.checkInRecordDetailForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增入住消费商品'.slice()
    this.checkInRecordDetailForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改入住消费商品'
      this.saveLoading = true
      this.checkInRecordDetailService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.checkInRecordDetailToSave = resp.data
            this.checkInRecordDetailForm.patchValue(this.checkInRecordDetailToSave);
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }

  findCheckInRecord() {
    this.checkInRecordSelectorComponent.display()
  }

  handleCheckInRecordSelectedEvent(selectedCheckInRecord: { checkInRecordId?: number; name?: string;phone?: string; }) {
    if (selectedCheckInRecord && 'checkInRecordId' in selectedCheckInRecord) {
      this.checkInRecordDetailForm.patchValue(selectedCheckInRecord);
    }
  }

  findGoods() {
    this.goodsSelectorComponent.display()
  }

  handleGoodsSelectedEvent(selectedGoods: { goodsId?: number; goodsName?: string;goodsPrice?: number; }) {
    if (selectedGoods && 'goodsId' in selectedGoods) {
      this.checkInRecordDetailForm.patchValue(selectedGoods);
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="checkInRecordDetailForm" (keydown.enter)="$event.preventDefault()">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name" nzRequired>入住人员姓名</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择入住人员姓名'">
              <nz-input-group nzSearch [nzAddOnAfter]="nameSuffixIconButton">
                <input nz-input formControlName="name" placeholder="请选择入住人员姓名" readonly />
              </nz-input-group>
              <ng-template #nameSuffixIconButton>
                <button nz-button  nzType="primary" nzSearch (click)="findCheckInRecord()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="phone" nzRequired>入住人员联系电话</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择入住人员联系电话'">
              <nz-input-group nzSearch [nzAddOnAfter]="phoneSuffixIconButton">
                <input nz-input formControlName="phone" placeholder="请选择入住人员联系电话" readonly />
              </nz-input-group>
              <ng-template #phoneSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findCheckInRecord()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="goodsName" nzRequired>商品名称</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择商品名称'">
              <nz-input-group nzSearch [nzAddOnAfter]="goodsNameSuffixIconButton">
                <input nz-input formControlName="goodsName" placeholder="请选择商品名称" readonly />
              </nz-input-group>
              <ng-template #goodsNameSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findGoods()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="goodsPrice" nzRequired>商品价格</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择商品价格'">
              <nz-input-group nzSearch [nzAddOnAfter]="goodsPriceSuffixIconButton">
                <input nz-input formControlName="goodsPrice" placeholder="请选择商品价格" readonly />
              </nz-input-group>
              <ng-template #goodsPriceSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findGoods()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="qty" nzRequired>数量</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入数量'">
            <nz-input-number formControlName="qty" [nzMin]="1" [nzMax]="9999" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="price" nzRequired>单价</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入单价'">
            <nz-input-number formControlName="price" [nzMin]="1" [nzMax]="9999" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="amount">总价</nz-form-label>
            <nz-form-control>
            <nz-input-number formControlName="amount" [nzMin]="1" [nzMax]="99999999" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
<check-in-record-selector (checkInRecordSelectedEvent)="handleCheckInRecordSelectedEvent($event)"></check-in-record-selector>
<goods-selector (goodsSelectedEvent)="handleGoodsSelectedEvent($event)"></goods-selector>

// v2_el/src/views/checkInRecordDetail/CheckInRecordDetailAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="checkInRecordDetailForm" :label-width="formLabelWidth" ref="refCheckInRecordDetailForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="入住人员姓名" prop="name">
            <el-input v-model="checkInRecordDetailForm.name" placeholder="请选择入住人员姓名" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findCheckInRecord"></i>
            </el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="入住人员联系电话" prop="phone">
            <el-input v-model="checkInRecordDetailForm.phone" placeholder="请选择入住人员联系电话" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findCheckInRecord"></i>
            </el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="商品名称" prop="goodsName">
            <el-input v-model="checkInRecordDetailForm.goodsName" placeholder="请选择商品名称" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findGoods"></i>
            </el-input>
          </el-form-item>
        </el-col>
<!--        <el-col :span="11">-->
<!--          <el-form-item label="商品价格" prop="goodsPrice">-->
<!--            <el-input v-model="checkInRecordDetailForm.goodsPrice" placeholder="请选择商品价格" readonly="readonly">-->
<!--              <i slot="suffix" class="el-input__icon el-icon-search" @click="findGoods"></i>-->
<!--            </el-input>-->
<!--          </el-form-item>-->
<!--        </el-col>-->
        <el-col :span="11">
          <el-form-item label="数量" prop="qty">
            <el-input-number v-model="checkInRecordDetailForm.qty" :min="1" :max="99" @change="calculateAmount"></el-input-number>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="单价" prop="price">
            <el-input-number v-model="checkInRecordDetailForm.price" :min="1" :max="999999" @change="calculateAmount"></el-input-number>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="总价" prop="amount">
            <el-input v-model="checkInRecordDetailForm.amount" :disabled="true"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button type="primary" @click="onReset" plain>重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="checkInRecordSelectorVisible" v-if="checkInRecordSelectorVisible" title="入住记录选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <check-in-record-selector @check-in-record-selected-event="handleCheckInRecordSelectedEvent">
      </check-in-record-selector>
    </el-dialog>
    <el-dialog :visible.sync="goodsSelectorVisible" v-if="goodsSelectorVisible" title="商品选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <goods-selector @goods-selected-event="handleGoodsSelectedEvent">
      </goods-selector>
    </el-dialog>
  </div>
</template>

<script>
import checkInRecordDetailApi from '@/api/checkInRecordDetailApi'
import CheckInRecordSelector from "@/views/checkInRecord/CheckInRecordSelector.vue";
import GoodsSelector from "@/views/goods/GoodsSelector.vue";
export default {
  name: 'CheckInRecordDetailAdd',
  components: {CheckInRecordSelector,GoodsSelector,},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      checkInRecordDetailForm: {
        checkInRecordId: '',
        name: '',
        phone: '',
        goodsId: '',
        goodsName: '',
        goodsPrice: '',
        qty: '',
        price: '',
        amount: ''
      },
      rules: {
        name:[
          { required: true, message: '请输入入住人员姓名', trigger: 'blur' }
        ],
        phone:[
          { required: true, message: '请输入入住人员联系电话', trigger: 'blur' }
        ],
        goodsName:[
          { required: true, message: '请输入商品名称', trigger: 'blur' }
        ],
        goodsPrice:[
          { required: true, message: '请输入商品价格', trigger: 'blur' }
        ],
        qty:[
          { required: true, message: '请输入数量', trigger: 'blur' }
        ],
        price:[
          { required: true, message: '请输入单价', trigger: 'blur' }
        ],
      },
      checkInRecordSelectorVisible: false,
      goodsSelectorVisible: false,
    }
  },
  created () {
    if (this.id) {
      checkInRecordDetailApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.checkInRecordDetailForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  mounted() {
    this.calculateAmount()
  },
  methods: {
    onReset () {
      this.checkInRecordDetailForm = {
        checkInRecordId: '',
        name: '',
        phone: '',
        goodsId: '',
        goodsName: '',
        goodsPrice: '',
        qty: '',
        price: '',
        amount: ''
      }
      this.$emit('reset-check-in-record-detail-add-event')
    },
    onSave () {
      this.$refs.refCheckInRecordDetailForm.validate((valid) => {
        if (valid) {
          checkInRecordDetailApi.save(this.checkInRecordDetailForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-check-in-record-detail-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    findCheckInRecord () {
      this.checkInRecordSelectorVisible = true
    },
    handleCheckInRecordSelectedEvent (selectedCheckInRecord) {
      this.checkInRecordSelectorVisible = false
      if (selectedCheckInRecord && 'checkInRecordId' in selectedCheckInRecord && this.checkInRecordDetailForm.checkInRecordId !== selectedCheckInRecord['checkInRecordId']) {
        this.checkInRecordDetailForm.checkInRecordId = selectedCheckInRecord['checkInRecordId']
        this.checkInRecordDetailForm.name = selectedCheckInRecord['name']
        this.checkInRecordDetailForm.phone = selectedCheckInRecord['phone']
      }
    },
    findGoods () {
      this.goodsSelectorVisible = true
    },
    handleGoodsSelectedEvent (selectedGoods) {
      this.goodsSelectorVisible = false
      if (selectedGoods && 'goodsId' in selectedGoods && this.checkInRecordDetailForm.goodsId !== selectedGoods['goodsId']) {
        this.checkInRecordDetailForm.goodsId = selectedGoods['goodsId']
        this.checkInRecordDetailForm.goodsName = selectedGoods['goodsName']
        this.checkInRecordDetailForm.price = selectedGoods['goodsPrice']
        this.calculateAmount()
      }
    },
    onBack () {
      this.$emit('close-check-in-record-detail-add-event')
    },
    calculateAmount() {
      this.checkInRecordDetailForm.amount = parseFloat((this.checkInRecordDetailForm.qty * this.checkInRecordDetailForm.price).toFixed(2))
    }
  }
}
</script>

<style lang="scss">
</style>
