// react_antd/src/components/Header/Header.tsx
import React, {useCallback, useState} from 'react';
import styles from '@/components/Header/Header.module.less';
import {DownOutlined} from '@ant-design/icons';
import type {MenuProps} from 'antd';
import {Button, Dropdown, Form, Input, message, Modal, Space} from 'antd';
import {useNavigate} from "react-router-dom";
import {UpdatePassForm} from "@/types/req/updatePassForm";
import userApi from "@/api/userApi.ts";
import {Result} from "@/types/result";


interface HeaderProps {
  title: string;
}

// 定义校验规则
const rules = {
  oldPassword: [
    { required: true, message: '请输入原密码' },
  ],
  newPassword: [
    { required: true, message: '请输入新密码' }
  ],
  confirmNewPassword: [
    { required: true, message: '请再次输入新密码' }
  ]
};

const initialUpdatePassForm: UpdatePassForm = {
  oldPass: '',
  newPass: '',
  newPass2: ''
}

const Header: React.FC<HeaderProps> = ({title}) => {

  const navigate = useNavigate();

  const [messageApi, messageContextHolder] = message.useMessage();
  const [modal, modalContextHolder] = Modal.useModal();

  const handleLogout = useCallback(async () => {
    const confirmed = await modal.confirm({
      title: '提示',
      content: (
        <>
          确定要退出吗?
        </>
      ),
      okText: '确定',
      cancelText: '取消',
      type: 'warning'
    });

    if (confirmed) {
      userApi.logout()
        .then(() => {
          sessionStorage.removeItem('loginToken')
          sessionStorage.removeItem('uid')
          sessionStorage.removeItem('username')
          navigate('/Login');
        })
        .catch(error => {
          console.log('退出失败', error)
          messageApi.error('退出失败')
        })
    }
  }, [modal]);

  const items: MenuProps['items'] = [
    {
      key: '1',
      label: '修改密码',
      onClick: () => handleUpdatePass()
    },
    {
      key: '2',
      label: '退出',
      onClick: () => handleLogout()
    },
  ];

  const username = sessionStorage.getItem('username')

  const [isModalOpen, setIsModalOpen] = useState(false);

  const handleUpdatePass = () => {
    setIsModalOpen(true);
    form.resetFields()
  };

  const handleCancel = () => {
    setIsModalOpen(false);
  };

  const [form] = Form.useForm();
  const [updatePassForm, setUpdatePassForm] = useState(initialUpdatePassForm);
  const setOldPass = (oldPass: string) => {
    setUpdatePassForm({ ...updatePassForm, oldPass });
  };
  const setNewPass = (newPass: string) => {
    setUpdatePassForm({ ...updatePassForm, newPass });
  };
  const setNewPass2 = (newPass2: string) => {
    setUpdatePassForm({ ...updatePassForm, newPass2 });
  };


  const handleOk = async () => {
    try {
      await form.validateFields()
      if (updatePassForm.newPass !== updatePassForm.newPass2) {
        // 显示成功消息
        messageApi.error('两次密码输入不一致');
        return
      }
      const resp: Result<void> = await userApi.updatePass(updatePassForm)
      if (!resp || resp.code !== 1) {
        messageApi.error(resp && resp.msg ? resp.msg : '操作异常')
        return
      }

      messageApi.success('操作成功');

      setIsModalOpen(false);
    } catch (error) {
      console.error('There was an error submitting the form!', error);
    }
  };

  const customFooter = (
    <div className='custom-footer'>
      <Button key="custom-ok" type="primary" onClick={handleOk}>
        保存
      </Button>
      <Button key="custom-cancel" style={{marginLeft: 'var(--button-margin-left)'}} onClick={handleCancel}>
        取消
      </Button>
    </div>
  );


  return (
    <header className={styles.header}>
      {messageContextHolder}
      {modalContextHolder}
      <div className={styles.headerTitle}>{title}</div>
      <div className={styles.middle}><span>版权所有 &copy; 2024 - 2026 <a href="http://www.52ejn.com" target="_blank">源码学习网</a></span><a href="http://beian.miit.gov.cn" target="_blank">粤ICP备2024308896号-1</a></div>
      <div className={styles.headerNav}>
        <Dropdown menu={{ items }}>
          <a onClick={(e) => e.preventDefault()} className={styles.headerNavContent}>
            <Space>
              {username}
              <DownOutlined />
            </Space>
          </a>
        </Dropdown>
      </div>
      <Modal title="修改密码" open={isModalOpen} onOk={handleOk} onCancel={handleCancel} width={'50%'} footer={customFooter}>
        <Form form={form}
          initialValues={{ remember: true }}
          autoComplete="off">
          <Form.Item
            name="oldPass"
            label="原密码"
            rules={rules.oldPassword}
            labelCol={{ span: 4 }} // 设置标签的宽度为 6 列
            wrapperCol={{ span: 20 }} // 设置输入框的宽度为 18 列
          >
            <Input.Password value={updatePassForm.oldPass} onChange={(e) => setOldPass(e.target.value)}/>
          </Form.Item>

          <Form.Item
            name="newPassword"
            label="新密码"
            rules={rules.newPassword}
            labelCol={{ span: 4 }} // 设置标签的宽度为 6 列
            wrapperCol={{ span: 20 }} // 设置输入框的宽度为 18 列
          >
            <Input.Password value={updatePassForm.newPass} onChange={(e) => setNewPass(e.target.value)}/>
          </Form.Item>

          <Form.Item
            name="confirmNewPassword"
            label="新密码确认"
            dependencies={['newPassword']}
            rules={rules.confirmNewPassword}
            labelCol={{ span: 4 }} // 设置标签的宽度为 6 列
            wrapperCol={{ span: 20 }} // 设置输入框的宽度为 18 列
          >
            <Input.Password value={updatePassForm.newPass2} onChange={(e) => setNewPass2(e.target.value)}/>
          </Form.Item>
        </Form>
      </Modal>
    </header>
  );
};

export default Header;

// angular_ngzorro/src/app/layout/header/header.component.ts
import {Component, OnInit} from '@angular/core';
import {Router} from '@angular/router';
import {SharedModule} from '../../shared.module';
import {AuthService} from '../../../service/auth.service';
import {TITLE} from '../../../const';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {UpdatePassForm} from '../../../types/req/UpdatePassForm';
import {NzModalService} from 'ng-zorro-antd/modal';

@Component({
  selector: 'app-header',
  imports: [
    SharedModule
  ],
  templateUrl: './header.component.html',
  standalone: true,
  styleUrls: [
    './header.component.less',
  ]
})
export class HeaderComponent implements OnInit {
  title: string = TITLE
  username = sessionStorage.getItem('username')
  updatePassForm!: FormGroup;
  isVisible: boolean = false
  loading: boolean = false

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private authService: AuthService,
    private router: Router,
    private modal: NzModalService
  ) {}

  ngOnInit(): void {
    this.updatePassForm = this.fb.group({
      oldPass: ['', [Validators.required]],
      newPass: ['', [Validators.required]],
      newPass2: ['', [Validators.required]]
    })
  }

  handleUpdatePass() {
    this.isVisible = true
  }

  handleOk() {
    this.loading = true
    for (const i in this.updatePassForm.controls) {
      this.updatePassForm.controls[i].markAsDirty();
      this.updatePassForm.controls[i].updateValueAndValidity();
    }
    if (!this.updatePassForm.valid) {
      this.loading = false
      return
    }
    const formValue = this.updatePassForm.value;
    if (formValue.newPass !== formValue.newPass2) {
      this.message.error('两次密码输入不一致');
      this.loading = false
      return
    }
    this.authService.updatePass(new UpdatePassForm(formValue)).subscribe({
      next: (resp) => {
        if (!resp || resp.code !== 1) {
          this.message.error(resp && resp.msg ? resp.msg : '操作异常')
          return
        }
        this.message.success('操作成功');
      },
      error: (error) => {
        // 处理错误
        console.error('Login failed:', error);
      },
      complete: () => {
        this.loading = false
        this.handleCancel()
      }
    });
  }

  handleCancel() {
    this.isVisible = false
    this.resetForm();
  }

  private resetForm(): void {
    if (this.updatePassForm) {
      this.updatePassForm.reset();
    }
  }

  handleLogout() {
    this.modal.confirm({
      nzTitle: '<i>退出提示</i>',
      nzContent: '<b>确定要退出吗?</b>',
      nzOnOk: () => {
        this.authService.logout();
        sessionStorage.removeItem('loginToken')
        sessionStorage.removeItem('uid')
        sessionStorage.removeItem('username')
        this.router.navigate(['/login']);
      }
    });
  }

}

<nz-header class="no-padding">
  <div class="header">
    <div class="header-title">{{title}}</div>
    <div class="middle"><span>版权所有 &copy; 2024 - 2026 <a href="http://www.52ejn.com" target="_blank">源码学习网</a></span><a href="http://beian.miit.gov.cn" target="_blank">粤ICP备2024308896号-1</a></div>
    <div class="header-nav">
      <a nz-dropdown [nzDropdownMenu]="menu" class="header-nav-content">
        {{ username }}
        <nz-icon nzType="down" />
      </a>
      <nz-dropdown-menu #menu="nzDropdownMenu">
        <ul nz-menu>
          <li nz-menu-item (click)="handleUpdatePass()">修改密码</li>
          <li nz-menu-item (click)="handleLogout()">退出</li>
        </ul>
      </nz-dropdown-menu>
    </div>
  </div>
  <nz-modal [(nzVisible)]="isVisible" [nzWidth]="'50%'" nzTitle="修改密码" (nzOnCancel)="handleCancel()" (nzOnOk)="handleOk()">
    <ng-container *nzModalContent>
      <form [formGroup]="updatePassForm" (ngSubmit)="handleOk()" (keydown.enter)="handleOk()">
        <nz-form-item>
          <nz-form-label nzRequired [nzSpan]="4" nzFor="oldPass">原密码</nz-form-label>
          <nz-form-control [nzErrorTip]="'请输入原密码'">
            <input nz-input formControlName="oldPass" placeholder="请输入原密码" />
          </nz-form-control>
        </nz-form-item>
        <nz-form-item>
          <nz-form-label nzRequired [nzSpan]="4" nzFor="newPass">新密码</nz-form-label>
          <nz-form-control [nzErrorTip]="'请输入新密码'">
            <input nz-input type="password" formControlName="newPass" placeholder="请输入新密码" />
          </nz-form-control>
        </nz-form-item>
        <nz-form-item>
          <nz-form-label nzRequired [nzSpan]="4" nzFor="newPass2">新密码确认</nz-form-label>
          <nz-form-control [nzErrorTip]="'请再次输入新密码'">
            <input nz-input formControlName="newPass2" placeholder="请再次输入新密码" />
          </nz-form-control>
        </nz-form-item>
      </form>
    </ng-container>
    <div *nzModalFooter>
      <div class="form-button-container">
        <button nz-button nzType="primary" (click)="handleOk()" [nzLoading]="loading">保存</button>
        <button nz-button nzType="default" (click)="handleCancel()">取消</button>
      </div>
    </div>
  </nz-modal>
</nz-header>
