// v2_el/src/views/room/RoomView.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="roomForm" label-width="150px" disabled="disabled">
      <el-row>
        <el-col :span="11">
          <el-form-item label="房号">
            <el-input v-model="roomForm.roomNumber"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="房型">
            <el-select v-model="roomForm.roomType" placeholder="请选择房型">
              <el-option label="标准单人间" :value="10"></el-option>
              <el-option label="豪华单人间" :value="11"></el-option>
              <el-option label="标准双人间" :value="20"></el-option>
              <el-option label="豪华双人间" :value="21"></el-option>
              <el-option label="标准套房" :value="90"></el-option>
              <el-option label="豪华套房" :value="91"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="状态">
            <el-select v-model="roomForm.status" placeholder="请选择状态">
              <el-option label="空房" :value="10"></el-option>
              <el-option label="已预定" :value="20"></el-option>
              <el-option label="已入住" :value="30"></el-option>
              <el-option label="已退房(待清理)" :value="40"></el-option>
              <el-option label="维修中" :value="50"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="价格">
            <el-input v-model="roomForm.price"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="面积">
            <el-input v-model="roomForm.area"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="楼层">
            <el-input v-model="roomForm.floorNumber"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="床型">
            <el-input v-model="roomForm.bedType"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="入住人数">
            <el-input v-model="roomForm.maxOccupancy"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="wifi是否免费">
            <el-select v-model="roomForm.freeWifi" placeholder="请选择wifi是否免费">
              <el-option label="否" :value="0"></el-option>
              <el-option label="是" :value="1"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="是否有窗">
            <el-select v-model="roomForm.existWindow" placeholder="请选择是否有窗">
              <el-option label="否" :value="0"></el-option>
              <el-option label="是" :value="1"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="是否有免费早餐">
            <el-select v-model="roomForm.freeBreakfast" placeholder="请选择是否有免费早餐">
              <el-option label="否" :value="0"></el-option>
              <el-option label="是" :value="1"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="创建时间">
            <el-input v-model="roomForm.createTime"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="最后修改时间">
            <el-input v-model="roomForm.modifyTime"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="12" :offset="6">
          <div class="form-button-container">
            <el-button @click="onBack" type="primary">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script>
import roomApi from '@/api/roomApi'
export default {
  name: 'RoomView',
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      roomForm: {
      }
    }
  },
  created () {
    if (this.id) {
      roomApi.findById(this.id)
          .then(resp => {
            if (resp && resp.code === 1) {
              this.roomForm = resp.data
            } else {
              this.$message.error('获取数据失败')
            }
          })
          .catch(error => {
            console.error('获取数据失败:', error)
          })
    }
  },
  methods: {
    onBack () {
      this.$emit('close-room-view-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// react_antd/src/pages/room/RoomView.tsx
import React, {useEffect} from "react";
import {Button, Col, Form, Input, Modal, Row, Select} from "antd";
import {Room} from "@/types/resp/room";

interface RoomViewProps {
  visible: boolean;
  viewRow: object;
  onCloseRoomView: () => void;
}

const RoomView: React.FC<RoomViewProps> = ({visible, viewRow, onCloseRoomView}) => {

  const [form] = Form.useForm<Room>();

  const onBack = () => {
    onCloseRoomView()
  };

  useEffect(() => {
    if (!visible) {
      return
    }
    if (viewRow) {
      form.setFieldsValue(viewRow);
    }
  }, [viewRow]);

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onBack}>关闭</Button>
    </div>
  );

  return (
    <Modal title={"房间详情"} open={visible} onCancel={onCloseRoomView}
        width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={form} labelCol={{span: 6}} disabled={true}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="roomNumber" label="房号">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="roomType" label="房型">
              <Select placeholder="请选择房型" options={[
                { value: 10, label: <span>标准单人间</span> },
                { value: 11, label: <span>豪华单人间</span> },
                { value: 20, label: <span>标准双人间</span> },
                { value: 21, label: <span>豪华双人间</span> },
                { value: 90, label: <span>标准套房</span> },
                { value: 91, label: <span>豪华套房</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="status" label="状态">
              <Select placeholder="请选择状态" options={[
                { value: 10, label: <span>空房</span> },
                { value: 20, label: <span>已预定</span> },
                { value: 30, label: <span>已入住</span> },
                { value: 40, label: <span>已退房(待清理)</span> },
                { value: 50, label: <span>维修中</span> }
              ]} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="price" label="价格">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="area" label="面积">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="floorNumber" label="楼层">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="bedType" label="床型">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="maxOccupancy" label="入住人数">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="freeWifi" label="wifi是否免费">
              <Select placeholder="请选择wifi是否免费" options={[
                { value: 0, label: <span>否</span> },
                { value: 1, label: <span>是</span> }
              ]} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="existWindow" label="是否有窗">
              <Select placeholder="请选择是否有窗" options={[
                { value: 0, label: <span>否</span> },
                { value: 1, label: <span>是</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="freeBreakfast" label="是否有免费早餐">
              <Select placeholder="请选择是否有免费早餐" options={[
                { value: 0, label: <span>否</span> },
                { value: 1, label: <span>是</span> }
              ]} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="createTime" label="创建时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="modifyTime" label="最后修改时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default RoomView;
