// angular_ngzorro/src/app/room/room-view.component.ts
import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {SharedModule} from '../shared.module';
import {MODAL_WIDTH} from '../../const'
import {Room} from '../../types/resp/Room';

@Component({
  selector: 'room-view',
  imports: [
    SharedModule
  ],
  templateUrl: './room-view.component.html',
  standalone: true
})
export class RoomViewComponent implements OnInit {
  roomForm!: FormGroup;
  isVisible: boolean = false
  title: string = '房间详情'
  modalWidth: string = MODAL_WIDTH

  constructor(
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.roomForm = this.fb.group({
      roomNumber: [''],
      roomType: [undefined],
      status: [undefined],
      price: [0],
      area: [''],
      floorNumber: [''],
      bedType: [''],
      maxOccupancy: [0],
      freeWifi: [undefined],
      existWindow: [undefined],
      freeBreakfast: [undefined],
      createTime: [''],
      modifyTime: [''],
    })
  }

  onBack() {
    this.isVisible = false
  }

  display(room: Room) {
    this.isVisible = true
    this.roomForm.patchValue(room);
    this.roomForm.disable();
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="roomForm">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomNumber">房号</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="roomNumber" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomType">房型</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="roomType">
                <nz-option nzLabel="标准单人间" [nzValue]="10"></nz-option>
                <nz-option nzLabel="豪华单人间" [nzValue]="11"></nz-option>
                <nz-option nzLabel="标准双人间" [nzValue]="20"></nz-option>
                <nz-option nzLabel="豪华双人间" [nzValue]="21"></nz-option>
                <nz-option nzLabel="标准套房" [nzValue]="90"></nz-option>
                <nz-option nzLabel="豪华套房" [nzValue]="91"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="status">状态</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="status">
                <nz-option nzLabel="空房" [nzValue]="10"></nz-option>
                <nz-option nzLabel="已预定" [nzValue]="20"></nz-option>
                <nz-option nzLabel="已入住" [nzValue]="30"></nz-option>
                <nz-option nzLabel="已退房(待清理)" [nzValue]="40"></nz-option>
                <nz-option nzLabel="维修中" [nzValue]="50"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="price">价格</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="price" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="area">面积</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="area" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="floorNumber">楼层</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="floorNumber" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="bedType">床型</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="bedType" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="maxOccupancy">入住人数</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="maxOccupancy" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="freeWifi">wifi是否免费</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="freeWifi">
                <nz-option nzLabel="否" [nzValue]="0"></nz-option>
                <nz-option nzLabel="是" [nzValue]="1"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="existWindow">是否有窗</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="existWindow">
                <nz-option nzLabel="否" [nzValue]="0"></nz-option>
                <nz-option nzLabel="是" [nzValue]="1"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="freeBreakfast">是否有免费早餐</nz-form-label>
            <nz-form-control>
              <nz-select formControlName="freeBreakfast">
                <nz-option nzLabel="否" [nzValue]="0"></nz-option>
                <nz-option nzLabel="是" [nzValue]="1"></nz-option>
              </nz-select>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="createTime">创建时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="createTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="modifyTime">最后修改时间</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="modifyTime" />
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>

// react_antd/src/pages/room/RoomView.tsx
import React, {useEffect} from "react";
import {Button, Col, Form, Input, Modal, Row, Select} from "antd";
import {Room} from "@/types/resp/room";

interface RoomViewProps {
  visible: boolean;
  viewRow: object;
  onCloseRoomView: () => void;
}

const RoomView: React.FC<RoomViewProps> = ({visible, viewRow, onCloseRoomView}) => {

  const [form] = Form.useForm<Room>();

  const onBack = () => {
    onCloseRoomView()
  };

  useEffect(() => {
    if (!visible) {
      return
    }
    if (viewRow) {
      form.setFieldsValue(viewRow);
    }
  }, [viewRow]);

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onBack}>关闭</Button>
    </div>
  );

  return (
    <Modal title={"房间详情"} open={visible} onCancel={onCloseRoomView}
        width={'var(--modal-width)'} footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={form} labelCol={{span: 6}} disabled={true}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="roomNumber" label="房号">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="roomType" label="房型">
              <Select placeholder="请选择房型" options={[
                { value: 10, label: <span>标准单人间</span> },
                { value: 11, label: <span>豪华单人间</span> },
                { value: 20, label: <span>标准双人间</span> },
                { value: 21, label: <span>豪华双人间</span> },
                { value: 90, label: <span>标准套房</span> },
                { value: 91, label: <span>豪华套房</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="status" label="状态">
              <Select placeholder="请选择状态" options={[
                { value: 10, label: <span>空房</span> },
                { value: 20, label: <span>已预定</span> },
                { value: 30, label: <span>已入住</span> },
                { value: 40, label: <span>已退房(待清理)</span> },
                { value: 50, label: <span>维修中</span> }
              ]} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="price" label="价格">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="area" label="面积">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="floorNumber" label="楼层">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="bedType" label="床型">
              <Input/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="maxOccupancy" label="入住人数">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="freeWifi" label="wifi是否免费">
              <Select placeholder="请选择wifi是否免费" options={[
                { value: 0, label: <span>否</span> },
                { value: 1, label: <span>是</span> }
              ]} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="existWindow" label="是否有窗">
              <Select placeholder="请选择是否有窗" options={[
                { value: 0, label: <span>否</span> },
                { value: 1, label: <span>是</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="freeBreakfast" label="是否有免费早餐">
              <Select placeholder="请选择是否有免费早餐" options={[
                { value: 0, label: <span>否</span> },
                { value: 1, label: <span>是</span> }
              ]} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="createTime" label="创建时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="modifyTime" label="最后修改时间">
              <Input/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default RoomView;
