// angular_ngzorro/src/app/room/room-selector.component.ts
import {Component, EventEmitter, OnInit, Output} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {RoomService} from '../../service/room.service';
import {RoomQueryForm} from '../../types/req/RoomQueryForm';
import {SharedModule} from '../shared.module';
import {Room} from '../../types/resp/Room';
import {Page} from '../../types/page';
import {NzModalService} from 'ng-zorro-antd/modal';
import {MODAL_WIDTH} from '../../const';

@Component({
  selector: 'room-selector',
  imports: [
    SharedModule
  ],
  templateUrl: './room-selector.component.html',
  standalone: true
})
export class RoomSelectorComponent implements OnInit {
  searchForm!: FormGroup;
  searchLoading: boolean = false
  listOfData: Room[] = [];
  total: number = 0
  isVisible: boolean = false
  title: string = '房间选择器(双击行选中)'
  modalWidth: string = MODAL_WIDTH


  @Output() roomSelectedEvent = new EventEmitter<{}>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private roomService: RoomService,
    private modal: NzModalService
  ) {}

  ngOnInit(): void {
    this.searchForm = this.fb.group({
      roomNumber: [''],
      roomType: [undefined],
      status: [undefined],
    })
    this.onSearch()
  }

  onReset() {
    this.searchForm.reset()
  }

  onSearch() {
    try {
      this.searchLoading = true
      this.roomService.find(new RoomQueryForm(this.searchForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          const page: Page<Room> | undefined = resp.data
          if (page && page.list.length > 0) {
            this.listOfData = page.list
            this.total = page.total
          }
        },
        complete: () => {
          this.searchLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onRowDblClick(row: Room, event: MouseEvent) {
    this.isVisible = false
    this.roomSelectedEvent.emit({
      roomId: row.id,
      roomNumber: row.roomNumber,
    });
  }

  onBack() {
    this.isVisible = false
  }

  display() {
    this.isVisible = true
    this.searchForm.reset();
  }

}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form nz-form class="search-form" [formGroup]="searchForm" (keydown.enter)="onSearch()" nzLayout="inline">
      <nz-form-item>
        <nz-form-label nzFor="roomNumber">房号</nz-form-label>
        <nz-form-control>
          <input nz-input formControlName="roomNumber" placeholder="请输入房号" />
        </nz-form-control>
      </nz-form-item>
      <nz-form-item>
        <nz-form-label nzFor="roomType">房型</nz-form-label>
        <nz-form-control>
          <nz-select formControlName="roomType" class="custom-select-width">
            <nz-option nzLabel="标准单人间" [nzValue]="10"></nz-option>
            <nz-option nzLabel="豪华单人间" [nzValue]="11"></nz-option>
            <nz-option nzLabel="标准双人间" [nzValue]="20"></nz-option>
            <nz-option nzLabel="豪华双人间" [nzValue]="21"></nz-option>
            <nz-option nzLabel="标准套房" [nzValue]="90"></nz-option>
            <nz-option nzLabel="豪华套房" [nzValue]="91"></nz-option>
          </nz-select>
        </nz-form-control>
      </nz-form-item>
      <nz-form-item>
        <nz-form-label nzFor="status">状态</nz-form-label>
        <nz-form-control>
          <nz-select formControlName="status" class="custom-select-width">
            <nz-option nzLabel="空房" [nzValue]="10"></nz-option>
            <nz-option nzLabel="已预定" [nzValue]="20"></nz-option>
            <nz-option nzLabel="已入住" [nzValue]="30"></nz-option>
            <nz-option nzLabel="已退房(待清理)" [nzValue]="40"></nz-option>
            <nz-option nzLabel="维修中" [nzValue]="50"></nz-option>
          </nz-select>
        </nz-form-control>
      </nz-form-item>
      <button nz-button type="button" nzType="primary" [nzLoading]="searchLoading" (click)="onSearch()">查询</button>
      <button nz-button type="button" class="margin-button" (click)="onReset()">重置</button>
    </form>
    <nz-table #basicTable [nzData]="listOfData" [nzTotal]="total" [nzLoading]="searchLoading" nzSize="small">
      <thead>
        <tr>
          <th>房号</th>
          <th>房型</th>
          <th>状态</th>
          <th>价格</th>
          <th>面积</th>
          <th>楼层</th>
          <th>床型</th>
          <th>入住人数</th>
          <th>wifi是否免费</th>
          <th>是否有窗</th>
          <th>是否有免费早餐</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let data of basicTable.data" (dblclick)="onRowDblClick(data, $event)">
          <td>{{data.roomNumber}}</td>
          <td>
            <ng-container *ngIf="data.roomType === 10">标准单人间</ng-container>
            <ng-container *ngIf="data.roomType === 11">豪华单人间</ng-container>
            <ng-container *ngIf="data.roomType === 20">标准双人间</ng-container>
            <ng-container *ngIf="data.roomType === 21">豪华双人间</ng-container>
            <ng-container *ngIf="data.roomType === 90">标准套房</ng-container>
            <ng-container *ngIf="data.roomType === 91">豪华套房</ng-container>
          </td>
          <td>
            <ng-container *ngIf="data.status === 10">空房</ng-container>
            <ng-container *ngIf="data.status === 20">已预定</ng-container>
            <ng-container *ngIf="data.status === 30">已入住</ng-container>
            <ng-container *ngIf="data.status === 40">已退房(待清理)</ng-container>
            <ng-container *ngIf="data.status === 50">维修中</ng-container>
          </td>
          <td>{{data.price}}</td>
          <td>{{data.area}}</td>
          <td>{{data.floorNumber}}</td>
          <td>{{data.bedType}}</td>
          <td>{{data.maxOccupancy}}</td>
          <td>
            <ng-container *ngIf="data.freeWifi === 0">否</ng-container>
            <ng-container *ngIf="data.freeWifi === 1">是</ng-container>
          </td>
          <td>
            <ng-container *ngIf="data.existWindow === 0">否</ng-container>
            <ng-container *ngIf="data.existWindow === 1">是</ng-container>
          </td>
          <td>
            <ng-container *ngIf="data.freeBreakfast === 0">否</ng-container>
            <ng-container *ngIf="data.freeBreakfast === 1">是</ng-container>
          </td>
        </tr>
      </tbody>
    </nz-table>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>

// react_antd/src/pages/room/RoomSelector.tsx
import React, {useEffect, useState} from 'react';
import {Button, Form, Input, Modal, Select, Table, TableProps} from 'antd';
import type {Room} from "@/types/resp/room";
import roomApi from '@/api/roomApi'
import {Result} from "@/types/result";
import {Page} from "@/types/page";


interface RoomSelectorProps {
  visible: boolean;
  onRoomSelected: (selectedRoom: { roomId?: number; roomNumber?: string; }) => void;
  onCloseRoomSelector: () => void;
}

const RoomSelector: React.FC<RoomSelectorProps> = ({visible, onRoomSelected, onCloseRoomSelector}) => {

  const [roomSelectorForm] = Form.useForm();

  const onFinish = async () => {
    await onSearch()
  };

  const onReset = () => {
    roomSelectorForm.resetFields();
  };

  const [data, setData] = useState<Room[]>([]);
  const onSearch = async () => {
    try {
      const resp: Result<Page<Room>> = await roomApi.find(roomSelectorForm.getFieldsValue())
      if (resp && resp.code === 1) {
        if (resp.data) {
          const page: Page<Room> = resp.data
          if (page && page.list.length > 0) {
            setData(page.list)
          }
        }
      }
    } catch (e) {
      console.log('获取数据异常', e)
    }
  };

  const columns: TableProps<Room>['columns'] = [
    {title: '房号', dataIndex: 'roomNumber', key: 'roomNumber'},
    {title: '房型', key: 'roomType', render: (_, record) => (
        <span>
        {(function () {
          if (record.roomType === 10) return '标准单人间';
          else if (record.roomType === 11) return '豪华单人间';
          else if (record.roomType === 20) return '标准双人间';
          else if (record.roomType === 21) return '豪华双人间';
          else if (record.roomType === 90) return '标准套房';
          else if (record.roomType === 91) return '豪华套房';
          else return '未知';
        })()}
      </span>
      ),
    },
    {title: '状态', key: 'status', render: (_, record) => (
        <span>
        {(function () {
          if (record.status === 10) return '空房';
          else if (record.status === 20) return '已预定';
          else if (record.status === 30) return '已入住';
          else if (record.status === 40) return '已退房(待清理)';
          else if (record.status === 50) return '维修中';
          else return '未知';
        })()}
      </span>
      ),
    },
    {title: '价格', dataIndex: 'price', key: 'price'},
    {title: '面积', dataIndex: 'area', key: 'area'},
    {title: '楼层', dataIndex: 'floorNumber', key: 'floorNumber'},
    {title: '床型', dataIndex: 'bedType', key: 'bedType'},
    {title: '入住人数', dataIndex: 'maxOccupancy', key: 'maxOccupancy'},
    {title: 'wifi是否免费', key: 'freeWifi', render: (_, record) => (
        <span>
        {(function () {
          if (record.freeWifi === 0) return '否';
          else if (record.freeWifi === 1) return '是';
          else return '未知';
        })()}
      </span>
      ),
    },
    {title: '是否有窗', key: 'existWindow', render: (_, record) => (
        <span>
        {(function () {
          if (record.existWindow === 0) return '否';
          else if (record.existWindow === 1) return '是';
          else return '未知';
        })()}
      </span>
      ),
    },
    {title: '是否有免费早餐', key: 'freeBreakfast', render: (_, record) => (
        <span>
        {(function () {
          if (record.freeBreakfast === 0) return '否';
          else if (record.freeBreakfast === 1) return '是';
          else return '未知';
        })()}
      </span>
      ),
    },
  ];

  const handleRowDoubleClick = (row: Room) => {
    onRoomSelected({
      roomId: row.id,
      roomNumber: row.roomNumber,
    })
  };

  const selectorFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onCloseRoomSelector}>关闭</Button>
    </div>
  );

  useEffect(() => {
    if (visible) {
      onSearch();
    }
  }, [visible]);


  return (
    <Modal title={"房间选择器(双击行选中)"} open={visible} onCancel={onCloseRoomSelector}
        width={'var(--modal-width)'} footer={selectorFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={roomSelectorForm} onFinish={onFinish} layout={"inline"}>
        <Form.Item name="roomNumber" label="房号">
          <Input maxLength={32} placeholder="请输入房号"/>
        </Form.Item>
        <Form.Item name="roomType" label="房型">
          <Select placeholder="请选择房型" options={[
            { value: 10, label: <span>标准单人间</span> },
            { value: 11, label: <span>豪华单人间</span> },
            { value: 20, label: <span>标准双人间</span> },
            { value: 21, label: <span>豪华双人间</span> },
            { value: 90, label: <span>标准套房</span> },
            { value: 91, label: <span>豪华套房</span> }
          ]} style={{width: 'var(--select-width)'}} />
        </Form.Item>
        <Form.Item name="status" label="状态">
          <Select placeholder="请选择状态" options={[
            { value: 10, label: <span>空房</span> },
            { value: 20, label: <span>已预定</span> },
            { value: 30, label: <span>已入住</span> },
            { value: 40, label: <span>已退房(待清理)</span> },
            { value: 50, label: <span>维修中</span> }
          ]} style={{width: 'var(--select-width)'}} />
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" htmlType="submit">查询</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button onClick={onReset}>重置</Button>
        </Form.Item>
      </Form>
      <Table<Room> columns={columns} dataSource={data} size="small" rowKey={record => record.id}
                         pagination={{ position: ["bottomCenter"] }}
                         onRow={(row) => ({
                           onDoubleClick: (event) => {
                             event.preventDefault();
                             handleRowDoubleClick(row);
                           },
                         })}/>
    </Modal>
  );
};

export default RoomSelector;
