// v2_el/src/views/room/RoomAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="roomForm" :label-width="formLabelWidth" ref="refRoomForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="房号" prop="roomNumber">
            <el-input v-model="roomForm.roomNumber" placeholder="请输入房号" maxlength="32"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="房型" prop="roomType">
            <el-select v-model="roomForm.roomType" placeholder="请选择房型">
              <el-option label="标准单人间" :value="10"></el-option>
              <el-option label="豪华单人间" :value="11"></el-option>
              <el-option label="标准双人间" :value="20"></el-option>
              <el-option label="豪华双人间" :value="21"></el-option>
              <el-option label="标准套房" :value="90"></el-option>
              <el-option label="豪华套房" :value="91"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="价格" prop="price">
            <el-input-number v-model="roomForm.price" :precision="2" :step="0.1" :min="1" :max="99999999"></el-input-number>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="面积" prop="area">
            <el-input v-model="roomForm.area" placeholder="请输入面积" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="楼层" prop="floorNumber">
            <el-input v-model="roomForm.floorNumber" placeholder="请输入楼层" maxlength="32"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="床型" prop="bedType">
            <el-input v-model="roomForm.bedType" placeholder="请输入床型" maxlength="50"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="入住人数" prop="maxOccupancy">
            <el-input-number v-model="roomForm.maxOccupancy" :min="1" :max="10"></el-input-number>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="wifi是否免费" prop="freeWifi">
            <el-select v-model="roomForm.freeWifi" placeholder="请选择wifi是否免费">
              <el-option label="否" :value="0"></el-option>
              <el-option label="是" :value="1"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="是否有窗" prop="existWindow">
            <el-select v-model="roomForm.existWindow" placeholder="请选择是否有窗">
              <el-option label="否" :value="0"></el-option>
              <el-option label="是" :value="1"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="是否有免费早餐" prop="freeBreakfast">
            <el-select v-model="roomForm.freeBreakfast" placeholder="请选择是否有免费早餐">
              <el-option label="否" :value="0"></el-option>
              <el-option label="是" :value="1"></el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button type="primary" @click="onReset" plain>重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script>
import roomApi from '@/api/roomApi'
export default {
  name: 'RoomAdd',
  components: {},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      roomForm: {
        roomNumber: '',
        roomType: '',
        price: '',
        area: '',
        floorNumber: '',
        bedType: '',
        maxOccupancy: '',
        freeWifi: '',
        existWindow: '',
        freeBreakfast: ''
      },
      rules: {
        roomNumber:[
          { required: true, message: '请输入房号', trigger: 'blur' }
        ],
        roomType:[
          { required: true, message: '请输入房型', trigger: 'blur' }
        ],
      },
    }
  },
  created () {
    if (this.id) {
      roomApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.roomForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.roomForm = {
        roomNumber: '',
        roomType: '',
        price: '',
        area: '',
        floorNumber: '',
        bedType: '',
        maxOccupancy: '',
        freeWifi: '',
        existWindow: '',
        freeBreakfast: ''
      }
      this.$emit('reset-room-add-event')
    },
    onSave () {
      this.$refs.refRoomForm.validate((valid) => {
        if (valid) {
          roomApi.save(this.roomForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-room-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    onBack () {
      this.$emit('close-room-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// react_antd/src/pages/room/RoomAdd.tsx
import React, {useEffect, useState} from "react";
import {Button, Col, Form, Input, InputNumber, message, Modal, Row, Select} from "antd";
import type {Result} from "@/types/result";
import roomApi from "@/api/roomApi.ts";
import {Room} from "@/types/resp/room";

interface RoomAddProps {
  visible: boolean;
  id: number;
  onCloseRoomAdd: () => void;
}

const RoomAdd: React.FC<RoomAddProps> = ({visible, id, onCloseRoomAdd}) => {

  const [form] = Form.useForm<Room>();
  const [messageApi, messageContextHolder] = message.useMessage();

  const rules = {
    roomNumber: [
      { required: true, message: '请输入房号' }
    ],
    roomType: [
      { required: true, message: '请输入房型' }
    ],
  };

  let roomForm: Partial<Room> = {}

  const [title, setTitle] = useState('新增房间');

  useEffect(() => {
    if (!visible) {
      return
    }
    if (id) {
      setTitle('编辑房间')
      initRoomFormById(id)
    } else {
      setTitle('新增房间')
      form.resetFields();
    }
  }, [visible]);

  const initRoomFormById = async (id: number) => {
    const resp: Result<Room> = await roomApi.findById(id)
    if (resp && resp.code === 1 && resp.data) {
      roomForm = resp.data
      form.setFieldsValue(resp.data);
    }
  }

  const onSave = async () => {
    try {
      await form.validateFields()

      let room2Save:Room = form.getFieldsValue()
      if (id) {
        room2Save = Object.assign(roomForm, room2Save)
      }
      const resp: Result<void> = await roomApi.save(room2Save);
      if (!resp || resp.code !== 1) {
        messageApi.error('保存失败:' + (resp.msg ? resp.msg : '未知异常'));
        return
      }
      messageApi.success('保存成功');
      onBack()
    } catch (error) {
      console.error('There was an error submitting the form!', error);
    }
  };

  const onReset = () => {
    setTitle('新增房间')
    form.resetFields();
  };
  

  const onBack = () => {
    onCloseRoomAdd()
  };

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onSave}>保存</Button>
      <Button onClick={onReset} style={{marginLeft: 'var(--button-margin-left)'}}>重置</Button>
      <Button type="primary" onClick={onBack} style={{marginLeft: 'var(--button-margin-left)'}}>关闭</Button>
    </div>
  );

  return (
    <Modal title={title} open={visible} onCancel={onCloseRoomAdd} width={'var(--modal-width)'}
        footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      {messageContextHolder}
      <Form form={form} name="roomForm" labelCol={{span: 6}}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="roomNumber" label="房号" rules={rules.roomNumber}>
              <Input maxLength={32} placeholder="请输入房号"/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="roomType" label="房型" rules={rules.roomType}>
              <Select placeholder="请选择房型" options={[
                { value: 10, label: <span>标准单人间</span> },
                { value: 11, label: <span>豪华单人间</span> },
                { value: 20, label: <span>标准双人间</span> },
                { value: 21, label: <span>豪华双人间</span> },
                { value: 90, label: <span>标准套房</span> },
                { value: 91, label: <span>豪华套房</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="price" label="价格">
              <InputNumber min={1} max={99999999} precision={2} step={0.1} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="area" label="面积">
              <Input maxLength={64} placeholder="请输入面积"/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="floorNumber" label="楼层">
              <Input maxLength={32} placeholder="请输入楼层"/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="bedType" label="床型">
              <Input maxLength={50} placeholder="请输入床型"/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="maxOccupancy" label="入住人数">
              <InputNumber min={1} max={10} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="freeWifi" label="wifi是否免费">
              <Select placeholder="请选择wifi是否免费" options={[
                { value: 0, label: <span>否</span> },
                { value: 1, label: <span>是</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="existWindow" label="是否有窗">
              <Select placeholder="请选择是否有窗" options={[
                { value: 0, label: <span>否</span> },
                { value: 1, label: <span>是</span> }
              ]} />
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="freeBreakfast" label="是否有免费早餐">
              <Select placeholder="请选择是否有免费早餐" options={[
                { value: 0, label: <span>否</span> },
                { value: 1, label: <span>是</span> }
              ]} />
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default RoomAdd;
