// angular_ngzorro/src/app/staff/staff-add.component.ts
import {Component, EventEmitter, OnInit, Output} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {StaffService} from '../../service/staff.service';
import {SharedModule} from '../shared.module';
import {StaffForm} from '../../types/req/StaffForm';
import {MODAL_WIDTH} from '../../const'

@Component({
  selector: 'staff-add',
  imports: [
    SharedModule
  ],
  templateUrl: './staff-add.component.html',
  standalone: true
})
export class StaffAddComponent implements OnInit {
  staffToSave:StaffForm = {};
  staffForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增员工'
  modalWidth: string = MODAL_WIDTH

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private staffService: StaffService
  ) {}

  ngOnInit(): void {
    this.staffForm = this.fb.group({
      name: ['', [Validators.required]],
      phone: [''],
      position: [''],
      specialty: [''],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.staffForm.controls) {
        this.staffForm.controls[i].markAsDirty();
        this.staffForm.controls[i].updateValueAndValidity();
      }
      if (!this.staffForm.valid) {
        this.saveLoading = false
        return
      }
      this.staffService.save(Object.assign(this.staffToSave, this.staffForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增员工'.slice()
    this.staffForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改员工'
      this.saveLoading = true
      this.staffService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.staffToSave = resp.data
            this.staffForm.patchValue(this.staffToSave);
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="staffForm">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name" nzRequired>姓名</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入姓名'">
              <input nz-input formControlName="name" placeholder="请输入姓名" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="phone">联系电话</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="phone" placeholder="请输入联系电话" maxlength="20"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="position">岗位</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="position" placeholder="请输入岗位" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="specialty">特长</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="specialty" placeholder="请输入特长" maxlength="255"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>

// react_antd/src/pages/staff/StaffAdd.tsx
import React, {useEffect, useState} from "react";
import {Button, Col, Form, Input, message, Modal, Row} from "antd";
import type {Result} from "@/types/result";
import staffApi from "@/api/staffApi.ts";
import {Staff} from "@/types/resp/staff";

interface StaffAddProps {
  visible: boolean;
  id: number;
  onCloseStaffAdd: () => void;
}

const StaffAdd: React.FC<StaffAddProps> = ({visible, id, onCloseStaffAdd}) => {

  const [form] = Form.useForm<Staff>();
  const [messageApi, messageContextHolder] = message.useMessage();

  const rules = {
    name: [
      { required: true, message: '请输入姓名' }
    ],
  };

  let staffForm: Partial<Staff> = {}

  const [title, setTitle] = useState('新增员工');

  useEffect(() => {
    if (!visible) {
      return
    }
    if (id) {
      setTitle('编辑员工')
      initStaffFormById(id)
    } else {
      setTitle('新增员工')
      form.resetFields();
    }
  }, [visible]);

  const initStaffFormById = async (id: number) => {
    const resp: Result<Staff> = await staffApi.findById(id)
    if (resp && resp.code === 1 && resp.data) {
      staffForm = resp.data
      form.setFieldsValue(resp.data);
    }
  }

  const onSave = async () => {
    try {
      await form.validateFields()

      let staff2Save:Staff = form.getFieldsValue()
      if (id) {
        staff2Save = Object.assign(staffForm, staff2Save)
      }
      const resp: Result<void> = await staffApi.save(staff2Save);
      if (!resp || resp.code !== 1) {
        messageApi.error('保存失败:' + (resp.msg ? resp.msg : '未知异常'));
        return
      }
      messageApi.success('保存成功');
      onBack()
    } catch (error) {
      console.error('There was an error submitting the form!', error);
    }
  };

  const onReset = () => {
    setTitle('新增员工')
    form.resetFields();
  };
  

  const onBack = () => {
    onCloseStaffAdd()
  };

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onSave}>保存</Button>
      <Button onClick={onReset} style={{marginLeft: 'var(--button-margin-left)'}}>重置</Button>
      <Button type="primary" onClick={onBack} style={{marginLeft: 'var(--button-margin-left)'}}>关闭</Button>
    </div>
  );

  return (
    <Modal title={title} open={visible} onCancel={onCloseStaffAdd} width={'var(--modal-width)'}
        footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      {messageContextHolder}
      <Form form={form} name="staffForm" labelCol={{span: 6}}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="name" label="姓名" rules={rules.name}>
              <Input maxLength={64} placeholder="请输入姓名"/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="phone" label="联系电话">
              <Input maxLength={20} placeholder="请输入联系电话"/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="position" label="岗位">
              <Input maxLength={64} placeholder="请输入岗位"/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="specialty" label="特长">
              <Input maxLength={255} placeholder="请输入特长"/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default StaffAdd;
