// angular_ngzorro/src/app/staff/staff-selector.component.ts
import {Component, EventEmitter, OnInit, Output} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {StaffService} from '../../service/staff.service';
import {StaffQueryForm} from '../../types/req/StaffQueryForm';
import {SharedModule} from '../shared.module';
import {Staff} from '../../types/resp/Staff';
import {Page} from '../../types/page';
import {NzModalService} from 'ng-zorro-antd/modal';
import {MODAL_WIDTH} from '../../const';

@Component({
  selector: 'staff-selector',
  imports: [
    SharedModule
  ],
  templateUrl: './staff-selector.component.html',
  standalone: true
})
export class StaffSelectorComponent implements OnInit {
  searchForm!: FormGroup;
  searchLoading: boolean = false
  listOfData: Staff[] = [];
  total: number = 0
  isVisible: boolean = false
  title: string = '员工选择器(双击行选中)'
  modalWidth: string = MODAL_WIDTH


  @Output() staffSelectedEvent = new EventEmitter<{}>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private staffService: StaffService,
    private modal: NzModalService
  ) {}

  ngOnInit(): void {
    this.searchForm = this.fb.group({
      name: [''],
      phone: [''],
    })
    this.onSearch()
  }

  onReset() {
    this.searchForm.reset()
  }

  onSearch() {
    try {
      this.searchLoading = true
      this.staffService.find(new StaffQueryForm(this.searchForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          const page: Page<Staff> | undefined = resp.data
          if (page && page.list.length > 0) {
            this.listOfData = page.list
            this.total = page.total
          }
        },
        complete: () => {
          this.searchLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onRowDblClick(row: Staff, event: MouseEvent) {
    this.isVisible = false
    this.staffSelectedEvent.emit({
      staffId: row.id,
      staffName: row.name,
      staffPhone: row.phone,
    });
  }

  onBack() {
    this.isVisible = false
  }

  display() {
    this.isVisible = true
    this.searchForm.reset();
  }

}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form nz-form class="search-form" [formGroup]="searchForm" (keydown.enter)="onSearch()" nzLayout="inline">
      <nz-form-item>
        <nz-form-label nzFor="name">姓名</nz-form-label>
        <nz-form-control>
          <input nz-input formControlName="name" placeholder="请输入姓名" />
        </nz-form-control>
      </nz-form-item>
<nz-form-item>
        <nz-form-label nzFor="phone">联系电话</nz-form-label>
        <nz-form-control>
          <input nz-input formControlName="phone" placeholder="请输入联系电话" />
        </nz-form-control>
      </nz-form-item>
      <button nz-button type="button" nzType="primary" [nzLoading]="searchLoading" (click)="onSearch()">查询</button>
      <button nz-button type="button" class="margin-button" (click)="onReset()">重置</button>
    </form>
    <nz-table #basicTable [nzData]="listOfData" [nzTotal]="total" [nzLoading]="searchLoading" nzSize="small">
      <thead>
        <tr>
          <th>姓名</th>
          <th>联系电话</th>
          <th>岗位</th>
          <th>特长</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let data of basicTable.data" (dblclick)="onRowDblClick(data, $event)">
          <td>{{data.name}}</td>
          <td>{{data.phone}}</td>
          <td>{{data.position}}</td>
          <td>{{data.specialty}}</td>
        </tr>
      </tbody>
    </nz-table>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>

// react_antd/src/pages/staff/StaffSelector.tsx
import React, {useEffect, useState} from 'react';
import {Button, Form, Input, Modal, Table, TableProps} from 'antd';
import type {Staff} from "@/types/resp/staff";
import staffApi from '@/api/staffApi'
import {Result} from "@/types/result";
import {Page} from "@/types/page";


interface StaffSelectorProps {
  visible: boolean;
  onStaffSelected: (selectedStaff: { staffId?: number;staffName?: string;staffPhone?: string; }) => void;
  onCloseStaffSelector: () => void;
}

const StaffSelector: React.FC<StaffSelectorProps> = ({visible, onStaffSelected, onCloseStaffSelector}) => {

  const [staffSelectorForm] = Form.useForm();

  const onFinish = async () => {
    await onSearch()
  };

  const onReset = () => {
    staffSelectorForm.resetFields();
  };

  const [data, setData] = useState<Staff[]>([]);
  const onSearch = async () => {
    try {
      const resp: Result<Page<Staff>> = await staffApi.find(staffSelectorForm.getFieldsValue())
      if (resp && resp.code === 1) {
        if (resp.data) {
          const page: Page<Staff> = resp.data
          if (page && page.list.length > 0) {
            setData(page.list)
          }
        }
      }
    } catch (e) {
      console.log('获取数据异常', e)
    }
  };

  const columns: TableProps<Staff>['columns'] = [
    {title: '姓名', dataIndex: 'name', key: 'name'},
    {title: '联系电话', dataIndex: 'phone', key: 'phone'},
    {title: '岗位', dataIndex: 'position', key: 'position'},
    {title: '特长', dataIndex: 'specialty', key: 'specialty'},
  ];

  const handleRowDoubleClick = (row: Staff) => {
    onStaffSelected({
      staffId: row.id,
      staffName: row.name,
      staffPhone: row.phone,
    })
  };

  const selectorFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onCloseStaffSelector}>关闭</Button>
    </div>
  );

  useEffect(() => {
    if (visible) {
      onSearch();
    }
  }, [visible]);


  return (
    <Modal title={"员工选择器(双击行选中)"} open={visible} onCancel={onCloseStaffSelector}
        width={'var(--modal-width)'} footer={selectorFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      <Form form={staffSelectorForm} onFinish={onFinish} layout={"inline"}>
        <Form.Item name="name" label="姓名">
          <Input maxLength={64} placeholder="请输入姓名"/>
        </Form.Item>
        <Form.Item name="phone" label="联系电话">
          <Input maxLength={20} placeholder="请输入联系电话"/>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" htmlType="submit">查询</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button onClick={onReset}>重置</Button>
        </Form.Item>
      </Form>
      <Table<Staff> columns={columns} dataSource={data} size="small" rowKey={record => record.id}
                         pagination={{ position: ["bottomCenter"] }}
                         onRow={(row) => ({
                           onDoubleClick: (event) => {
                             event.preventDefault();
                             handleRowDoubleClick(row);
                           },
                         })}/>
    </Modal>
  );
};

export default StaffSelector;
