// v2_el/src/views/staff/StaffAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="staffForm" :label-width="formLabelWidth" ref="refStaffForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="姓名" prop="name">
            <el-input v-model="staffForm.name" placeholder="请输入姓名" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="联系电话" prop="phone">
            <el-input v-model="staffForm.phone" placeholder="请输入联系电话" maxlength="20"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="岗位" prop="position">
            <el-input v-model="staffForm.position" placeholder="请输入岗位" maxlength="64"></el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="特长" prop="specialty">
            <el-input v-model="staffForm.specialty" placeholder="请输入特长" maxlength="255"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button type="primary" @click="onReset" plain>重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script>
import staffApi from '@/api/staffApi'
export default {
  name: 'StaffAdd',
  components: {},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      staffForm: {
        name: '',
        phone: '',
        position: '',
        specialty: ''
      },
      rules: {
        name:[
          { required: true, message: '请输入姓名', trigger: 'blur' }
        ],
      },
    }
  },
  created () {
    if (this.id) {
      staffApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.staffForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.staffForm = {
        name: '',
        phone: '',
        position: '',
        specialty: ''
      }
      this.$emit('reset-staff-add-event')
    },
    onSave () {
      this.$refs.refStaffForm.validate((valid) => {
        if (valid) {
          staffApi.save(this.staffForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-staff-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    onBack () {
      this.$emit('close-staff-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>

// react_antd/src/pages/staff/StaffAdd.tsx
import React, {useEffect, useState} from "react";
import {Button, Col, Form, Input, message, Modal, Row} from "antd";
import type {Result} from "@/types/result";
import staffApi from "@/api/staffApi.ts";
import {Staff} from "@/types/resp/staff";

interface StaffAddProps {
  visible: boolean;
  id: number;
  onCloseStaffAdd: () => void;
}

const StaffAdd: React.FC<StaffAddProps> = ({visible, id, onCloseStaffAdd}) => {

  const [form] = Form.useForm<Staff>();
  const [messageApi, messageContextHolder] = message.useMessage();

  const rules = {
    name: [
      { required: true, message: '请输入姓名' }
    ],
  };

  let staffForm: Partial<Staff> = {}

  const [title, setTitle] = useState('新增员工');

  useEffect(() => {
    if (!visible) {
      return
    }
    if (id) {
      setTitle('编辑员工')
      initStaffFormById(id)
    } else {
      setTitle('新增员工')
      form.resetFields();
    }
  }, [visible]);

  const initStaffFormById = async (id: number) => {
    const resp: Result<Staff> = await staffApi.findById(id)
    if (resp && resp.code === 1 && resp.data) {
      staffForm = resp.data
      form.setFieldsValue(resp.data);
    }
  }

  const onSave = async () => {
    try {
      await form.validateFields()

      let staff2Save:Staff = form.getFieldsValue()
      if (id) {
        staff2Save = Object.assign(staffForm, staff2Save)
      }
      const resp: Result<void> = await staffApi.save(staff2Save);
      if (!resp || resp.code !== 1) {
        messageApi.error('保存失败:' + (resp.msg ? resp.msg : '未知异常'));
        return
      }
      messageApi.success('保存成功');
      onBack()
    } catch (error) {
      console.error('There was an error submitting the form!', error);
    }
  };

  const onReset = () => {
    setTitle('新增员工')
    form.resetFields();
  };
  

  const onBack = () => {
    onCloseStaffAdd()
  };

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onSave}>保存</Button>
      <Button onClick={onReset} style={{marginLeft: 'var(--button-margin-left)'}}>重置</Button>
      <Button type="primary" onClick={onBack} style={{marginLeft: 'var(--button-margin-left)'}}>关闭</Button>
    </div>
  );

  return (
    <Modal title={title} open={visible} onCancel={onCloseStaffAdd} width={'var(--modal-width)'}
        footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      {messageContextHolder}
      <Form form={form} name="staffForm" labelCol={{span: 6}}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="name" label="姓名" rules={rules.name}>
              <Input maxLength={64} placeholder="请输入姓名"/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="phone" label="联系电话">
              <Input maxLength={20} placeholder="请输入联系电话"/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="position" label="岗位">
              <Input maxLength={64} placeholder="请输入岗位"/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="specialty" label="特长">
              <Input maxLength={255} placeholder="请输入特长"/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default StaffAdd;
