// v2_el/src/views/admin/AdminList.vue
<template>
  <div class="admin-list">
    <div class="breadcrumb">
      <el-breadcrumb separator="/">
        <el-breadcrumb-item to="Home" :replace="true">首页</el-breadcrumb-item>
        <el-breadcrumb-item>管理员列表</el-breadcrumb-item>
      </el-breadcrumb>
    </div>
    <el-form :inline="true" :model="searchParams">
      <el-form-item label="用户名">
        <el-input v-model="searchParams.username" placeholder="请输入用户名" maxlength="64"></el-input>
      </el-form-item>
      <el-form-item label="姓名">
        <el-input v-model="searchParams.name" placeholder="请输入姓名" maxlength="64"></el-input>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="onSearch">查询</el-button>
        <el-button @click="onReset">重置</el-button>
        <el-button type="primary" @click="onAdd">新增</el-button>
      </el-form-item>
    </el-form>

    <el-table
      :data="pageData.list"
      border
      v-loading="pageData.loading"
      size="mini"
      header-cell-class-name="table-header-cell-font"
      cell-class-name="table-cell-font">
      <el-table-column prop="username" label="用户名"></el-table-column>
      <el-table-column prop="password" label="密码"></el-table-column>
      <el-table-column prop="name" label="姓名"></el-table-column>
      <el-table-column prop="createTime" label="创建时间"></el-table-column>
      <el-table-column prop="modifyTime" label="最后修改时间"></el-table-column>
      <el-table-column fixed="right" label="操作" width="250">
        <template v-slot="{ row }">
          <el-button @click.native.prevent="editRow(row.id)" type="primary">编辑</el-button>
          <el-button @click.native.prevent="delRow(row.id)" type="danger" plain>删除</el-button>
          <el-button @click.native.prevent="detailRow(row.id)" type="primary" plain>详情</el-button>
        </template>
      </el-table-column>
    </el-table>
    <div class="table-pagination">
      <el-pagination
        @current-change="paginationChange"
        :current-page="pageData.current"
        :page-sizes="pageData.pageSizes"
        :page-size="pageData.size"
        background
        layout="total, prev, pager, next, jumper"
        :total="pageData.count">
      </el-pagination>
    </div>
    <el-dialog :visible.sync="adminAddVisible" v-if="adminAddVisible" :title="adminAddTitle" :top="dialogTop" :width="dialogWidth" :modal-append-to-body="true">
      <admin-add :id="selectedAdminId" @close-admin-add-event="handleCloseAdminAddEvent" @reset-admin-add-event="handleResetAdminAddEvent">
      </admin-add>
    </el-dialog>
    <el-dialog :visible.sync="adminViewVisible" v-if="adminViewVisible" title="管理员详情" :top="dialogTop" :width="dialogWidth">
      <admin-view :id="selectedAdminId" @close-admin-view-event="handleCloseAdminViewEvent">
      </admin-view>
    </el-dialog>
  </div>
</template>

<script>
import adminApi from '@/api/adminApi'
import AdminAdd from "@/views/admin/AdminAdd.vue"
import AdminView from "@/views/admin/AdminView.vue"
import listQueryMixin from '@/mixins/listQueryMixin'
export default {
  name: 'AdminList',
  components: {AdminAdd, AdminView},
  mixins: [
    listQueryMixin
  ],
  data () {
    return {
      searchParams: {
        username: '',
        name: ''
      },
      adminAddVisible: false,
      adminAddTitle: '',
      adminViewVisible: false,
      selectedAdminId: 0
    }
  },
  methods: {
    getPageData (p) {
      return adminApi.find(p)
    },
    onSearch () {
      this._getPageData()
    },
    onReset () {
      this.searchParams = {
        username: '',
        name: ''
      }
      this.pageData.pageIndex = 1
      this._getPageData()
    },
    onAdd () {
      this.selectedAdminId = ''
      this.adminAddVisible = true
      this.adminAddTitle = '管理员新增'
    },
    editRow (id) {
      this.selectedAdminId = id
      this.adminAddVisible = true
      this.adminAddTitle = '管理员编辑'
    },
    delRow (id) {
      if (!id) {
        return
      }
      this.$confirm('确定要删除吗?', '删除提示', {
        confirmButtonText: '确定',
        cancelButtonText: '取消',
        type: 'warning'
      }).then(() => {
        adminApi.del(id)
          .then((resp) => {
            if (resp && resp.code === 1) {
              this.$message.success('删除成功!')
              this.onSearch()
            } else {
              this.$message.error('保存失败:' + (resp.msg ? resp.msg : '原因未知'))
            }
          })
          .catch(error => {
            console.error('获取数据失败:', error)
          })
      }).catch(() => {})
    },
    detailRow (id) {
      this.selectedAdminId = id
      this.adminViewVisible = true
    },
    handleCloseAdminViewEvent () {
      this.adminViewVisible = false
    },
    handleResetAdminAddEvent () {
      this.adminAddTitle = '管理员新增'
    },
    handleCloseAdminAddEvent (params) {
      if (params && params.search) {
        this.onSearch()
      }
      this.adminAddVisible = false
    }
  }
}
</script>

<style lang="scss">
</style>

// react_antd/src/pages/admin/AdminList.tsx
import React, {useCallback, useEffect, useState} from 'react';
import {Breadcrumb, Button, Form, Input, message, Modal, Space, Table, TableProps} from 'antd';
import {useNavigate} from "react-router-dom";
import type {Admin} from "@/types/resp/admin";
import adminApi from '@/api/adminApi'
import {Result} from "@/types/result";
import {Page} from "@/types/page";
import AdminAdd from "@/pages/admin/AdminAdd.tsx";
import AdminView from "@/pages/admin/AdminView.tsx";


const AdminList: React.FC = () => {

  const navigate = useNavigate();
  const [messageApi, messageContextHolder] = message.useMessage();
  const [modal, modalContextHolder] = Modal.useModal();

  const handleClick = (path: string) => {
    navigate(path);
  };

  const breadcrumbsItems = [
    {title: '首页', className: 'breadcrumbHome', onClick: () => handleClick('/Home')},
    {title: '管理员列表'}
  ]

  const [form] = Form.useForm();

  const onFinish = async () => {
    await onSearch()
  };

  const onReset = () => {
    form.resetFields();
  };

  const [data, setData] = useState<Admin[]>([]);
  const onSearch = async () => {
    try {
      const resp: Result<Page<Admin>> = await adminApi.find(form.getFieldsValue())
      if (resp && resp.code === 1) {
        if (resp.data) {
          const page: Page<Admin> = resp.data
          if (page && page.list.length > 0) {
            setData(page.list)
          }
        }
      }
    } catch (e) {
      console.log('获取数据异常', e)
    }
  };

  const columns: TableProps<Admin>['columns'] = [
    {title: '用户名', dataIndex: 'username', key: 'username'},
    {title: '密码', dataIndex: 'password', key: 'password'},
    {title: '姓名', dataIndex: 'name', key: 'name'},
    {title: '创建时间', dataIndex: 'createTime', key: 'createTime'},
    {title: '最后修改时间', dataIndex: 'modifyTime', key: 'modifyTime'},
    {
      title: '操作',
      key: 'action',
      width: '250px',
      render: (_, record) => (
        <Space size="middle">
          <Button type="primary" onClick={() => editRow(record.id)}>编辑</Button>
          <Button danger onClick={() => delRow(record.id)}>删除</Button>
          <Button color="primary" variant="outlined" onClick={() => detailRow(record)}>详情</Button>
        </Space>
      ),
    },
  ];

  const [adminAddVisible, setAdminAddVisible] = useState(false);
  const [adminViewVisible, setAdminViewVisible] = useState(false);
  const [selectedAdminId, setSelectedAdminId] = useState(0)
  const [selectedAdmin, setSelectedAdmin] = useState({})

  const onAdd = () => {
    setSelectedAdminId(0)
    setAdminAddVisible(true)
  };

  const editRow = (id: number) => {
    setSelectedAdminId(id)
    setAdminAddVisible(true)
  };

  const delRow = useCallback(async (id: number) => {
    const confirmed = await modal.confirm({
      title: '删除提示',
      content: (
        <>
          确定要删除吗?
        </>
      ),
      okText: '确定',
      cancelText: '取消',
      type: 'warning'
    });

    if (confirmed) {
      adminApi.del(id)
        .then((resp) => {
          if (resp && resp.code === 1) {
            messageApi.success('删除成功!')
            onSearch()
          } else {
            messageApi.error('操作失败:' + (resp.msg ? resp.msg : '原因未知'))
          }
        })
        .catch(error => {
          console.error('操作失败:', error)
        })
    }
  }, [modal]);

  const detailRow = (record: Admin) => {
    setSelectedAdmin(record)
    setAdminViewVisible(true)
  };


  const handleCloseAdminAdd = () => {
    setAdminAddVisible(false)
  };

  const handleCloseAdminView = () => {
    setAdminViewVisible(false)
  };

  useEffect(() => {
    onSearch();

    return () => {
    };
  }, []);

  return (
    <div className="adminList">
      {messageContextHolder}
      {modalContextHolder}
      <Breadcrumb items={breadcrumbsItems} style={{marginBottom: 'var(--container-margin)'}} />
      <Form form={form} onFinish={onFinish} layout={"inline"}>
        <Form.Item name="username" label="用户名">
          <Input maxLength={64} placeholder="请输入用户名"/>
        </Form.Item>
        <Form.Item name="name" label="姓名">
          <Input maxLength={64} placeholder="请输入姓名"/>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" htmlType="submit">查询</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button onClick={onReset}>重置</Button>
        </Form.Item>
        <Form.Item label={null}>
          <Button type="primary" onClick={onAdd}>新增</Button>
        </Form.Item>
      </Form>
      <Table<Admin> columns={columns} dataSource={data} size="small" rowKey={record => record.id} pagination={{ position: ["bottomCenter"] }} style={{marginTop: 'var(--container-margin)'}} />
      <AdminAdd visible={adminAddVisible} onCloseAdminAdd={handleCloseAdminAdd} id={selectedAdminId} />
      <AdminView visible={adminViewVisible} onCloseAdminView={handleCloseAdminView} viewRow={selectedAdmin} />
    </div>
  );
};

export default AdminList;
