// angular_ngzorro/src/app/admin/admin-add.component.ts
import {Component, EventEmitter, OnInit, Output} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {AdminService} from '../../service/admin.service';
import {SharedModule} from '../shared.module';
import {AdminForm} from '../../types/req/AdminForm';
import {MODAL_WIDTH} from '../../const'

@Component({
  selector: 'admin-add',
  imports: [
    SharedModule
  ],
  templateUrl: './admin-add.component.html',
  standalone: true
})
export class AdminAddComponent implements OnInit {
  adminToSave:AdminForm = {};
  adminForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增管理员'
  modalWidth: string = MODAL_WIDTH

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private adminService: AdminService
  ) {}

  ngOnInit(): void {
    this.adminForm = this.fb.group({
      username: ['', [Validators.required]],
      password: ['', [Validators.required]],
      name: ['', [Validators.required]],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.adminForm.controls) {
        this.adminForm.controls[i].markAsDirty();
        this.adminForm.controls[i].updateValueAndValidity();
      }
      if (!this.adminForm.valid) {
        this.saveLoading = false
        return
      }
      this.adminService.save(Object.assign(this.adminToSave, this.adminForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增管理员'.slice()
    this.adminForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改管理员'
      this.saveLoading = true
      this.adminService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.adminToSave = resp.data
            this.adminForm.patchValue(this.adminToSave);
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="adminForm">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="username" nzRequired>用户名</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入用户名'">
              <input nz-input formControlName="username" placeholder="请输入用户名" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="password" nzRequired>密码</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入密码'">
              <input nz-input formControlName="password" placeholder="请输入密码" maxlength="255"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="name" nzRequired>姓名</nz-form-label>
            <nz-form-control [nzErrorTip]="'请输入姓名'">
              <input nz-input formControlName="name" placeholder="请输入姓名" maxlength="64"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>

// react_antd/src/pages/admin/AdminAdd.tsx
import React, {useEffect, useState} from "react";
import {Button, Col, Form, Input, message, Modal, Row} from "antd";
import type {Result} from "@/types/result";
import adminApi from "@/api/adminApi.ts";
import {Admin} from "@/types/resp/admin";

interface AdminAddProps {
  visible: boolean;
  id: number;
  onCloseAdminAdd: () => void;
}

const AdminAdd: React.FC<AdminAddProps> = ({visible, id, onCloseAdminAdd}) => {

  const [form] = Form.useForm<Admin>();
  const [messageApi, messageContextHolder] = message.useMessage();

  const rules = {
    username: [
      { required: true, message: '请输入用户名' }
    ],
    password: [
      { required: true, message: '请输入密码' }
    ],
    name: [
      { required: true, message: '请输入姓名' }
    ],
  };

  let adminForm: Partial<Admin> = {}

  const [title, setTitle] = useState('新增管理员');

  useEffect(() => {
    if (!visible) {
      return
    }
    if (id) {
      setTitle('编辑管理员')
      initAdminFormById(id)
    } else {
      setTitle('新增管理员')
      form.resetFields();
    }
  }, [visible]);

  const initAdminFormById = async (id: number) => {
    const resp: Result<Admin> = await adminApi.findById(id)
    if (resp && resp.code === 1 && resp.data) {
      adminForm = resp.data
      form.setFieldsValue(resp.data);
    }
  }

  const onSave = async () => {
    try {
      await form.validateFields()

      let admin2Save:Admin = form.getFieldsValue()
      if (id) {
        admin2Save = Object.assign(adminForm, admin2Save)
      }
      const resp: Result<void> = await adminApi.save(admin2Save);
      if (!resp || resp.code !== 1) {
        messageApi.error('保存失败:' + (resp.msg ? resp.msg : '未知异常'));
        return
      }
      messageApi.success('保存成功');
      onBack()
    } catch (error) {
      console.error('There was an error submitting the form!', error);
    }
  };

  const onReset = () => {
    setTitle('新增管理员')
    form.resetFields();
  };
  

  const onBack = () => {
    onCloseAdminAdd()
  };

  const addFooter = (
    <div className='custom-footer'>
      <Button type="primary" onClick={onSave}>保存</Button>
      <Button onClick={onReset} style={{marginLeft: 'var(--button-margin-left)'}}>重置</Button>
      <Button type="primary" onClick={onBack} style={{marginLeft: 'var(--button-margin-left)'}}>关闭</Button>
    </div>
  );

  return (
    <Modal title={title} open={visible} onCancel={onCloseAdminAdd} width={'var(--modal-width)'}
        footer={addFooter} style={{marginTop: 'var(--modal-margin-top)'}}>
      {messageContextHolder}
      <Form form={form} name="adminForm" labelCol={{span: 6}}>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="username" label="用户名" rules={rules.username}>
              <Input maxLength={64} placeholder="请输入用户名"/>
            </Form.Item>
          </Col>
          <Col span={11}>
            <Form.Item name="password" label="密码" rules={rules.password}>
              <Input maxLength={255} placeholder="请输入密码"/>
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={10}>
          <Col span={11}>
            <Form.Item name="name" label="姓名" rules={rules.name}>
              <Input maxLength={64} placeholder="请输入姓名"/>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    </Modal>
  )
}

export default AdminAdd;
