// angular_ngzorro/src/app/room-maintenance-record/room-maintenance-record-add.component.ts
import {Component, EventEmitter, OnInit, Output, ViewChild} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {NzMessageService} from 'ng-zorro-antd/message';
import {RoomMaintenanceRecordService} from '../../service/room-maintenance-record.service';
import {SharedModule} from '../shared.module';
import {RoomMaintenanceRecordForm} from '../../types/req/RoomMaintenanceRecordForm';
import {MODAL_WIDTH} from '../../const'
import {RoomSelectorComponent} from '../room/room-selector.component';
import {StaffSelectorComponent} from '../staff/staff-selector.component';

@Component({
  selector: 'room-maintenance-record-add',
  imports: [
    RoomSelectorComponent,
    StaffSelectorComponent,
    SharedModule
  ],
  templateUrl: './room-maintenance-record-add.component.html',
  standalone: true
})
export class RoomMaintenanceRecordAddComponent implements OnInit {
  roomMaintenanceRecordToSave:RoomMaintenanceRecordForm = {};
  roomMaintenanceRecordForm!: FormGroup;
  isVisible: boolean = false
  saveLoading: boolean = false
  title: string = '新增房间维护记录'
  modalWidth: string = MODAL_WIDTH

  @ViewChild(RoomSelectorComponent, { static: false }) roomSelectorComponent!: RoomSelectorComponent;
  @ViewChild(StaffSelectorComponent, { static: false }) staffSelectorComponent!: StaffSelectorComponent;

  @Output() addedEvent = new EventEmitter<boolean>();

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private roomMaintenanceRecordService: RoomMaintenanceRecordService
  ) {}

  ngOnInit(): void {
    this.roomMaintenanceRecordForm = this.fb.group({
      roomId: [0],
      roomNumber: ['', [Validators.required]],
      staffId: [0],
      staffName: ['', [Validators.required]],
      staffPhone: ['', [Validators.required]],
      startTime: [''],
      endTime: [''],
      content: [''],
    })
  }

  onSave() {
    try {
      this.saveLoading = true
      for (const i in this.roomMaintenanceRecordForm.controls) {
        this.roomMaintenanceRecordForm.controls[i].markAsDirty();
        this.roomMaintenanceRecordForm.controls[i].updateValueAndValidity();
      }
      if (!this.roomMaintenanceRecordForm.valid) {
        this.saveLoading = false
        return
      }
      this.roomMaintenanceRecordService.save(Object.assign(this.roomMaintenanceRecordToSave, this.roomMaintenanceRecordForm.value)).subscribe({
        next: (resp) => {
          if (!resp || resp.code !== 1) {
            this.message.error(resp && resp.msg ? resp.msg : '操作异常')
            return
          }
          this.message.success("保存成功")
          this.onBack(true)
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } catch (e) {
      console.log('获取数据异常', e)
    }
  }

  onReset() {
    this.title = '新增房间维护记录'.slice()
    this.roomMaintenanceRecordForm.reset()
  }

  onBack(addedFlag=false) {
    this.isVisible = false
    this.addedEvent.emit(addedFlag);
  }

  display(id: number) {
    this.isVisible = true
    if (id) {
      this.title = '修改房间维护记录'
      this.saveLoading = true
      this.roomMaintenanceRecordService.findById(id).subscribe({
        next: (resp) => {
          if (resp && resp.code === 1 && resp.data) {
            this.roomMaintenanceRecordToSave = resp.data
            this.roomMaintenanceRecordForm.patchValue(this.roomMaintenanceRecordToSave);
          }
        },
        complete: () => {
          this.saveLoading = false
        }
      })
    } else {
      this.onReset()
    }
  }

  findRoom() {
    this.roomSelectorComponent.display()
  }

  handleRoomSelectedEvent(selectedRoom: { roomId?: number; roomNumber?: string; }) {
    if (selectedRoom && 'roomId' in selectedRoom) {
      this.roomMaintenanceRecordForm.patchValue(selectedRoom);
    }
  }

  findStaff() {
    this.staffSelectorComponent.display()
  }

  handleStaffSelectedEvent(selectedStaff: { staffId?: number; staffName?: string;staffPhone?: string; }) {
    if (selectedStaff && 'staffId' in selectedStaff) {
      this.roomMaintenanceRecordForm.patchValue(selectedStaff);
    }
  }
}

<nz-modal [(nzVisible)]="isVisible" [nzWidth]="modalWidth" (nzOnCancel)="onBack()" [nzStyle]="{'top': '50px'}">
  <div *nzModalTitle>{{ title }}</div>
  <ng-container *nzModalContent>
    <form [formGroup]="roomMaintenanceRecordForm" (keydown.enter)="$event.preventDefault()">
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="roomNumber" nzRequired>房号</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择房号'">
              <nz-input-group nzSearch [nzAddOnAfter]="roomNumberSuffixIconButton">
                <input nz-input formControlName="roomNumber" placeholder="请选择房号" readonly />
              </nz-input-group>
              <ng-template #roomNumberSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findRoom()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="staffName" nzRequired>员工姓名</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择员工姓名'">
              <nz-input-group nzSearch [nzAddOnAfter]="staffNameSuffixIconButton">
                <input nz-input formControlName="staffName" placeholder="请选择员工姓名" readonly />
              </nz-input-group>
              <ng-template #staffNameSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findStaff()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="staffPhone" nzRequired>员工联系电话</nz-form-label>
            <nz-form-control [nzErrorTip]="'请选择员工联系电话'">
              <nz-input-group nzSearch [nzAddOnAfter]="staffPhoneSuffixIconButton">
                <input nz-input formControlName="staffPhone" placeholder="请选择员工联系电话" readonly />
              </nz-input-group>
              <ng-template #staffPhoneSuffixIconButton>
                <button nz-button nzType="primary" nzSearch (click)="findStaff()"><nz-icon nzType="search" /></button>
              </ng-template>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="startTime">开始时间</nz-form-label>
            <nz-form-control >
              <nz-date-picker nzShowTime formControlName="startTime" nzFormat="yyyy-MM-dd HH:mm:ss"></nz-date-picker>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="endTime">结束时间</nz-form-label>
            <nz-form-control >
              <nz-date-picker nzShowTime formControlName="endTime" nzFormat="yyyy-MM-dd HH:mm:ss"></nz-date-picker>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
      <nz-row [nzGutter]="10">
        <nz-col [nzSpan]="12">
          <nz-form-item>
            <nz-form-label [nzSpan]="6" nzFor="content">维护内容</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="content" placeholder="请输入维护内容" maxlength="65535"/>
            </nz-form-control>
          </nz-form-item>
        </nz-col>
      </nz-row>
    </form>
  </ng-container>
  <div *nzModalFooter>
    <div class="form-button-container">
      <button nz-button nzType="primary" (click)="onSave()" [nzLoading]="saveLoading">保存</button>
      <button nz-button nzType="default" (click)="onReset()" [nzLoading]="saveLoading">重置</button>
      <button nz-button nzType="default" (click)="onBack()">关闭</button>
    </div>
  </div>
</nz-modal>
<room-selector (roomSelectedEvent)="handleRoomSelectedEvent($event)"></room-selector>
<staff-selector (staffSelectedEvent)="handleStaffSelectedEvent($event)"></staff-selector>

// v2_el/src/views/roomMaintenanceRecord/RoomMaintenanceRecordAdd.vue
<template>
  <div class="pop-dialog-container">
    <div class="pop-dialog-main">
    <el-form label-position="right" :model="roomMaintenanceRecordForm" :label-width="formLabelWidth" ref="refRoomMaintenanceRecordForm" :rules="rules">
      <el-row>
        <el-col :span="11">
          <el-form-item label="房号" prop="roomNumber">
            <el-input v-model="roomMaintenanceRecordForm.roomNumber" placeholder="请选择房号" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findRoom"></i>
            </el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="员工姓名" prop="staffName">
            <el-input v-model="roomMaintenanceRecordForm.staffName" placeholder="请选择员工姓名" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findStaff"></i>
            </el-input>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="员工联系电话" prop="staffPhone">
            <el-input v-model="roomMaintenanceRecordForm.staffPhone" placeholder="请选择员工联系电话" readonly="readonly">
              <i slot="suffix" class="el-input__icon el-icon-search" @click="findStaff"></i>
            </el-input>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="开始时间" prop="startTime">
            <el-date-picker
                v-model="roomMaintenanceRecordForm.startTime" type="datetime" placeholder="开始时间" value-format="yyyy-MM-dd HH:mm:ss">
            </el-date-picker>
          </el-form-item>
        </el-col>
      </el-row>
      <el-row>
        <el-col :span="11">
          <el-form-item label="结束时间" prop="endTime">
            <el-date-picker
                v-model="roomMaintenanceRecordForm.endTime" type="datetime" placeholder="结束时间" value-format="yyyy-MM-dd HH:mm:ss">
            </el-date-picker>
          </el-form-item>
        </el-col>
        <el-col :span="11">
          <el-form-item label="维护内容" prop="content">
            <el-input v-model="roomMaintenanceRecordForm.content" placeholder="请输入维护内容" maxlength="65535"></el-input>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    </div>
    <div class="pop-dialog-footer">
      <el-row>
        <el-col :span="11" :offset="6">
          <div class="form-button-container">
            <el-button type="primary" @click="onSave">保存</el-button>
            <el-button type="primary" @click="onReset" plain>重置</el-button>
            <el-button type="primary" @click="onBack">关闭</el-button>
          </div>
        </el-col>
      </el-row>
    </div>
    <el-dialog :visible.sync="roomSelectorVisible" v-if="roomSelectorVisible" title="房间选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <room-selector @room-selected-event="handleRoomSelectedEvent">
      </room-selector>
    </el-dialog>
    <el-dialog :visible.sync="staffSelectorVisible" v-if="staffSelectorVisible" title="员工选择器(双击行选中)" :top="dialogTop" :width="dialogWidth" :append-to-body="true">
      <staff-selector @staff-selected-event="handleStaffSelectedEvent">
      </staff-selector>
    </el-dialog>
  </div>
</template>

<script>
import roomMaintenanceRecordApi from '@/api/roomMaintenanceRecordApi'
import RoomSelector from "@/views/room/RoomSelector.vue";
import StaffSelector from "@/views/staff/StaffSelector.vue";
export default {
  name: 'RoomMaintenanceRecordAdd',
  components: {RoomSelector,StaffSelector,},
  props: ['id'],
  mixins: [
  ],
  data () {
    return {
      roomMaintenanceRecordForm: {
        roomId: '',
        roomNumber: '',
        staffId: '',
        staffName: '',
        staffPhone: '',
        startTime: '',
        endTime: '',
        content: ''
      },
      rules: {
        roomNumber:[
          { required: true, message: '请输入房号', trigger: 'blur' }
        ],
        staffName:[
          { required: true, message: '请输入员工姓名', trigger: 'blur' }
        ],
        staffPhone:[
          { required: true, message: '请输入员工联系电话', trigger: 'blur' }
        ],
      },
      roomSelectorVisible: false,
      staffSelectorVisible: false,
    }
  },
  created () {
    if (this.id) {
      roomMaintenanceRecordApi.findById(Number(this.id))
        .then(resp => {
          if (resp && resp.code === 1) {
            this.roomMaintenanceRecordForm = resp.data
          } else {
            this.$message.error('获取数据失败')
          }
        })
        .catch(error => {
          console.error('获取数据失败:', error)
        })
    }
  },
  methods: {
    onReset () {
      this.roomMaintenanceRecordForm = {
        roomId: '',
        roomNumber: '',
        staffId: '',
        staffName: '',
        staffPhone: '',
        startTime: '',
        endTime: '',
        content: ''
      }
      this.$emit('reset-room-maintenance-record-add-event')
    },
    onSave () {
      this.$refs.refRoomMaintenanceRecordForm.validate((valid) => {
        if (valid) {
          roomMaintenanceRecordApi.save(this.roomMaintenanceRecordForm)
            .then((resp) => {
              if (resp && resp.code === 1) {
                this.$message.success('保存成功')
                this.$emit('close-room-maintenance-record-add-event', {search: true})
              } else {
                this.$message.error('保存失败:' + (resp.msg ? resp.msg : ''))
              }
            })
            .catch(error => {
              console.log(error)
              this.$message.error('保存失败')
            })
        } else {
          return false
        }
      })
    },
    findRoom () {
      this.roomSelectorVisible = true
    },
    handleRoomSelectedEvent (selectedRoom) {
      this.roomSelectorVisible = false
      if (selectedRoom && 'roomId' in selectedRoom && this.roomMaintenanceRecordForm.roomId !== selectedRoom['roomId']) {
        this.roomMaintenanceRecordForm.roomId = selectedRoom['roomId']
        this.roomMaintenanceRecordForm.roomNumber = selectedRoom['roomNumber']
      }
    },
    findStaff () {
      this.staffSelectorVisible = true
    },
    handleStaffSelectedEvent (selectedStaff) {
      this.staffSelectorVisible = false
      if (selectedStaff && 'staffId' in selectedStaff && this.roomMaintenanceRecordForm.staffId !== selectedStaff['staffId']) {
        this.roomMaintenanceRecordForm.staffId = selectedStaff['staffId']
        this.roomMaintenanceRecordForm.staffName = selectedStaff['staffName']
        this.roomMaintenanceRecordForm.staffPhone = selectedStaff['staffPhone']
      }
    },
    onBack () {
      this.$emit('close-room-maintenance-record-add-event')
    }
  }
}
</script>

<style lang="scss">
</style>
